// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Stream from "@reventlessdev/rescript-effect/src/Stream.res.mjs";
import * as Effect from "effect/Effect";
import * as Message$ReventlessCore from "../../src/Message.res.mjs";
import * as Counter_Callback$ReventlessCore from "../../src/components/Counter/Counter_Callback.res.mjs";

S.enableJson();

let capturedCountCalls = {
  contents: []
};

let capturedEventBatches = {
  contents: []
};

async function mockCountsDbCount(id, field, delta) {
  capturedCountCalls.contents = capturedCountCalls.contents.concat([[
      id,
      field,
      delta
    ]]);
  return {
    TAG: "Ok",
    _0: 0
  };
}

function mockJsonEventsHandler(stream) {
  return Effect.map(Stream.runCollect(stream), chunk => {
    capturedEventBatches.contents = capturedEventBatches.contents.concat([chunk]);
  });
}

let TestCounterSpec = {
  name: "TestCounter",
  countsDbCount: mockCountsDbCount,
  jsonEventsHandler: mockJsonEventsHandler
};

let TestCounterHandler = Counter_Callback$ReventlessCore.Make(TestCounterSpec);

function makeCountsJson(id, count) {
  return Message$ReventlessCore.encode({
    id: id,
    count: count
  }, Counter_Callback$ReventlessCore.countsStateSchema);
}

function reset() {
  capturedCountCalls.contents = [];
  capturedEventBatches.contents = [];
}

export {
  capturedCountCalls,
  capturedEventBatches,
  mockCountsDbCount,
  mockJsonEventsHandler,
  TestCounterSpec,
  TestCounterHandler,
  makeCountsJson,
  reset,
}
/*  Not a pure module */
