// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DomainDeadCode$ReventlessGwt from "../src/DomainDeadCode.res.mjs";

function writable(name, producesOpt, consumesOpt, linkedViewsOpt) {
  let produces = producesOpt !== undefined ? producesOpt : [];
  let consumes = consumesOpt !== undefined ? consumesOpt : [];
  let linkedViews = linkedViewsOpt !== undefined ? linkedViewsOpt : [];
  return {
    name: name,
    commands: [],
    producedEventTypes: produces,
    consumedEventTypes: consumes,
    linkedViews: linkedViews,
    consistencyRead: undefined,
    events: [],
    chapter: undefined
  };
}

function queryable(name, consumesOpt) {
  let consumes = consumesOpt !== undefined ? consumesOpt : [];
  return {
    name: name,
    queryField: "",
    schema: "",
    consumedEventTypes: consumes,
    linkedWriteSide: [],
    labelField: "id",
    searchableFields: [],
    statusField: undefined,
    visibility: undefined,
    chapter: undefined
  };
}

function automation(name, consumesOpt) {
  let consumes = consumesOpt !== undefined ? consumesOpt : [];
  return {
    name: name,
    consumedEventTypes: consumes,
    producedCommandTypes: [],
    targetName: "",
    chapter: undefined
  };
}

function structure(aggregatesOpt, readModelsOpt, stateViewSlicesOpt, stateChangeSlicesOpt, automationSlicesOpt, outboundTranslationSlicesOpt, extensionsOpt) {
  let aggregates = aggregatesOpt !== undefined ? aggregatesOpt : [];
  let readModels = readModelsOpt !== undefined ? readModelsOpt : [];
  let stateViewSlices = stateViewSlicesOpt !== undefined ? stateViewSlicesOpt : [];
  let stateChangeSlices = stateChangeSlicesOpt !== undefined ? stateChangeSlicesOpt : [];
  let automationSlices = automationSlicesOpt !== undefined ? automationSlicesOpt : [];
  let outboundTranslationSlices = outboundTranslationSlicesOpt !== undefined ? outboundTranslationSlicesOpt : [];
  let extensions = extensionsOpt !== undefined ? extensionsOpt : [];
  return {
    readModels: readModels,
    stateViewSlices: stateViewSlices,
    stateChangeSlices: stateChangeSlices,
    aggregates: aggregates,
    automationSlices: automationSlices,
    outboundTranslationSlices: outboundTranslationSlices,
    inboundTranslationSlices: [],
    extensions: extensions,
    extensionPoints: undefined
  };
}

globalThis.describe("DomainDeadCode.analyze — orphan events", () => {
  globalThis.test("flags a produced event no component consumes", async () => {
    let shop = structure([writable("Order", [
        "Shop.Placed",
        "Shop.Archived"
      ], undefined, undefined)], [queryable("Orders", ["Shop.Placed"])], undefined, undefined, undefined, undefined, undefined);
    let findings = DomainDeadCode$ReventlessGwt.analyze([[
        "Shop",
        shop
      ]]);
    globalThis.expect(findings.map(f => f.detail)).toEqual(["Shop.Archived"]);
    let f = findings[0];
    globalThis.expect([
      f.kind,
      f.pluginName,
      f.componentName
    ]).toEqual([
      "OrphanEvent",
      "Shop",
      "Order"
    ]);
  });
  globalThis.test("a consumer in ANY plugin clears the orphan (cross-plugin)", async () => {
    let shop = structure([writable("Order", ["Shop.Placed"], undefined, undefined)], undefined, undefined, undefined, undefined, undefined, undefined);
    let analytics = structure(undefined, undefined, undefined, undefined, [automation("OnPlaced", ["Shop.Placed"])], undefined, undefined);
    let findings = DomainDeadCode$ReventlessGwt.analyze([
      [
        "Shop",
        shop
      ],
      [
        "Analytics",
        analytics
      ]
    ]);
    globalThis.expect(findings.length).toBe(0);
  });
  globalThis.test("consumption via a state-view slice and a state-change DCB read both count", async () => {
    let s = structure([writable("Order", [
        "Shop.Placed",
        "Shop.Shipped"
      ], undefined, undefined)], undefined, [queryable("OrderView", ["Shop.Placed"])], [writable("Ship", undefined, ["Shop.Shipped"], undefined)], undefined, undefined, undefined);
    let findings = DomainDeadCode$ReventlessGwt.analyze([[
        "Shop",
        s
      ]]);
    globalThis.expect(findings.length).toBe(0);
  });
  globalThis.test("a linked classic read model clears all the aggregate's events (rule 2)", async () => {
    let shop = structure([writable("Order", [
        "Shop.Placed",
        "Shop.Archived"
      ], undefined, ["Orders"])], [queryable("Orders", undefined)], undefined, undefined, undefined, undefined, undefined);
    let findings = DomainDeadCode$ReventlessGwt.analyze([[
        "Shop",
        shop
      ]]);
    globalThis.expect(findings.length).toBe(0);
  });
  globalThis.test("an aggregate with no view and no consumer is fully orphaned", async () => {
    let shop = structure([writable("Audit", ["Shop.Logged"], undefined, undefined)], undefined, undefined, undefined, undefined, undefined, undefined);
    let findings = DomainDeadCode$ReventlessGwt.analyze([[
        "Shop",
        shop
      ]]);
    globalThis.expect(findings.map(f => f.detail)).toEqual(["Shop.Logged"]);
  });
  globalThis.test("state-change slices are scanned as producers too", async () => {
    let s = structure(undefined, undefined, undefined, [writable("Reserve", ["Shop.Reserved"], undefined, undefined)], undefined, undefined, undefined);
    let findings = DomainDeadCode$ReventlessGwt.analyze([[
        "Shop",
        s
      ]]);
    globalThis.expect(findings.map(f => [
      f.componentName,
      f.detail
    ])).toEqual([[
        "Reserve",
        "Shop.Reserved"
      ]]);
  });
});

export {
  writable,
  queryable,
  automation,
  structure,
}
/*  Not a pure module */
