// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let enabled = {
  contents: false
};

let pendingByMsgId = {};

function enableTracking() {
  enabled.contents = true;
}

function trackAppended(entries) {
  if (enabled.contents) {
    entries.forEach(param => {
      pendingByMsgId[param[0]] = param[1];
    });
    return;
  }
}

function resolve(msgIds) {
  msgIds.forEach(msgId => Stdlib_Dict.$$delete(pendingByMsgId, msgId));
}

function minPending() {
  let positions = Object.values(pendingByMsgId);
  let first = positions[0];
  if (first !== undefined) {
    return Stdlib_Array.reduce(positions, first, (a, b) => {
      if (a < b) {
        return a;
      } else {
        return b;
      }
    });
  }
}

function reset() {
  enabled.contents = false;
  Object.keys(pendingByMsgId).forEach(k => Stdlib_Dict.$$delete(pendingByMsgId, k));
}

export {
  enabled,
  pendingByMsgId,
  enableTracking,
  trackAppended,
  resolve,
  minPending,
  reset,
}
/* No side effect */
