// Generated by ReScript, PLEASE EDIT WITH CARE

import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as Api_Naming$ReventlessCore from "../components/Api/Api_Naming.res.mjs";
import * as PluginSpec$ReventlessCore from "./PluginSpec.res.mjs";
import * as ApiNoApiHelpers$ReventlessCore from "../components/Api/ApiNoApiHelpers.res.mjs";
import * as PluginsReadModelSpec$ReventlessCore from "./PluginsReadModelSpec.res.mjs";
import * as Platform_EventGraphReadModelSpec$ReventlessCore from "./Platform_EventGraphReadModelSpec.res.mjs";

let adminAuth = {
  tableName: "Plugin",
  group: "Admin"
};

let pluginExcludeFields = [
  "eventCollector",
  "extensionPointNames",
  "extensionNames"
];

let pluginUIOnlyExcludeFields = pluginExcludeFields.concat([
  "apiSchemaFragment",
  "uiFragments",
  "structure"
]);

let queryEntries = [
  {
    singleFieldName: Api_Naming$ReventlessCore.adminField("Plugin"),
    listFieldName: Api_Naming$ReventlessCore.adminField("Plugins"),
    returnTypeName: Api_Naming$ReventlessCore.adminField("Plugin"),
    stateSchema: PluginsReadModelSpec$ReventlessCore.stateSchema,
    specName: PluginsReadModelSpec$ReventlessCore.name,
    authorization: adminAuth,
    excludeFields: pluginExcludeFields
  },
  {
    singleFieldName: Api_Naming$ReventlessCore.adminField("PlatformEventGraph"),
    listFieldName: Api_Naming$ReventlessCore.adminField("PlatformEventGraphs"),
    returnTypeName: Api_Naming$ReventlessCore.adminField("PlatformEventGraph"),
    stateSchema: Platform_EventGraphReadModelSpec$ReventlessCore.stateSchema,
    specName: Platform_EventGraphReadModelSpec$ReventlessCore.name,
    authorization: adminAuth,
    excludeFields: []
  }
];

let constructorNames = DcbTag$Reventless.extractAllVariantNames(PluginSpec$ReventlessCore.commandSchema);

let filteredConstructorNames = ApiNoApiHelpers$ReventlessCore.filterNoApiVariants(constructorNames, PluginSpec$ReventlessCore.commandSchema);

let fieldNames = filteredConstructorNames.map(cname => Api_Naming$ReventlessCore.adminField(PluginSpec$ReventlessCore.name + "_" + cname));

let pluginAggregateMutationEntries = fieldNames.length === 0 ? [] : [{
      fieldNames: fieldNames,
      commandSchema: PluginSpec$ReventlessCore.commandSchema
    }];

export {
  adminAuth,
  pluginExcludeFields,
  pluginUIOnlyExcludeFields,
  queryEntries,
  pluginAggregateMutationEntries,
}
/* pluginUIOnlyExcludeFields Not a pure module */
