// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Effect from "effect/Effect";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as Message$ReventlessCore from "../Message.res.mjs";
import * as Compat$ReventlessInterop from "@reventlessdev/reventless-interop/src/Compat.res.mjs";
import * as PluginSpec$ReventlessCore from "./PluginSpec.res.mjs";
import * as ScheduleOps$ReventlessCore from "../util/ScheduleOps.res.mjs";
import * as CompatMatrix$ReventlessInterop from "@reventlessdev/reventless-interop/src/protocol/CompatMatrix.res.mjs";
import * as PluginReadModelSpec$ReventlessCore from "./PluginReadModelSpec.res.mjs";
import * as ExtensionPointMapping$ReventlessInfra from "@reventlessdev/reventless-infra/src/types/ExtensionPointMapping.res.mjs";
import * as PluginExtensionPointSpec$ReventlessInfra from "@reventlessdev/reventless-infra/src/types/PluginExtensionPointSpec.res.mjs";

function Make(Spec) {
  let forwardCommand = async (_id, command, extensionPointName, queryEngine) => {
    let jsons = await queryEngine.scan(PluginSpec$ReventlessCore.name, [
      [
        "extensionPointNames",
        "Contains",
        {
          TAG: "String",
          _0: extensionPointName
        }
      ],
      [
        "status",
        "Contains",
        {
          TAG: "String",
          _0: "Connected"
        }
      ]
    ], 1000);
    if (jsons.length === 0) {
      return Effect.runSync(Effect.logWarning(`ForwardCommand: Couldn't find Plugin with ExtensionPoint ` + extensionPointName));
    }
    let plugin = jsons[0];
    let exit = 0;
    let plugin$1;
    try {
      plugin$1 = Message$ReventlessCore.decode(plugin, PluginReadModelSpec$ReventlessCore.stateSchema);
      exit = 1;
    } catch (raw_err) {
      let err = Primitive_exceptions.internalToException(raw_err);
      let errMsg = Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_JsExn.fromException(err), Stdlib_JsExn.message), "unknown");
      return Effect.runSync(Effect.logError(`ForwardCommand: Couldn't decode Plugin: ` + errMsg));
    }
    if (exit === 1) {
      let extensionPoint = plugin$1.extensionPoints.find(extensionPoint => extensionPoint.name === extensionPointName);
      if (extensionPoint === undefined) {
        return Effect.runSync(Effect.logWarning(`ForwardCommand: Couldn't find ExtensionPoint ` + extensionPointName + ` in ` + plugin$1.name));
      }
      let exit$1 = 0;
      let val;
      try {
        val = await Spec.runtimeOps.messagePublish.sendMessageToChannel(extensionPoint.commandTopic, command);
        exit$1 = 2;
      } catch (raw_err$1) {
        let err$1 = Primitive_exceptions.internalToException(raw_err$1);
        let errMsg$1 = Stdlib_Option.getOr(Stdlib_Option.flatMap(Stdlib_JsExn.fromException(err$1), Stdlib_JsExn.message), "unknown");
        return Effect.runSync(Effect.logError(`PluginExtensionPoint_PluginMapping: Error on publish command: ` + errMsg$1));
      }
      if (exit$1 === 2) {
        return Effect.runSync(Effect.logInfo(`ForwardCommand: published command to ` + plugin$1.name + ` ` + extensionPoint.commandTopic));
      }
    }
  };
  let callHandler = async (createSchedule, deleteSchedule, queryEngine, directive) => {
    switch (directive.TAG) {
      case "CreateDisconnectSchedule" :
        let id = directive._0;
        return await createSchedule({
          name: Spec.environment + ("-" + id),
          rate: ScheduleOps$ReventlessCore.minutesFromNow(directive._1),
          payload: JSON.stringify(Message$ReventlessCore.encodeCommand$p({
            id: id,
            meta: Message$ReventlessCore.generateMeta("Core.Plugin", undefined, "Scheduler"),
            command: "DisconnectPlugin"
          }, S.string, PluginExtensionPointSpec$ReventlessInfra.commandSchema))
        });
      case "DeleteDisconnectSchedule" :
        return await deleteSchedule(directive._0);
      case "DoConnectPlugin" :
      case "DoDisconnectPlugin" :
        break;
      case "ForwardCommand" :
        let match = directive._0;
        return await forwardCommand(match.id, match.command, match.extensionPointName, queryEngine);
    }
    let fn = Spec.updateApiSchema;
    if (fn !== undefined) {
      return await fn(queryEngine);
    }
  };
  let mapIncomingCommand = (id, cmd, _meta) => {
    if (typeof cmd !== "object") {
      return [
        {
          TAG: "PublishCommand",
          _0: id,
          _1: "Disconnect"
        },
        {
          TAG: "Call",
          _0: callHandler,
          _1: {
            TAG: "DeleteDisconnectSchedule",
            _0: id
          }
        }
      ];
    }
    switch (cmd.TAG) {
      case "Heartbeat" :
        return [
          {
            TAG: "PublishCommand",
            _0: id,
            _1: "Heartbeat"
          },
          {
            TAG: "Call",
            _0: callHandler,
            _1: {
              TAG: "CreateDisconnectSchedule",
              _0: id,
              _1: cmd._0 + 2 | 0
            }
          }
        ];
      case "ConnectPlugin" :
        let pluginDefinition = cmd._0;
        let protocolErrors = pluginDefinition.extensionProtocols.flatMap(proto => Compat$ReventlessInterop.validateProtocol(CompatMatrix$ReventlessInterop.corePlugin, proto.extensionPointName, proto.commandVersion, proto.eventVersion));
        let reportAction = protocolErrors.length !== 0 ? (Effect.runSync(Effect.logWarning(`[Core.Plugin] Protocol version mismatch for plugin ` + pluginDefinition.id + `: ` + Stdlib_Option.getOr(JSON.stringify(protocolErrors), "[]"))), [{
              TAG: "PublishCommand",
              _0: id,
              _1: {
                TAG: "ReportIncompatibility",
                _0: pluginDefinition
              }
            }]) : [];
        return [{
            TAG: "PublishCommand",
            _0: id,
            _1: {
              TAG: "Connect",
              _0: pluginDefinition
            }
          }].concat(reportAction);
      case "ForwardCommand" :
        return [{
            TAG: "Call",
            _0: callHandler,
            _1: {
              TAG: "ForwardCommand",
              _0: cmd._0
            }
          }];
    }
  };
  let mapOutgoingEvent = (id, event, _meta, _queryEngine) => {
    if (typeof event !== "object") {
      return [{
          TAG: "PublishEvent",
          _0: id,
          _1: "UnknownPluginDetected"
        }];
    }
    switch (event.TAG) {
      case "Connected" :
        let pluginDefinition = event._0;
        return [
          {
            TAG: "PublishEvent",
            _0: id,
            _1: {
              TAG: "PluginConnected",
              _0: pluginDefinition
            }
          },
          {
            TAG: "Call",
            _0: callHandler,
            _1: {
              TAG: "DoConnectPlugin",
              _0: pluginDefinition
            }
          }
        ];
      case "Reconnected" :
        let pluginDefinition$1 = event._0;
        return [
          {
            TAG: "PublishEvent",
            _0: id,
            _1: {
              TAG: "PluginReconnected",
              _0: pluginDefinition$1
            }
          },
          {
            TAG: "Call",
            _0: callHandler,
            _1: {
              TAG: "DoConnectPlugin",
              _0: pluginDefinition$1
            }
          }
        ];
      case "Disconnected" :
        let pluginDefinition$2 = event._0;
        return [
          {
            TAG: "PublishEvent",
            _0: id,
            _1: {
              TAG: "PluginDisconnected",
              _0: pluginDefinition$2
            }
          },
          {
            TAG: "Call",
            _0: callHandler,
            _1: {
              TAG: "DoDisconnectPlugin",
              _0: pluginDefinition$2
            }
          }
        ];
      case "Activated" :
        return [{
            TAG: "PublishEvent",
            _0: id,
            _1: {
              TAG: "PluginActivated",
              _0: event._0
            }
          }];
      case "Deactivated" :
        let pluginDefinition$3 = event._0;
        return [
          {
            TAG: "PublishEvent",
            _0: id,
            _1: {
              TAG: "PluginDeactivated",
              _0: pluginDefinition$3
            }
          },
          {
            TAG: "Call",
            _0: callHandler,
            _1: {
              TAG: "DoDisconnectPlugin",
              _0: pluginDefinition$3
            }
          }
        ];
      case "IncompatiblePluginDetected" :
        return [{
            TAG: "PublishEvent",
            _0: id,
            _1: {
              TAG: "IncompatiblePlugin",
              _0: event._0
            }
          }];
    }
  };
  let PluginMapping = {
    Delegate: undefined,
    mapIncomingCommand: mapIncomingCommand,
    mapOutgoingEvent: mapOutgoingEvent
  };
  let Mapping = ExtensionPointMapping$ReventlessInfra.Make({
    name: PluginExtensionPointSpec$ReventlessInfra.name,
    moduleUrl: PluginExtensionPointSpec$ReventlessInfra.moduleUrl,
    commandSchema: PluginExtensionPointSpec$ReventlessInfra.commandSchema,
    eventSchema: PluginExtensionPointSpec$ReventlessInfra.eventSchema,
    directiveSchema: PluginExtensionPointSpec$ReventlessInfra.directiveSchema
  })({
    Delegate: {
      Id: Id$Reventless.$$String,
      name: PluginSpec$ReventlessCore.name,
      eventSchema: PluginSpec$ReventlessCore.eventSchema,
      errorSchema: PluginSpec$ReventlessCore.errorSchema,
      commandSchema: PluginSpec$ReventlessCore.commandSchema,
      moduleUrl: PluginSpec$ReventlessCore.moduleUrl
    },
    mapIncomingCommand: mapIncomingCommand,
    mapOutgoingEvent: mapOutgoingEvent
  });
  return {
    forwardCommand: forwardCommand,
    callHandler: callHandler,
    PluginMapping: PluginMapping,
    Mapping: Mapping
  };
}

let PluginExtensionPointSpec;

export {
  PluginExtensionPointSpec,
  Make,
}
/* S Not a pure module */
