// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";

let consumedEventSchema = Sury.union([
  Sury.literal("ProductAdded"),
  Sury.literal("ProductArchived"),
  Sury.literal("ProductUnarchived"),
  Sury.literal("ProductDiscontinued")
]);

let commandSchema = Sury.$schema(s => ({
  TAG: "ArchiveProduct",
  productId: s.m(DcbTag$Reventless.string)
}));

let errorSchema = Sury.union([
  Sury.literal("ProductNotFound"),
  Sury.literal("ProductIsDiscontinued")
]);

let eventSchema = Sury.$schema(s => ({
  TAG: "ProductArchived",
  productId: s.m(DcbTag$Reventless.string)
}));

function commandTransition(command) {
  return {
    TAG: "Moves",
    _0: ["Listed"],
    _1: "Archived"
  };
}

function commandAuthorization(command) {
  return {
    TAG: "AllowGroups",
    _0: [
      "Admin",
      "Merchandiser"
    ]
  };
}

let traits = [];

let name = "ArchiveProduct";

let Id;

let moduleUrl = "@reventlessdev/online-shop-hybrid-catalog/src/Product/StateChangeSlice/ArchiveProduct.res.mjs";

let readConsistency = "EscalateOnRetry";

export {
  name,
  Id,
  consumedEventSchema,
  commandSchema,
  errorSchema,
  eventSchema,
  commandTransition,
  moduleUrl,
  commandAuthorization,
  readConsistency,
  traits,
}
/* consumedEventSchema Not a pure module */
