// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Component$Reventless = require("../../components/Component.res.js");
var ComponentType$Reventless = require("../../ComponentType.res.js");
var EventCollector$Reventless = require("../../components/EventCollector/EventCollector.res.js");

function Make(RuntimeEnvironment, EventCollectorChannel) {
  var forEventCollector = function (handler, memorySizeOpt, timeoutOpt, eventCollector) {
    var memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 1024;
    var timeout = timeoutOpt !== undefined ? timeoutOpt : 30;
    var resource = Component$Reventless.toPulumiResource(eventCollector);
    return RuntimeEnvironment.make(ComponentType$Reventless.nameOpt(resource.__name, EventCollector$Reventless.componentType), handler, memorySize, timeout, {
                parent: resource
              });
  };
  return {
          EventCollectorChannel: EventCollectorChannel,
          forEventCollector: forEventCollector
        };
}

exports.Make = Make;
/* Component-Reventless Not a pure module */
