// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as ClientSqs from "@aws-sdk/client-sqs";
import * as NodeHttpHandler from "@smithy/node-http-handler";

let Raw = {};

let clientInstance = {
  contents: undefined
};

function client() {
  let client$1 = clientInstance.contents;
  if (client$1 !== undefined) {
    return Primitive_option.valFromOption(client$1);
  }
  let client$2 = new ClientSqs.SQSClient({
    maxAttempts: 5,
    requestHandler: Primitive_option.some(new NodeHttpHandler.NodeHttpHandler({
      connectionTimeout: 1000,
      requestTimeout: 5000
    }))
  });
  clientInstance.contents = Primitive_option.some(client$2);
  return client$2;
}

let Raw$1 = {};

function send(command) {
  return client().send(command);
}

let SendMessageCommand = {
  Raw: Raw$1,
  send: send
};

let BatchResultErrorEntry = {};

let Raw$2 = {};

function send$1(command) {
  return client().send(command);
}

let SendMessageBatchCommand = {
  Raw: Raw$2,
  send: send$1
};

let Raw$3 = {};

function send$2(command) {
  return client().send(command);
}

let DeleteMessageCommand = {
  Raw: Raw$3,
  send: send$2
};

let Raw$4 = {};

function send$3(command) {
  return client().send(command);
}

let DeleteMessageBatchCommand = {
  Raw: Raw$4,
  send: send$3
};

let Raw$5 = {};

function send$4(command) {
  return client().send(command);
}

let AddPermissionCommand = {
  Raw: Raw$5,
  send: send$4
};

let Raw$6 = {};

function send$5(command) {
  return client().send(command);
}

let GetQueueAttributesCommand = {
  Raw: Raw$6,
  send: send$5
};

let Raw$7 = {};

function send$6(command) {
  return client().send(command);
}

let SetQueueAttributesCommand = {
  Raw: Raw$7,
  send: send$6
};

export {
  Raw,
  clientInstance,
  client,
  SendMessageCommand,
  BatchResultErrorEntry,
  SendMessageBatchCommand,
  DeleteMessageCommand,
  DeleteMessageBatchCommand,
  AddPermissionCommand,
  GetQueueAttributesCommand,
  SetQueueAttributesCommand,
}
/* @aws-sdk/client-sqs Not a pure module */
