// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as LocalBus$ReventlessLocal from "../../../src/adapter/LocalBus.res.mjs";
import * as TestRunner$ReventlessLocal from "../../../src/test/TestRunner.res.mjs";
import * as TestFixtures$ReventlessLocal from "../../TestFixtures.res.mjs";
import * as ExtensionPointMapping$ReventlessInfra from "@reventlessdev/reventless-infra/src/types/ExtensionPointMapping.res.mjs";
import * as ExtensionPoint_Builder$ReventlessLocal from "../../../src/components/ExtensionPoint_Builder.res.mjs";

S.enableJson();

let Bus = LocalBus$ReventlessLocal.Make({});

TestRunner$ReventlessLocal.setup();

let name = "TestEP";

let commandSchema = S.schema(s => ({
  TAG: "Forward",
  targetId: s.m(S.string)
}));

let eventSchema = S.literal("TEPNoEvent");

let directiveSchema = S.literal("TEPNoDirective");

let moduleUrl = import.meta.url;

function commandAuthorization(param) {
  return "AllowAuthenticated";
}

let TestEPSpec = {
  name: name,
  commandSchema: commandSchema,
  eventSchema: eventSchema,
  directiveSchema: directiveSchema,
  moduleUrl: moduleUrl,
  commandAuthorization: commandAuthorization
};

let name$1 = "TargetAgg";

let commandSchema$1 = S.schema(s => ({
  TAG: "Execute",
  targetId: s.m(S.string)
}));

let eventSchema$1 = S.schema(s => ({
  TAG: "Executed",
  targetId: s.m(S.string)
}));

let errorSchema = S.literal("TEAggNoError");

let moduleUrl$1 = import.meta.url;

function commandAuthorization$1(param) {
  return "AllowAuthenticated";
}

let DelegateAggSpec = {
  Id: undefined,
  name: name$1,
  commandSchema: commandSchema$1,
  eventSchema: eventSchema$1,
  errorSchema: errorSchema,
  moduleUrl: moduleUrl$1,
  commandAuthorization: commandAuthorization$1
};

let moduleUrl$2 = "test:ExtensionPointFixtures:ForwardMapping";

function mapIncomingCommand(_id, cmd, _meta) {
  let targetId = cmd.targetId;
  let execCmd = {
    TAG: "Execute",
    targetId: targetId
  };
  return [{
      TAG: "PublishCommand",
      _0: targetId,
      _1: execCmd
    }];
}

let ForwardMapping = {
  ExtensionPoint: undefined,
  Delegate: undefined,
  moduleUrl: moduleUrl$2,
  mapIncomingCommand: mapIncomingCommand,
  mapOutgoingEvent: undefined
};

let TestEPMapping1 = ExtensionPointMapping$ReventlessInfra.Make({
  ExtensionPoint: {
    name: name,
    moduleUrl: moduleUrl,
    commandSchema: commandSchema,
    eventSchema: eventSchema,
    directiveSchema: directiveSchema
  },
  Delegate: {
    Id: {
      schema: Id$Reventless.StringPure.schema,
      make: prim => prim,
      makeFromString: prim => prim,
      toString: prim => prim,
      cmp: Id$Reventless.StringPure.cmp
    },
    name: name$1,
    eventSchema: eventSchema$1,
    errorSchema: errorSchema,
    commandSchema: commandSchema$1,
    moduleUrl: moduleUrl$1,
    commandAuthorization: commandAuthorization$1
  },
  moduleUrl: moduleUrl$2,
  mapIncomingCommand: mapIncomingCommand,
  mapOutgoingEvent: undefined
});

let name$2 = "TestEPMappings";

let moduleUrl$3 = import.meta.url;

let mappings = [TestEPMapping1];

let TestEPMappings = {
  Spec: undefined,
  name: name$2,
  moduleUrl: moduleUrl$3,
  mappings: mappings
};

let EPBuilderWithBus = ExtensionPoint_Builder$ReventlessLocal.Make(Bus);

let TestEP = EPBuilderWithBus.Make({
  name: name,
  moduleUrl: moduleUrl,
  commandSchema: commandSchema,
  eventSchema: eventSchema,
  directiveSchema: directiveSchema
})({
  name: name$2,
  moduleUrl: moduleUrl$3,
  mappings: mappings
});

let capturedCmds = {
  contents: []
};

async function mockPublishFn(cmds) {
  capturedCmds.contents = capturedCmds.contents.concat(cmds);
}

let ep = TestEP.make(Object.fromEntries([[
    "TargetAgg",
    []
  ]]), Object.fromEntries([[
    "TargetAgg",
    mockPublishFn
  ]]), TestFixtures$ReventlessLocal.mockScheduler, TestFixtures$ReventlessLocal.mockQueryEngine, TestFixtures$ReventlessLocal.mockResourceNaming, undefined);

let testMeta = TestFixtures$ReventlessLocal.makeTestMeta("TestEP");

function resetMocks() {
  capturedCmds.contents = [];
}

export {
  Bus,
  TestEPSpec,
  DelegateAggSpec,
  ForwardMapping,
  TestEPMapping1,
  TestEPMappings,
  EPBuilderWithBus,
  TestEP,
  capturedCmds,
  mockPublishFn,
  ep,
  testMeta,
  resetMocks,
}
/*  Not a pure module */
