// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Component = require("./Component");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Message$Reventless = require("../Message.bs.js");
var Util_Decco$Reventless = require("../util/Util_Decco.bs.js");
var ComponentType$Reventless = require("../ComponentType.bs.js");

var NotPublishedToPublisher = Caml_exceptions.create("EventTopic-Reventless.NotPublishedToPublisher");

var Adapter = { };

function Make(Spec, Publisher) {
  var publishFn = function (publisher, name) {
    return (function (events$prime) {
        var eventCount = events$prime.length;
        var __x = Promise.all(Belt_Array.mapWithIndex(events$prime, (function (idx, event$prime) {
                    var json = Message$Reventless.event$prime_encode(Spec.Id.t_encode, Spec.event_encode, event$prime);
                    var id = event$prime.id;
                    var eventName = Belt_Option.getWithDefault(Util_Decco$Reventless.Json.variantName(Curry._1(Spec.event_encode, event$prime.event)), "Could not get event-name!");
                    var idx$1 = idx + 1 | 0;
                    var __x = publisher.publish(Curry._1(Spec.Id.toString, id), event$prime.meta, json);
                    var __x$1 = __x.catch((function (e) {
                            console.log("EventTopic: Couldn\'t publish event " + (String(idx$1) + ("/" + (String(eventCount) + (": " + (String(eventName) + ("(" + (String(id) + (") to " + (String(name) + ""))))))))));
                            return Promise.reject([
                                        NotPublishedToPublisher,
                                        e
                                      ]);
                          }));
                    return __x$1.then((function (param) {
                                  var $$event = JSON.stringify(json);
                                  return Promise.resolve((console.log("EventTopic: Published event " + (String(idx$1) + ("/" + (String(eventCount) + (": " + (String(eventName) + ("(" + (String(id) + (") to " + (String(name) + (": " + (String($$event) + "")))))))))))), undefined));
                                }));
                  })));
        return __x.then((function (param) {
                      return Promise.resolve(undefined);
                    }));
      });
  };
  var construct = function (storageResources, self, name) {
    var opts = {
      parent: self
    };
    var publisher = Curry._3(Publisher.make, ComponentType$Reventless.name(name, /* EventTopic */8), storageResources, opts);
    self.publish = publishFn(publisher, name);
    var outputs = {
      resources: publisher.resources
    };
    self.setOutputs(outputs);
    return self.registerOutputs(outputs);
  };
  var make = function (name, storageResources, opts, param) {
    var prim = ComponentType$Reventless.toString(/* EventTopic */8);
    var prim$1 = function (param, param$1) {
      return construct(storageResources, param, param$1);
    };
    return new Component.default(prim, name, prim$1, opts);
  };
  return {
          Spec: Spec,
          make: make,
          publish: (function (prim) {
              return prim.publish;
            })
        };
}

var componentType = /* EventTopic */8;

exports.componentType = componentType;
exports.NotPublishedToPublisher = NotPublishedToPublisher;
exports.Adapter = Adapter;
exports.Make = Make;
/* ./Component Not a pure module */
