// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Decco = require("decco/src/Decco.bs.js");
var Js_json = require("rescript/lib/js/js_json.js");
var Belt_List = require("rescript/lib/js/belt_List.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Component = require("./Component").default;
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Component$Reventless = require("./Component.bs.js");
var ComponentType$Reventless = require("../ComponentType.bs.js");

function storageError_encode(v) {
  if (typeof v === "number") {
    if (v === /* StaleState */0) {
      return ["StaleState"];
    } else {
      return ["MissingSubIdConfig"];
    }
  }
  switch (v.TAG | 0) {
    case /* NotSavedToStorage */0 :
        return [
                "NotSavedToStorage",
                Decco.stringToJson(v._0)
              ];
    case /* NotLoadedFromStorage */1 :
        return [
                "NotLoadedFromStorage",
                Decco.stringToJson(v._0)
              ];
    case /* NotCountedOnStorage */2 :
        return [
                "NotCountedOnStorage",
                Decco.stringToJson(v._0)
              ];
    case /* NotDeletedFromStorage */3 :
        return [
                "NotDeletedFromStorage",
                Decco.stringToJson(v._0)
              ];
    case /* BatchNotFullyWrittenToStorage */4 :
        return [
                "BatchNotFullyWrittenToStorage",
                Decco.stringToJson(v._0)
              ];
    
  }
}

function storageError_decode(v) {
  var jsonArr = Js_json.classify(v);
  if (typeof jsonArr === "number") {
    return Decco.error(undefined, "Not a variant", v);
  }
  if (jsonArr.TAG !== /* JSONArray */3) {
    return Decco.error(undefined, "Not a variant", v);
  }
  var jsonArr$1 = jsonArr._0;
  if (jsonArr$1.length === 0) {
    return Decco.error(undefined, "Expected variant, found empty array", v);
  }
  var tagged = jsonArr$1.map(Js_json.classify);
  var match = Belt_Array.getExn(tagged, 0);
  if (typeof match !== "number" && match.TAG === /* JSONString */0) {
    switch (match._0) {
      case "BatchNotFullyWrittenToStorage" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0 = Decco.stringFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0.TAG === /* Ok */0) {
            return {
                    TAG: /* Ok */0,
                    _0: {
                      TAG: /* BatchNotFullyWrittenToStorage */4,
                      _0: v0._0
                    }
                  };
          }
          var e = v0._0;
          return {
                  TAG: /* Error */1,
                  _0: {
                    path: "[0]" + e.path,
                    message: e.message,
                    value: e.value
                  }
                };
      case "MissingSubIdConfig" :
          if (tagged.length !== 1) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
                    TAG: /* Ok */0,
                    _0: /* MissingSubIdConfig */1
                  };
          }
      case "NotCountedOnStorage" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0$1 = Decco.stringFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0$1.TAG === /* Ok */0) {
            return {
                    TAG: /* Ok */0,
                    _0: {
                      TAG: /* NotCountedOnStorage */2,
                      _0: v0$1._0
                    }
                  };
          }
          var e$1 = v0$1._0;
          return {
                  TAG: /* Error */1,
                  _0: {
                    path: "[0]" + e$1.path,
                    message: e$1.message,
                    value: e$1.value
                  }
                };
      case "NotDeletedFromStorage" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0$2 = Decco.stringFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0$2.TAG === /* Ok */0) {
            return {
                    TAG: /* Ok */0,
                    _0: {
                      TAG: /* NotDeletedFromStorage */3,
                      _0: v0$2._0
                    }
                  };
          }
          var e$2 = v0$2._0;
          return {
                  TAG: /* Error */1,
                  _0: {
                    path: "[0]" + e$2.path,
                    message: e$2.message,
                    value: e$2.value
                  }
                };
      case "NotLoadedFromStorage" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0$3 = Decco.stringFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0$3.TAG === /* Ok */0) {
            return {
                    TAG: /* Ok */0,
                    _0: {
                      TAG: /* NotLoadedFromStorage */1,
                      _0: v0$3._0
                    }
                  };
          }
          var e$3 = v0$3._0;
          return {
                  TAG: /* Error */1,
                  _0: {
                    path: "[0]" + e$3.path,
                    message: e$3.message,
                    value: e$3.value
                  }
                };
      case "NotSavedToStorage" :
          if (tagged.length !== 2) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          }
          var v0$4 = Decco.stringFromJson(Belt_Array.getExn(jsonArr$1, 1));
          if (v0$4.TAG === /* Ok */0) {
            return {
                    TAG: /* Ok */0,
                    _0: {
                      TAG: /* NotSavedToStorage */0,
                      _0: v0$4._0
                    }
                  };
          }
          var e$4 = v0$4._0;
          return {
                  TAG: /* Error */1,
                  _0: {
                    path: "[0]" + e$4.path,
                    message: e$4.message,
                    value: e$4.value
                  }
                };
      case "StaleState" :
          if (tagged.length !== 1) {
            return Decco.error(undefined, "Invalid number of arguments to variant constructor", v);
          } else {
            return {
                    TAG: /* Ok */0,
                    _0: /* StaleState */0
                  };
          }
      default:
        
    }
  }
  return Decco.error(undefined, "Invalid variant constructor", Belt_Array.getExn(jsonArr$1, 0));
}

function NoResolvers(Config) {
  var make = function (param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8) {
    return {
            resources: [],
            resourcesMaker: (function (param) {
                return [];
              })
          };
  };
  return {
          make: make
        };
}

var Adapter = {
  NoResolvers: NoResolvers
};

function Make(Config, Spec, $$Storage, Resolvers) {
  var loadFn = function (storage) {
    return function (id) {
      return storage.load(Curry._1(Spec.Id.toString, id)).then(function (result) {
                  return Promise.resolve(Belt_Result.map(result, (function (states) {
                                    return Belt_List.flatten(Belt_List.map(states, (function (param) {
                                                      var state = Curry._1(Spec.state_decode, param);
                                                      if (state.TAG === /* Ok */0) {
                                                        return {
                                                                hd: state._0,
                                                                tl: /* [] */0
                                                              };
                                                      }
                                                      console.log("QueryDb: Error: Couldn't decode state for " + id + ": " + state._0);
                                                      return /* [] */0;
                                                    })));
                                  })));
                });
    };
  };
  var saveFn = function (storage) {
    return function (id, state, saveMode, ttl) {
      var dict = Js_json.decodeObject(Curry._1(Spec.state_encode, state));
      if (dict !== undefined) {
        var dict$1 = Caml_option.valFromOption(dict);
        dict$1["id"] = Curry._1(Spec.Id.t_encode, id);
        return storage.save(Curry._1(Spec.Id.toString, id), dict$1, saveMode, ttl);
      }
      console.log("QueryDB.save: Error: Couldn't decodeObject:", JSON.stringify(state));
      return Promise.resolve({
                  TAG: /* Error */1,
                  _0: {
                    TAG: /* NotSavedToStorage */0,
                    _0: "Couldn't decodeObject"
                  }
                });
    };
  };
  var saveBatchFn = function (storage) {
    return function (items) {
      var batch = Belt_Array.keepMap(items, (function (param) {
              var state = param[1];
              var id = param[0];
              var dict = Js_json.decodeObject(Curry._1(Spec.state_encode, state));
              if (dict !== undefined) {
                var dict$1 = Caml_option.valFromOption(dict);
                dict$1["id"] = Curry._1(Spec.Id.t_encode, id);
                return [
                        Curry._1(Spec.Id.toString, id),
                        dict$1,
                        param[2]
                      ];
              }
              console.log("QueryDB.saveBatch: Error: Couldn't decodeObject:", JSON.stringify(state));
              
            }));
      return storage.saveBatch(batch);
    };
  };
  var countFn = function (storage) {
    return function (id, fieldName, inc) {
      return storage.count(Curry._1(Spec.Id.toString, id), fieldName, inc);
    };
  };
  var deleteFn = function (storage) {
    return function (id, subId) {
      return storage.delete(Curry._1(Spec.Id.toString, id), subId);
    };
  };
  var outputs = Component$Reventless.extractOutputs;
  var construct = function (ttl, self, name, api, apiRole) {
    var opts = {
      parent: self
    };
    var sortField = Belt_Option.map(Spec.subIdConfig, (function (config) {
            return config.subIdField;
          }));
    var storageName = ComponentType$Reventless.name(name, /* QueryDb */11);
    var storage = Curry._7($$Storage.make, storageName, Spec.indexes, sortField, ttl, api, apiRole, opts);
    self.load = loadFn(storage);
    self.save = saveFn(storage);
    self.saveBatch = saveBatchFn(storage);
    self.count = countFn(storage);
    self.delete = deleteFn(storage);
    var resolvers = Curry.app(Resolvers.make, [
          name,
          api,
          apiRole,
          storage.dataSourceName,
          Spec.indexes,
          sortField,
          Spec.resolveIdConfigs,
          Spec.resolveIdsConfigs,
          opts
        ]);
    var outputs = {
      resources: Belt_Array.concat(storage.resources, resolvers.resources),
      resolversMaker: resolvers.resourcesMaker
    };
    self.setOutputs(outputs);
    return self.registerOutputs(outputs);
  };
  var make = function (ttl, opts, param) {
    var prim0 = ComponentType$Reventless.toString(/* QueryDb */11);
    var prim1 = Spec.name;
    var prim2 = function (param, param$1, param$2, param$3) {
      return construct(ttl, param, param$1, param$2, param$3);
    };
    var prim4 = Config.api;
    var prim5 = Config.apiRole;
    return new Component(prim0, prim1, prim2, opts, prim4, prim5);
  };
  return {
          Spec: Spec,
          make: make,
          load: (function (prim) {
              return prim.load;
            }),
          save: (function (prim) {
              return prim.save;
            }),
          saveBatch: (function (prim) {
              return prim.saveBatch;
            }),
          count: (function (prim) {
              return prim.count;
            }),
          $$delete: (function (prim) {
              return prim.delete;
            }),
          deleteBatch: (function (prim) {
              return prim.deleteBatch;
            }),
          outputs: outputs
        };
}

var componentType = /* QueryDb */11;

exports.componentType = componentType;
exports.storageError_encode = storageError_encode;
exports.storageError_decode = storageError_decode;
exports.Adapter = Adapter;
exports.Make = Make;
/* ./Component Not a pure module */
