// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Component = require("./Component").default;
var ComponentType$Reventless = require("../ComponentType.bs.js");

var Adapter = {
  publisher: "Publisher"
};

function Make(ScheduledPublisher) {
  var construct = function (self, name) {
    var opts = {
      parent: self
    };
    var scheduledPublisher = Curry._2(ScheduledPublisher.make, name, opts);
    self.createSchedule = scheduledPublisher.create;
    self.deleteSchedule = scheduledPublisher.delete;
    var outputs = {
      scheduledPublisher: scheduledPublisher.resource
    };
    self.setOutputs(outputs);
    return self.registerOutputs(outputs);
  };
  var make = function (opts, param) {
    var prim0 = ComponentType$Reventless.toString(/* Scheduler */13);
    var prim1 = ComponentType$Reventless.toName(/* Scheduler */13);
    return new Component(prim0, prim1, construct, opts);
  };
  return {
          make: make
        };
}

var componentType = /* Scheduler */13;

exports.componentType = componentType;
exports.Adapter = Adapter;
exports.Make = Make;
/* ./Component Not a pure module */
