// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var Belt_Option = require("@rescript/std/lib/js/belt_Option.js");
var Caml_option = require("@rescript/std/lib/js/caml_option.js");
var Pulumi = require("@pulumi/pulumi");
var Belt_SetString = require("@rescript/std/lib/js/belt_SetString.js");
var Adapter$Reventless = require("../adapter/Adapter.res.js");
var Schedule$Reventless = require("../util/Schedule.res.js");
var Component$Reventless = require("./Component.res.js");
var Util_Pulumi$Reventless = require("../util/Util_Pulumi.res.js");
var ComponentType$Reventless = require("../ComponentType.res.js");
var Util_EventTopic$Reventless = require("../util/Util_EventTopic.res.js");
var SideEffectHandler_Runtime$Reventless = require("./SideEffectHandler_Runtime.res.js");

function Make(SpecificEventCollector) {
  var make = function (name, sideEffects, allEventTopics, queryEngine, scheduler, memorySizeOpt, timeoutOpt, policy1, policy2, opts) {
    var memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 2048;
    var timeout = timeoutOpt !== undefined ? timeoutOpt : 180;
    return Component$Reventless.make(ComponentType$Reventless.toString("SideEffectHandler"), name, (function (extra, extra$1) {
                  var opts_parent = Caml_option.some(Component$Reventless.toPulumiResource(extra));
                  var opts = {
                    parent: opts_parent
                  };
                  var aggregateNames = Belt_SetString.fromArray(Belt_Array.map(sideEffects, (function (SideEffect) {
                              return SideEffect.Source.name;
                            })));
                  var eventCollector = SpecificEventCollector.make(extra$1, Util_EventTopic$Reventless.filterEventTopics(allEventTopics, aggregateNames), (function (extra) {
                          return SideEffectHandler_Runtime$Reventless.eventsHandler(sideEffects, queryEngine, extra);
                        }), memorySize, timeout, policy1, policy2, opts);
                  var eventCollectorResources = Adapter$Reventless.resourcesToUnwrappedOutput(Component$Reventless.extractOutputs(eventCollector).resources);
                  Component$Reventless.setOperations(extra, Pulumi.all([
                              Component$Reventless.operations(eventCollector),
                              eventCollectorResources
                            ]).apply(function (param) {
                            var eventCollectorResources = param[1];
                            return {
                                    enqueueEvent: param[0].enqueueEvent,
                                    createSchedule: Schedule$Reventless.create(scheduler, eventCollectorResources),
                                    deleteSchedule: Schedule$Reventless.$$delete(scheduler, eventCollectorResources)
                                  };
                          }));
                  return Component$Reventless.setOutputs(extra, {
                              name: extra$1,
                              eventCollector: Component$Reventless.extractOutputs(eventCollector)
                            });
                }), Belt_Option.map(opts, Util_Pulumi$Reventless.ComponentResourceOptions.ofCustomResourceOptions));
  };
  return {
          make: make
        };
}

var ReventlessEventCollector;

var componentType = "SideEffectHandler";

exports.ReventlessEventCollector = ReventlessEventCollector;
exports.componentType = componentType;
exports.Make = Make;
/* @pulumi/pulumi Not a pure module */
