// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Id$Reventless = require("../../src/Id.bs.js");
var ViewTest$Reventless = require("../../test-helper/ViewTest.bs.js");
var PluginSpec$Reventless = require("../../src/core/plugin/PluginSpec.bs.js");
var PluginView$Reventless = require("../../src/core/plugin/PluginView.bs.js");
var PluginFixture$Reventless = require("./PluginFixture.bs.js");

var PluginTest = ViewTest$Reventless.Make({
        Id: Id$Reventless.$$String,
        name: PluginSpec$Reventless.name,
        event_encode: PluginSpec$Reventless.event_encode,
        event_decode: PluginSpec$Reventless.event_decode
      })({
      name: PluginView$Reventless.name,
      state_encode: PluginView$Reventless.state_encode,
      state_decode: PluginView$Reventless.state_decode,
      resolveIdConfigs: PluginView$Reventless.resolveIdConfigs,
      resolveIdsConfigs: PluginView$Reventless.resolveIdsConfigs,
      sortConfig: PluginView$Reventless.sortConfig,
      indexes: PluginView$Reventless.indexes,
      init: PluginView$Reventless.init,
      apply: PluginView$Reventless.apply,
      applyMulti: PluginView$Reventless.applyMulti
    });

Jest.describe("Plugin: View", (function (param) {
        Jest.test("UnknownPluginDetected", (function (param) {
                return Curry._1(PluginTest.thenNoState, Curry._2(PluginTest.whenEvent, /* UnknownPluginDetected */0, Curry._1(PluginTest.givenEvents, /* [] */0)));
              }));
        Jest.test("UnknownPluginDetected (already detected)", (function (param) {
                return Curry._1(PluginTest.thenNoState, Curry._2(PluginTest.whenEvent, /* UnknownPluginDetected */0, Curry._1(PluginTest.givenEvents, /* :: */[
                                    /* UnknownPluginDetected */0,
                                    /* [] */0
                                  ])));
              }));
        Jest.test("PluginConnected", (function (param) {
                return Curry._2(PluginTest.thenState, /* record */[
                            /* name */PluginFixture$Reventless.state[/* name */0],
                            /* version */PluginFixture$Reventless.state[/* version */1],
                            /* eventCollector */PluginFixture$Reventless.state[/* eventCollector */2],
                            /* extensionPoints */PluginFixture$Reventless.state[/* extensionPoints */3],
                            /* extensionPointNames */PluginFixture$Reventless.state[/* extensionPointNames */4],
                            /* extensionNames */PluginFixture$Reventless.state[/* extensionNames */5],
                            /* extensions */PluginFixture$Reventless.state[/* extensions */6],
                            /* status : Connected */0,
                            /* statusChange */PluginFixture$Reventless.state[/* statusChange */8]
                          ], Curry._2(PluginTest.whenEvent, /* PluginConnected */Block.__(0, [PluginFixture$Reventless.pluginDefinition]), Curry._1(PluginTest.givenEvents, /* :: */[
                                    /* UnknownPluginDetected */0,
                                    /* [] */0
                                  ])));
              }));
        Jest.test("PluginDisconnected", (function (param) {
                return Curry._2(PluginTest.thenState, /* record */[
                            /* name */PluginFixture$Reventless.state[/* name */0],
                            /* version */PluginFixture$Reventless.state[/* version */1],
                            /* eventCollector */PluginFixture$Reventless.state[/* eventCollector */2],
                            /* extensionPoints */PluginFixture$Reventless.state[/* extensionPoints */3],
                            /* extensionPointNames */PluginFixture$Reventless.state[/* extensionPointNames */4],
                            /* extensionNames */PluginFixture$Reventless.state[/* extensionNames */5],
                            /* extensions */PluginFixture$Reventless.state[/* extensions */6],
                            /* status : Disconnected */1,
                            /* statusChange */PluginFixture$Reventless.state[/* statusChange */8]
                          ], Curry._2(PluginTest.whenEvent, /* PluginDisconnected */Block.__(2, [PluginFixture$Reventless.pluginDefinition]), Curry._1(PluginTest.givenEvents, /* :: */[
                                    /* UnknownPluginDetected */0,
                                    /* :: */[
                                      /* PluginConnected */Block.__(0, [PluginFixture$Reventless.pluginDefinition]),
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("PluginDeactivated", (function (param) {
                return Curry._2(PluginTest.thenState, /* record */[
                            /* name */PluginFixture$Reventless.state[/* name */0],
                            /* version */PluginFixture$Reventless.state[/* version */1],
                            /* eventCollector */PluginFixture$Reventless.state[/* eventCollector */2],
                            /* extensionPoints */PluginFixture$Reventless.state[/* extensionPoints */3],
                            /* extensionPointNames */PluginFixture$Reventless.state[/* extensionPointNames */4],
                            /* extensionNames */PluginFixture$Reventless.state[/* extensionNames */5],
                            /* extensions */PluginFixture$Reventless.state[/* extensions */6],
                            /* status : Inactive */2,
                            /* statusChange */PluginFixture$Reventless.state[/* statusChange */8]
                          ], Curry._2(PluginTest.whenEvent, /* PluginDeactivated */Block.__(4, [PluginFixture$Reventless.pluginDefinition]), Curry._1(PluginTest.givenEvents, /* :: */[
                                    /* UnknownPluginDetected */0,
                                    /* :: */[
                                      /* PluginConnected */Block.__(0, [PluginFixture$Reventless.pluginDefinition]),
                                      /* [] */0
                                    ]
                                  ])));
              }));
        Jest.test("PluginActivated", (function (param) {
                return Curry._2(PluginTest.thenState, /* record */[
                            /* name */PluginFixture$Reventless.state[/* name */0],
                            /* version */PluginFixture$Reventless.state[/* version */1],
                            /* eventCollector */PluginFixture$Reventless.state[/* eventCollector */2],
                            /* extensionPoints */PluginFixture$Reventless.state[/* extensionPoints */3],
                            /* extensionPointNames */PluginFixture$Reventless.state[/* extensionPointNames */4],
                            /* extensionNames */PluginFixture$Reventless.state[/* extensionNames */5],
                            /* extensions */PluginFixture$Reventless.state[/* extensions */6],
                            /* status : Disconnected */1,
                            /* statusChange */PluginFixture$Reventless.state[/* statusChange */8]
                          ], Curry._2(PluginTest.whenEvent, /* PluginActivated */Block.__(3, [PluginFixture$Reventless.pluginDefinition]), Curry._1(PluginTest.givenEvents, /* :: */[
                                    /* UnknownPluginDetected */0,
                                    /* :: */[
                                      /* PluginConnected */Block.__(0, [PluginFixture$Reventless.pluginDefinition]),
                                      /* :: */[
                                        /* PluginDeactivated */Block.__(4, [PluginFixture$Reventless.pluginDefinition]),
                                        /* [] */0
                                      ]
                                    ]
                                  ])));
              }));
        return Jest.test("PluginReconnected (after activated)", (function (param) {
                      return Curry._2(PluginTest.thenState, /* record */[
                                  /* name */PluginFixture$Reventless.state[/* name */0],
                                  /* version */PluginFixture$Reventless.state[/* version */1],
                                  /* eventCollector */PluginFixture$Reventless.state[/* eventCollector */2],
                                  /* extensionPoints */PluginFixture$Reventless.state[/* extensionPoints */3],
                                  /* extensionPointNames */PluginFixture$Reventless.state[/* extensionPointNames */4],
                                  /* extensionNames */PluginFixture$Reventless.state[/* extensionNames */5],
                                  /* extensions */PluginFixture$Reventless.state[/* extensions */6],
                                  /* status : Connected */0,
                                  /* statusChange */PluginFixture$Reventless.state[/* statusChange */8]
                                ], Curry._2(PluginTest.whenEvent, /* PluginReconnected */Block.__(1, [PluginFixture$Reventless.pluginDefinition]), Curry._1(PluginTest.givenEvents, /* :: */[
                                          /* UnknownPluginDetected */0,
                                          /* :: */[
                                            /* PluginConnected */Block.__(0, [PluginFixture$Reventless.pluginDefinition]),
                                            /* :: */[
                                              /* PluginDeactivated */Block.__(4, [PluginFixture$Reventless.pluginDefinition]),
                                              /* :: */[
                                                /* PluginActivated */Block.__(3, [PluginFixture$Reventless.pluginDefinition]),
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ])));
                    }));
      }));

exports.PluginTest = PluginTest;
/* PluginTest Not a pure module */
