// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var TestFixtures$Reventless = require("../../test-helper/TestFixtures.bs.js");
var PluginProjection$Reventless = require("../../src/core/ReadModels/Plugin/PluginProjection.bs.js");

var pluginDefinition_extensionPoints = [];

var pluginDefinition_extensions = [{
    name: "Core.Plugin.Test",
    extensionPointName: "Core.Plugin"
  }];

var pluginDefinition = {
  id: "id@1",
  name: "name",
  version: "1",
  extensionPoints: pluginDefinition_extensionPoints,
  extensions: pluginDefinition_extensions,
  eventCollector: "eventCollector"
};

var state_extensionPoints = pluginDefinition_extensionPoints;

var state_extensionPointNames = PluginProjection$Reventless.Util.extractExtensionPointNames(pluginDefinition_extensionPoints);

var state_extensionNames = PluginProjection$Reventless.Util.extractExtensionNames(pluginDefinition_extensions);

var state_extensions = pluginDefinition_extensions;

var state = {
  name: "name",
  version: "1",
  eventCollector: "eventCollector",
  extensionPoints: state_extensionPoints,
  extensionPointNames: state_extensionPointNames,
  extensionNames: state_extensionNames,
  extensions: state_extensions,
  status: /* Connected */0,
  statusChange: TestFixtures$Reventless.statusChange
};

var extensionPointNames2 = ["Test.Test"];

var pluginDefinition2_extensionPoints = Belt_Array.mapWithIndex(extensionPointNames2, (function (idx, name) {
        return {
                name: name,
                commandTopic: "commandTopic" + (String(idx) + ""),
                eventTopic: "eventTopic" + (String(idx) + "")
              };
      }));

var pluginDefinition2_extensions = [];

var pluginDefinition2 = {
  id: "id2@1",
  name: "name2",
  version: "1",
  extensionPoints: pluginDefinition2_extensionPoints,
  extensions: pluginDefinition2_extensions,
  eventCollector: "eventCollector"
};

exports.pluginDefinition = pluginDefinition;
exports.state = state;
exports.extensionPointNames2 = extensionPointNames2;
exports.pluginDefinition2 = pluginDefinition2;
/* state Not a pure module */
