// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Stream from "@reventlessdev/rescript-effect/src/Stream.res.mjs";
import * as Effect from "effect/Effect";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as ReadModel$Reventless from "@reventlessdev/reventless-spec/src/components/ReadModel.res.mjs";
import * as Message$ReventlessCore from "@reventlessdev/reventless-core/src/Message.res.mjs";
import * as Component$ReventlessCore from "@reventlessdev/reventless-core/src/components/Component.res.mjs";
import * as LocalBus$ReventlessLocal from "../../../src/adapter/LocalBus.res.mjs";
import * as TestRunner$ReventlessLocal from "../../../src/test/TestRunner.res.mjs";
import * as DcbEventLog_Builder$ReventlessLocal from "../../../src/components/DcbEventLog_Builder.res.mjs";
import * as StateViewSlice_Builder$ReventlessLocal from "../../../src/components/StateViewSlice_Builder.res.mjs";

let eventSchema = S.union([
  S.schema(s => ({
    TAG: "ScoreRecorded",
    id: s.m(DcbTag$Reventless.string),
    category: s.m(S.string),
    date: s.m(S.string),
    score: s.m(S.int)
  })),
  S.schema(s => ({
    TAG: "ScoreRemoved",
    id: s.m(DcbTag$Reventless.string),
    category: s.m(S.string),
    date: s.m(S.string)
  }))
]);

let ScoreEventLog = {
  eventSchema: eventSchema
};

let name = "ScoresView";

let moduleUrl = import.meta.url;

let consumedEventSchema = S.union([
  S.schema(s => ({
    TAG: "ScoreRecorded",
    id: s.m(S.string),
    category: s.m(S.string),
    date: s.m(S.string),
    score: s.m(S.int)
  })),
  S.schema(s => ({
    TAG: "ScoreRemoved",
    id: s.m(S.string),
    category: s.m(S.string),
    date: s.m(S.string)
  }))
]);

let stateSchema = S.schema(s => ({
  id: s.m(S.string),
  category: s.m(S.string),
  date: s.m(S.string),
  score: s.m(S.int)
}));

let config = ReadModel$Reventless.config(undefined, undefined, undefined);

let subIdConfig = {
  subIdField: "_subId",
  getSubId: state => state.category + "/" + state.date
};

let ScoresViewSpec = {
  name: name,
  moduleUrl: moduleUrl,
  consumedEventSchema: consumedEventSchema,
  stateSchema: stateSchema,
  config: config,
  subIdConfig: subIdConfig,
  authorization: "AllowAuthenticated",
  visibility: "Public"
};

let moduleUrl$1 = import.meta.url;

function project(param) {
  let event = param.event;
  if (event.TAG !== "ScoreRecorded") {
    return [{
        TAG: "Delete",
        _0: event.id
      }];
  }
  let id = event.id;
  return [{
      TAG: "Set",
      _0: id,
      _1: {
        id: id,
        category: event.category,
        date: event.date,
        score: event.score
      }
    }];
}

let ScoresViewProjection = {
  Spec: undefined,
  moduleUrl: moduleUrl$1,
  project: project
};

let Bus = LocalBus$ReventlessLocal.Make({});

TestRunner$ReventlessLocal.setup();

let ScoreEventLogMaker = DcbEventLog_Builder$ReventlessLocal.Make(Bus);

let eventLog = ScoreEventLogMaker.make("ScoreEventLog", undefined, {
  TAG: "Simple",
  _0: {
    key: "id"
  }
}, undefined);

let SVMaker = StateViewSlice_Builder$ReventlessLocal.Make(Bus);

let ScoresViewMaker = SVMaker.Make({
  name: name,
  moduleUrl: moduleUrl,
  stateSchema: stateSchema,
  consumedEventSchema: consumedEventSchema,
  config: config,
  subIdConfig: subIdConfig,
  authorization: "AllowAuthenticated",
  visibility: "Public"
})({
  project: project,
  moduleUrl: moduleUrl$1
});

let sv = ScoresViewMaker.make(eventLog, undefined, undefined);

let dcbEventTopicResource = Component$ReventlessCore.outputs(eventLog).eventTopic.resources[0];

function encodeEvent(event) {
  let json = S.reverseConvertToJsonOrThrow(event, eventSchema);
  let match = Message$ReventlessCore.splitMessage(json);
  let tags = DcbTag$Reventless.extractTags(eventSchema, event);
  let meta = Message$ReventlessCore.generateMeta("test", undefined, undefined, undefined, undefined, undefined, undefined, undefined);
  return {
    eventType: match[0],
    data: match[1],
    tags: tags,
    meta: meta
  };
}

async function appendEvent(event) {
  let ops = await TestRunner$ReventlessLocal.resolve(ScoreEventLogMaker.operations(eventLog));
  await ops.append([encodeEvent(event)], undefined);
}

async function loadScores(id) {
  let ops = Bus.getQueryDb("ScoresView");
  if (ops === undefined) {
    return [];
  }
  let states = await Effect.runPromise(Effect.catchAll(Stream.runCollect(ops.loadStream(id)), param => Effect.succeed([])));
  return states.map(json => S.parseJsonOrThrow(json, stateSchema));
}

export {
  ScoreEventLog,
  ScoresViewSpec,
  ScoresViewProjection,
  Bus,
  ScoreEventLogMaker,
  eventLog,
  SVMaker,
  ScoresViewMaker,
  sv,
  dcbEventTopicResource,
  encodeEvent,
  appendEvent,
  loadScores,
}
/* eventSchema Not a pure module */
