// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Aws from "@pulumi/aws";
import * as IAM$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/IAM/IAM.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Pulumi from "@pulumi/pulumi";
import * as Lambda$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/Lambda/Lambda.res.mjs";
import * as AWS$ReventlessAws from "../AWS.res.mjs";
import * as AWS_Tags$ReventlessAws from "../AWS_Tags.res.mjs";
import * as QueryDb$ReventlessCore from "@reventlessdev/reventless-core/src/components/QueryDb/QueryDb.res.mjs";
import * as PolicyDocument$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/IAM/PolicyDocument.res.mjs";
import * as Util_Bundle$ReventlessAws from "../../util/Util_Bundle.res.mjs";
import * as StateAnnotations$Reventless from "@reventlessdev/reventless-spec/src/components/StateAnnotations.res.mjs";
import * as Plugin_Helpers$ReventlessCore from "@reventlessdev/reventless-core/src/plugin/component/Plugin_Helpers.res.mjs";
import * as Util_ReadModel$ReventlessCore from "@reventlessdev/reventless-core/src/util/Util_ReadModel.res.mjs";
import * as AppSync_EventsApi$ReventlessAws from "../Api/AppSync_EventsApi.res.mjs";
import * as Util_LambdaLogging$ReventlessAws from "../../util/Util_LambdaLogging.res.mjs";
import * as Util_DynamoDbStream$ReventlessAws from "../../util/Util_DynamoDbStream.res.mjs";
import * as StateTopic_AppSync_Helpers$ReventlessAws from "./StateTopic_AppSync_Helpers.res.mjs";

let registry = {};

function makeForTable(tableName, streamArn, partitionKeyName, topicName, retiredField, eventsApi, param) {
  let checkedTableName = Pulumi.all([
    tableName,
    partitionKeyName
  ]).apply(param => {
    let tableName = param[0];
    StateTopic_AppSync_Helpers$ReventlessAws.checkPartitionKeyName(tableName, param[1]);
    return tableName;
  });
  let key = eventsApi.name;
  let entries = Stdlib_Option.getOr(registry[key], []);
  registry[key] = entries.concat([{
      tableName: checkedTableName,
      streamArn: streamArn,
      topicName: topicName,
      retiredField: retiredField
    }]);
}

function make(readModelName, topicName, allQueryDbs, eventsApi, opts) {
  let streamResource = Util_DynamoDbStream$ReventlessAws.findResource(Util_ReadModel$ReventlessCore.queryDbStorageResources(allQueryDbs, readModelName));
  makeForTable(streamResource.name, Util_DynamoDbStream$ReventlessAws.streamArnFromDynamoDbTableResource(streamResource), Pulumi.output(StateTopic_AppSync_Helpers$ReventlessAws.entityKeyPartitionAttribute), topicName, Stdlib_Option.map(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Plugin_Helpers$ReventlessCore.stateSchemaRegistry[readModelName], StateAnnotations$Reventless.getSpec), spec => spec.retired), r => r.field), eventsApi, opts);
}

function finish(eventsApi, opts) {
  let key = eventsApi.name;
  let entries = registry[key];
  if (entries === undefined) {
    return;
  }
  if (entries.length === 0) {
    return;
  }
  let name = eventsApi.name;
  let lambdaRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name + "StateTopicRole", Pulumi.output(AWS$ReventlessAws.Lambda.principal), AWS_Tags$ReventlessAws.make(name + "StateTopicRole", QueryDb$ReventlessCore.componentType, "Identity", undefined, name, undefined, undefined, undefined), opts);
  let streamArnsOutput = Pulumi.all(entries.map(e => e.streamArn));
  Pulumi.all([
    streamArnsOutput,
    eventsApi.api.apiArn
  ]).apply(param => {
    new (Aws.iam.RolePolicy)(name + "StateTopicPolicy", {
      policy: PolicyDocument$PulumiAws.toJsonString(PolicyDocument$PulumiAws.make(undefined, name + "StateTopicPolicy", [
        {
          Sid: "AllowLambdaLogging",
          Effect: "Allow",
          Action: "logs:*",
          Resource: "arn:aws:logs:*:*:*"
        },
        {
          Sid: "AllowReadDynamoDbStream",
          Effect: "Allow",
          Action: [
            "dynamodb:DescribeStream",
            "dynamodb:GetRecords",
            "dynamodb:GetShardIterator",
            "dynamodb:ListStreams"
          ],
          Resource: param[0]
        },
        {
          Sid: "AllowPublishAppSyncEvents",
          Effect: "Allow",
          Action: "appsync:EventPublish",
          Resource: param[1] + "/*"
        }
      ])),
      role: lambdaRole.id
    }, opts);
  });
  let topicMapJson = Pulumi.all(entries.map(e => e.tableName)).apply(tableNames => {
    let dict = {};
    tableNames.forEach((tableName, i) => {
      let topicName = entries[i].topicName;
      dict[tableName] = topicName;
    });
    return JSON.stringify(dict);
  });
  let retiredMapJson = Pulumi.all(entries.map(e => e.tableName)).apply(tableNames => {
    let dict = {};
    tableNames.forEach((tableName, i) => Stdlib_Option.forEach(entries[i].retiredField, f => {
      dict[tableName] = f;
    }));
    return JSON.stringify(dict);
  });
  let packageDirs = Object.fromEntries([[
      "@reventlessdev/reventless-aws",
      Util_Bundle$ReventlessAws.resolvePackageRoot(undefined, "@reventlessdev/reventless-aws")
    ]]);
  let match = Util_Bundle$ReventlessAws.buildCodeArchive("@reventlessdev/reventless-aws/src/adapter/StateTopic/StateTopic_AppSync_Ops.res.mjs", packageDirs, undefined, false);
  let layers = Stdlib_Option.getOr(Stdlib_Option.map(Lambda$PulumiAws.reventlessLayerArn, arn => [arn]), []);
  let appsyncEndpoint = AppSync_EventsApi$ReventlessAws.httpEndpoint(eventsApi);
  let logGroup = Util_LambdaLogging$ReventlessAws.makeManagedLogGroup(name + "StateTopicPublisher", undefined, AWS_Tags$ReventlessAws.make(name + "StateTopicPublisherLogGroup", QueryDb$ReventlessCore.componentType, "Logs", undefined, name, undefined, undefined, undefined), opts, undefined);
  let lambda = new (Aws.lambda.Function)(name + "StateTopicPublisher", {
    handler: "index.handler",
    runtime: "nodejs22.x",
    code: match.code,
    role: lambdaRole.arn,
    memorySize: 256,
    timeout: 30,
    layers: layers,
    tags: AWS_Tags$ReventlessAws.make(name + "StateTopic", QueryDb$ReventlessCore.componentType, "StateTopic", undefined, name, undefined, undefined, undefined),
    environment: {
      variables: Object.fromEntries([
        [
          "Environment",
          Pulumi.getStack()
        ],
        [
          "APPSYNC_ENDPOINT",
          appsyncEndpoint
        ],
        [
          "STATE_TOPIC_MAP",
          topicMapJson
        ],
        [
          "STATE_RETIRED_MAP",
          retiredMapJson
        ],
        [
          "NODE_OPTIONS",
          Util_Bundle$ReventlessAws.esmLoaderNodeOptions
        ],
        [
          "ESM_FALLBACK_DIRS",
          Util_Bundle$ReventlessAws.esmFallbackDirs
        ],
        Util_LambdaLogging$ReventlessAws.logLevelEntry()
      ])
    },
    sourceCodeHash: match.sourceCodeHash,
    loggingConfig: Util_LambdaLogging$ReventlessAws.loggingConfigFor(logGroup)
  }, opts);
  entries.forEach(entry => {
    let esmName = entry.topicName + "Stream2" + name + "StateTopic";
    new (Aws.lambda.EventSourceMapping)(esmName, {
      functionName: lambda.arn,
      bisectBatchOnFunctionError: true,
      eventSourceArn: entry.streamArn,
      maximumRetryAttempts: 3,
      startingPosition: "LATEST",
      tags: AWS_Tags$ReventlessAws.make(esmName, QueryDb$ReventlessCore.componentType, "EventSourceMapping", undefined, name, undefined, undefined, undefined)
    }, opts);
  });
  registry[key] = [];
}

export {
  registry,
  makeForTable,
  make,
  finish,
}
/* @pulumi/aws Not a pure module */
