// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var SSH2 = require("@reventless/bs-ssh2/src/SSH2.bs.js");
var Belt_Int = require("@rescript/std/lib/js/belt_Int.js");

function parseUrl(url) {
  var colonI = url.indexOf(":");
  var slashI = url.indexOf("/");
  var match = colonI > -1;
  var match$1 = slashI > -1;
  if (!match) {
    if (match$1) {
      return [
              url.slice(0, slashI),
              undefined,
              url.slice(slashI + 1 | 0)
            ];
    } else {
      return [
              url,
              undefined,
              ""
            ];
    }
  }
  if (!match$1) {
    return [
            url.slice(0, colonI),
            Belt_Int.fromString(url.slice(colonI + 1 | 0)),
            ""
          ];
  }
  var fst = colonI < slashI ? colonI : slashI;
  var port = colonI < slashI ? url.slice(colonI + 1 | 0, slashI) : url.slice(colonI + 1 | 0);
  var path = colonI < slashI ? url.slice(slashI + 1 | 0) : url.slice(slashI + 1 | 0, colonI);
  return [
          url.slice(0, fst),
          Belt_Int.fromString(port),
          path
        ];
}

var Client = SSH2.Client;

var ReadStreamOptions = SSH2.ReadStreamOptions;

var FastOptions = SSH2.FastOptions;

var WriteStreamOptions = SSH2.WriteStreamOptions;

var extendedError = SSH2.extendedError;

exports.Client = Client;
exports.ReadStreamOptions = ReadStreamOptions;
exports.FastOptions = FastOptions;
exports.WriteStreamOptions = WriteStreamOptions;
exports.extendedError = extendedError;
exports.parseUrl = parseUrl;
/* No side effect */
