// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function Make(Spec) {
  var make = function (param, param$1, param$2) {
    return {
            resources: []
          };
  };
  return {
          make: make
        };
}

exports.Make = Make;
/* No side effect */
