// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var ResourceQuery$Reventless = require("./ResourceQuery.res.js");

function bucketNameOfAllTasks(tasks, taskName) {
  return Core__Option.map(Core__Option.flatMap(tasks.find(function (task) {
                      return task.name === taskName;
                    }), (function (task) {
                    return task.bucket;
                  })), (function (bucket) {
                return bucket.bucket.get();
              }));
}

function bucketNameOfTaskExn(tasks, taskName) {
  return ResourceQuery$Reventless.unwrapResource(bucketNameOfAllTasks(tasks, taskName), "Bucket", taskName);
}

exports.bucketNameOfAllTasks = bucketNameOfAllTasks;
exports.bucketNameOfTaskExn = bucketNameOfTaskExn;
/* No side effect */
