// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("@rescript/std/lib/js/belt_Option.js");

function message(loc, exn) {
  return Belt_Option.getWithDefault(exn.message, "unspecified error") + Belt_Option.mapWithDefault(loc, "", (function (loc) {
                return " at " + loc;
              }));
}

exports.message = message;
/* No side effect */
