// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ECS$AwsSdk from "@reventlessdev/rescript-aws-sdk/src/ECS.res.mjs";
import * as ClientEcs from "@aws-sdk/client-ecs";

function clone(taskDefinition, cluster, fullQualifiedStackName, subnets, payload, param) {
  console.log("clone: requested by user " + (payload.meta.user + (" from ip " + payload.meta.ip)));
  let environment = Object.fromEntries([
    [
      "REVENTLESS_CORE_STACK",
      fullQualifiedStackName.organization + `/` + fullQualifiedStackName.project + `/` + fullQualifiedStackName.stack
    ],
    [
      "RESTORE_DATE_TIME",
      payload.restoreDateTime
    ]
  ]);
  return ECS$AwsSdk.RunTaskCommand.send(new ClientEcs.RunTaskCommand({
    taskDefinition: taskDefinition.get(),
    launchType: "FARGATE",
    cluster: cluster.get(),
    networkConfiguration: {
      awsvpcConfiguration: subnets
    },
    overrides: {
      containerOverrides: [{
          name: "reventless-ci",
          command: [
            "reventless-ci",
            "clone-environment"
          ],
          environment: environment
        }]
    }
  }));
}

export {
  clone,
}
/* ECS-AwsSdk Not a pure module */
