// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TestRunner$ReventlessInMemory from "../../../src/test/TestRunner.res.mjs";
import * as MixedSourceReadModelFixtures$ReventlessInMemory from "./MixedSourceReadModelFixtures.res.mjs";

describe("MixedSource ReadModel", () => {
  beforeAll(async () => {
    await TestRunner$ReventlessInMemory.resolve(MixedSourceReadModelFixtures$ReventlessInMemory.MixedRM.operations(MixedSourceReadModelFixtures$ReventlessInMemory.rm));
    await TestRunner$ReventlessInMemory.resolve(MixedSourceReadModelFixtures$ReventlessInMemory.aggregateResource.name);
    await TestRunner$ReventlessInMemory.resolve(MixedSourceReadModelFixtures$ReventlessInMemory.dcbResource.name);
  });
  test("aggregate event projects with source 'aggregate'", async () => {
    await MixedSourceReadModelFixtures$ReventlessInMemory.publishAggregateEvent("agg-1", {
      TAG: "AggregateItemCreated",
      name: "Widget"
    });
    let states = await MixedSourceReadModelFixtures$ReventlessInMemory.loadState("agg-1");
    expect(states.length).toBe(1);
    let state = states[0];
    expect(state.name).toBe("Widget");
    expect(state.source).toBe("aggregate");
  });
  test("DCB event projects with source 'dcb'", async () => {
    await MixedSourceReadModelFixtures$ReventlessInMemory.publishDcbEvent("dcb-1", {
      TAG: "DcbItemAdded",
      name: "Gadget"
    });
    let states = await MixedSourceReadModelFixtures$ReventlessInMemory.loadState("dcb-1");
    expect(states.length).toBe(1);
    let state = states[0];
    expect(state.name).toBe("Gadget");
    expect(state.source).toBe("dcb");
  });
  test("both sources coexist independently", async () => {
    let aggStates = await MixedSourceReadModelFixtures$ReventlessInMemory.loadState("agg-1");
    let dcbStates = await MixedSourceReadModelFixtures$ReventlessInMemory.loadState("dcb-1");
    expect(aggStates.length).toBe(1);
    expect(dcbStates.length).toBe(1);
    let agg = aggStates[0];
    let dcb = dcbStates[0];
    expect(agg.source).toBe("aggregate");
    expect(dcb.source).toBe("dcb");
  });
  test("aggregate update modifies existing entry", async () => {
    await MixedSourceReadModelFixtures$ReventlessInMemory.publishAggregateEvent("agg-1", {
      TAG: "AggregateItemRenamed",
      name: "Super Widget"
    });
    let states = await MixedSourceReadModelFixtures$ReventlessInMemory.loadState("agg-1");
    expect(states.length).toBe(1);
    let state = states[0];
    expect(state.name).toBe("Super Widget");
    expect(state.source).toBe("aggregate");
  });
  test("DCB update modifies existing entry", async () => {
    await MixedSourceReadModelFixtures$ReventlessInMemory.publishDcbEvent("dcb-1", {
      TAG: "DcbItemNameChanged",
      name: "Super Gadget"
    });
    let states = await MixedSourceReadModelFixtures$ReventlessInMemory.loadState("dcb-1");
    expect(states.length).toBe(1);
    let state = states[0];
    expect(state.name).toBe("Super Gadget");
    expect(state.source).toBe("dcb");
  });
});

/*  Not a pure module */
