// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Effect from "effect/Effect";
import * as Logger from "effect/Logger";
import * as LogLevel from "effect/LogLevel";
import * as Logger$ReventlessCore from "./Logger.res.mjs";

function _messageToString(msg) {
  if (Array.isArray(msg)) {
    return msg.map(j => {
      if (typeof j === "string") {
        return j;
      } else {
        return Stdlib_Option.getOr(JSON.stringify(j), "");
      }
    }).join(" ");
  }
  switch (typeof msg) {
    case "string" :
      return msg;
    default:
      return Stdlib_Option.getOr(JSON.stringify(msg), "");
  }
}

let _defaultMin = {
  contents: "Info"
};

function setDefaultMinLevel(l) {
  _defaultMin.contents = l;
}

function _effectMin() {
  let match = process.env.LOG_LEVEL;
  if (match !== undefined) {
    switch (match) {
      case "debug" :
        return LogLevel.Debug;
      case "error" :
        return LogLevel.Error;
      case "info" :
        return LogLevel.Info;
      case "silent" :
        return LogLevel.None;
      case "warn" :
        return LogLevel.Warning;
    }
  }
  let match$1 = _defaultMin.contents;
  switch (match$1) {
    case "Debug" :
      return LogLevel.Debug;
    case "Info" :
      return LogLevel.Info;
    case "Warn" :
      return LogLevel.Warning;
    case "Error" :
      return LogLevel.Error;
  }
}

function ordinalToLevel(ordinal) {
  if (ordinal >= 40000) {
    return "Error";
  } else if (ordinal >= 30000) {
    return "Warn";
  } else if (ordinal >= 20000) {
    return "Info";
  } else {
    return "Debug";
  }
}

function install() {
  Logger.defaultLogger.log = opts => {
    let raw = _messageToString(opts.message);
    let level = ordinalToLevel(opts.logLevel.ordinal);
    let idx = raw.indexOf(Logger$ReventlessCore.detailSeparator);
    if (idx < 0) {
      return Logger$ReventlessCore.emit(level, undefined, undefined, raw);
    }
    let msg = raw.slice(0, idx);
    let detailStr = raw.slice(idx + 1 | 0, raw.length);
    let detail;
    try {
      detail = JSON.parse(detailStr);
    } catch (exn) {
      detail = undefined;
    }
    Logger$ReventlessCore.emit(level, undefined, detail, msg);
  };
}

install();

function withComp(comp, msg) {
  let prefix = Logger$ReventlessCore.fmtComp(comp, undefined);
  if (prefix === "") {
    return msg;
  } else {
    return prefix + msg;
  }
}

function encode(comp, detail, msg) {
  let text = withComp(comp, msg);
  if (detail !== undefined) {
    return text + Logger$ReventlessCore.detailSeparator + JSON.stringify(detail);
  } else {
    return text;
  }
}

function logInfo(comp, detail, msg) {
  return Logger.withMinimumLogLevel(Effect.logInfo(encode(comp, detail, msg)), _effectMin());
}

function logWarn(comp, detail, msg) {
  return Logger.withMinimumLogLevel(Effect.logWarning(encode(comp, detail, msg)), _effectMin());
}

function logError(comp, detail, msg) {
  return Logger.withMinimumLogLevel(Effect.logError(encode(comp, detail, msg)), _effectMin());
}

function logDebug(comp, detail, msg) {
  return Logger.withMinimumLogLevel(Effect.logDebug(encode(comp, detail, msg)), _effectMin());
}

export {
  _messageToString,
  _defaultMin,
  setDefaultMinLevel,
  _effectMin,
  ordinalToLevel,
  install,
  withComp,
  encode,
  logInfo,
  logWarn,
  logError,
  logDebug,
}
/*  Not a pure module */
