// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stream from "../src/Stream.res.mjs";
import * as Effect from "effect";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";

describe("Stream bindings", () => {
  describe("construction", () => {
    test("fromIterable emits all items in order", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.fromIterable([
        1,
        2,
        3
      ])));
      expect(result).toEqual([
        1,
        2,
        3
      ]);
    });
    test("empty stream yields no items", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.empty));
      expect(result).toEqual([]);
    });
    test("fromEffect wraps a single value", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.fromEffect(Effect.Effect.succeed("hello"))));
      expect(result).toEqual(["hello"]);
    });
    test("fromQueue emits items already in the queue", async () => {
      let queue = Effect.Effect.runSync(Effect.Queue.unbounded());
      Effect.Effect.runSync(Effect.Queue.offer(queue, 10));
      Effect.Effect.runSync(Effect.Queue.offer(queue, 20));
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.take(Effect.Stream.fromQueue(queue), 2)));
      expect(result).toEqual([
        10,
        20
      ]);
    });
    test("paginateEffect pages through chunks until None", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Stream.paginateEffect(0, cursor => Effect.Effect.sync(() => {
        let all = [
          1,
          2,
          3,
          4,
          5
        ];
        let pageEnd = Primitive_int.min(cursor + 2 | 0, 5);
        let chunk = all.slice(cursor, pageEnd);
        let next = (cursor + 2 | 0) < 5 ? cursor + 2 | 0 : undefined;
        return [
          chunk,
          next
        ];
      }))));
      expect(result).toEqual([
        1,
        2,
        3,
        4,
        5
      ]);
    });
  });
  describe("transformation", () => {
    test("map transforms each item", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.map(Effect.Stream.fromIterable([
        1,
        2,
        3
      ]), n => (n << 1))));
      expect(result).toEqual([
        2,
        4,
        6
      ]);
    });
    test("filter removes items not matching predicate", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.filter(Effect.Stream.fromIterable([
        1,
        2,
        3,
        4,
        5
      ]), n => n % 2 === 0)));
      expect(result).toEqual([
        2,
        4
      ]);
    });
    test("take limits to first N items", async () => {
      let result = await Effect.Effect.runPromise(Stream.runCollect(Effect.Stream.take(Effect.Stream.fromIterable([
        1,
        2,
        3,
        4,
        5
      ]), 3)));
      expect(result).toEqual([
        1,
        2,
        3
      ]);
    });
  });
  describe("terminal runners", () => {
    test("runFold accumulates state across all items", async () => {
      let sum = await Effect.Effect.runPromise(Effect.Stream.runFold(Effect.Stream.fromIterable([
        1,
        2,
        3,
        4
      ]), 0, (acc, n) => acc + n | 0));
      expect(sum).toBe(10);
    });
    test("runFold can accumulate a tuple", async () => {
      let match = await Effect.Effect.runPromise(Effect.Stream.runFold(Effect.Stream.fromIterable([
        "a",
        "b",
        "c"
      ]), [
        "",
        0
      ], (param, s) => [
        s,
        param[1] + 1 | 0
      ]));
      expect(match[0]).toBe("c");
      expect(match[1]).toBe(3);
    });
    test("runHead returns Some for non-empty stream", async () => {
      let head = await Effect.Effect.runPromise(Stream.runHead(Effect.Stream.fromIterable([
        42,
        1,
        2
      ])));
      expect(head).toEqual(42);
    });
    test("runHead returns None for empty stream", async () => {
      let head = await Effect.Effect.runPromise(Stream.runHead(Effect.Stream.empty));
      expect(head).toEqual(undefined);
    });
  });
});

/*  Not a pure module */
