// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LocalBus$ReventlessLocal from "../../src/adapter/LocalBus.res.mjs";
import * as TestRunner$ReventlessLocal from "../../src/test/TestRunner.res.mjs";

TestRunner$ReventlessLocal.setup();

let defaultMeta = {
  service: "test",
  time: "",
  ip: "",
  user: "test",
  msgId: "",
  correlationId: ""
};

describe("LocalBus PubSub (Phase F)", () => {
  describe("publishEvent timing", () => {
    test("resolves after exactly 2 microtask ticks", async () => {
      let TestBus = LocalBus$ReventlessLocal.Make({});
      let delivered = {
        contents: false
      };
      TestBus.subscribeToEvents("T", async (param, param$1, param$2) => {
        delivered.contents = true;
      });
      let pubPromise = TestBus.publishEvent("T", "svc", defaultMeta, JSON.parse("{}"));
      expect(delivered.contents).toBe(false);
      await Promise.resolve();
      await Promise.resolve();
      await pubPromise;
      expect(delivered.contents).toBe(true);
    });
    test("publishEvent with no subscribers returns immediately", async () => {
      let TestBus = LocalBus$ReventlessLocal.Make({});
      return await TestBus.publishEvent("empty-topic", "svc", defaultMeta, null);
    });
  });
  describe("fan-out", () => {
    test("delivers to all subscribers on the same topic", async () => {
      let TestBus = LocalBus$ReventlessLocal.Make({});
      let count = {
        contents: 0
      };
      TestBus.subscribeToEvents("T", async (param, param$1, param$2) => {
        count.contents = count.contents + 1 | 0;
      });
      TestBus.subscribeToEvents("T", async (param, param$1, param$2) => {
        count.contents = count.contents + 1 | 0;
      });
      TestBus.subscribeToEvents("T", async (param, param$1, param$2) => {
        count.contents = count.contents + 1 | 0;
      });
      await TestBus.publishEvent("T", "svc", defaultMeta, JSON.parse("{}"));
      expect(count.contents).toBe(3);
    });
    test("publishing to topic-a does not reach topic-b subscribers", async () => {
      let TestBus = LocalBus$ReventlessLocal.Make({});
      let countA = {
        contents: 0
      };
      let countB = {
        contents: 0
      };
      TestBus.subscribeToEvents("topic-a", async (param, param$1, param$2) => {
        countA.contents = countA.contents + 1 | 0;
      });
      TestBus.subscribeToEvents("topic-b", async (param, param$1, param$2) => {
        countB.contents = countB.contents + 1 | 0;
      });
      await TestBus.publishEvent("topic-a", "svc", defaultMeta, null);
      expect(countA.contents).toBe(1);
      expect(countB.contents).toBe(0);
    });
  });
});

export {
  defaultMeta,
}
/*  Not a pure module */
