// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as ReadModel$Reventless from "@reventlessdev/reventless-spec/src/components/ReadModel.res.mjs";

let stateSchema = S.schema(s => ({
  email: s.m(S.string),
  address: s.m(S.string),
  deactivated: s.m(S.bool)
}));

let moduleUrl = import.meta.url;

let config = ReadModel$Reventless.config(undefined, undefined, undefined);

let Id;

let name = "Customers";

let subIdConfig;

export {
  Id,
  stateSchema,
  name,
  moduleUrl,
  config,
  subIdConfig,
}
/* stateSchema Not a pure module */
