// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TestRunner$ReventlessInMemory from "../../../src/test/TestRunner.res.mjs";
import * as InMemory_Bus$ReventlessInMemory from "../../../src/adapter/InMemory_Bus.res.mjs";

let Bus = InMemory_Bus$ReventlessInMemory.Make({});

TestRunner$ReventlessInMemory.setup();

export {
  Bus,
}
/* Bus Not a pure module */
