// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Hint$ReventlessGwt from "./Hint.res.mjs";
import * as Outcome$ReventlessGwt from "./Outcome.res.mjs";
import * as ComponentMeta$ReventlessGwt from "./ComponentMeta.res.mjs";
import * as RenderRescript$ReventlessGwt from "./RenderRescript.res.mjs";

function write(s) {
  process.stdout.write(s);
}

function writeLine(s) {
  process.stdout.write(s + "\n");
}

function setIfSome(d, k, o) {
  if (o !== undefined) {
    d[k] = o;
    return;
  }
}

function uriOf(path) {
  return "file://" + path;
}

function fileLabelOf(abs) {
  let base = Nodepath.basename(abs);
  if (base.endsWith(".res.mjs")) {
    return base.slice(0, base.length - 8 | 0);
  } else {
    return base;
  }
}

function relativeToCwd(abs) {
  return Nodepath.relative(process.cwd(), abs);
}

let sourceLineCache = {};

function resetLocateCache() {
  Object.keys(sourceLineCache).forEach(k => Stdlib_Dict.$$delete(sourceLineCache, k));
}

function mjsToRes(mjsPath) {
  if (mjsPath.endsWith(".res.mjs")) {
    return mjsPath.slice(0, mjsPath.length - 4 | 0);
  }
}

function readLinesCached(resPath) {
  let v = sourceLineCache[resPath];
  if (v !== undefined) {
    return Primitive_option.valFromOption(v);
  }
  let v$1;
  try {
    v$1 = Nodefs.existsSync(resPath) ? Nodefs.readFileSync(resPath, "utf8").split("\n") : undefined;
  } catch (exn) {
    v$1 = undefined;
  }
  sourceLineCache[resPath] = v$1;
  return v$1;
}

function escapeForDouble(s) {
  return s.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"");
}

function escapeForSingle(s) {
  return s.replaceAll("\\", "\\\\").replaceAll("'", "\\'");
}

function locateInSource(mjsPath, label) {
  let resPath = mjsToRes(mjsPath);
  if (resPath === undefined) {
    return;
  }
  let lines = readLinesCached(resPath);
  if (lines === undefined) {
    return;
  }
  let needleD = "\"" + escapeForDouble(label) + "\"";
  let needleS = "'" + escapeForSingle(label) + "'";
  let total = lines.length;
  let _i = 0;
  while (true) {
    let i = _i;
    if (i >= total) {
      return;
    }
    let line = lines[i];
    let idxD = line.indexOf(needleD);
    let idxS = line.indexOf(needleS);
    let col = idxD !== -1 ? (
        idxS !== -1 ? (
            idxD < idxS ? idxD : idxS
          ) + 1 | 0 : idxD + 1 | 0
      ) : (
        idxS !== -1 ? idxS + 1 | 0 : -1
      );
    if (col >= 0) {
      return {
        file: resPath,
        line: i + 1 | 0,
        column: col
      };
    }
    _i = i + 1 | 0;
    continue;
  };
}

function rangeJson(loc) {
  let start = {};
  start["line"] = loc.line - 1 | 0;
  start["character"] = loc.column - 1 | 0;
  let end_ = {};
  end_["line"] = loc.line - 1 | 0;
  end_["character"] = loc.column - 1 | 0;
  let r = {};
  r["start"] = start;
  r["end"] = end_;
  return r;
}

function locationJson(loc) {
  let d = {};
  d["uri"] = "file://" + loc.file;
  d["range"] = rangeJson(loc);
  return d;
}

function event(payload) {
  let s = JSON.stringify(payload);
  process.stdout.write(s + "\n");
}

function hello() {
  let d = {};
  d["event"] = "hello";
  d["protocol"] = 2;
  event(d);
}

function discoverStart() {
  let d = {};
  d["event"] = "discoverStart";
  event(d);
}

function emitDiscoveryItems(files) {
  files.forEach(param => {
    let path = param[0];
    let resPath = mjsToRes(path);
    let fileUri = resPath !== undefined ? (
        Nodefs.existsSync(resPath) ? "file://" + resPath : "file://" + path
      ) : "file://" + path;
    let d = {};
    d["event"] = "item";
    d["id"] = path;
    d["kind"] = "file";
    d["label"] = fileLabelOf(path);
    d["description"] = Nodepath.relative(process.cwd(), path);
    d["uri"] = fileUri;
    let c = ComponentMeta$ReventlessGwt.componentOfTestFile(path);
    if (c !== undefined) {
      let comp = {};
      comp["kind"] = c.kind;
      comp["name"] = c.name;
      d["component"] = comp;
    }
    event(d);
    let seenDescribes = {};
    param[1].forEach(t => {
      let stack = {
        contents: []
      };
      t.describePath.forEach(label => {
        let parent = stack.contents.length === 0 ? path : path + "::" + stack.contents.join("::");
        stack.contents = stack.contents.concat([label]);
        let id = path + "::" + stack.contents.join("::");
        let match = seenDescribes[id];
        if (match !== undefined) {
          return;
        }
        seenDescribes[id] = true;
        let s = {};
        s["event"] = "item";
        s["id"] = id;
        s["parent"] = parent;
        s["kind"] = "suite";
        s["label"] = label;
        let loc = locateInSource(path, label);
        if (loc !== undefined) {
          s["uri"] = "file://" + loc.file;
          s["range"] = rangeJson(loc);
        }
        event(s);
      });
      let parent = t.describePath.length === 0 ? path : path + "::" + t.describePath.join("::");
      let testId = path + "::" + t.id;
      let leaf = {};
      leaf["event"] = "item";
      leaf["id"] = testId;
      leaf["parent"] = parent;
      leaf["kind"] = "test";
      leaf["label"] = t.name;
      let resLoc = locateInSource(path, t.name);
      let match = t.location;
      let exit = 0;
      let loc;
      if (resLoc !== undefined) {
        loc = resLoc;
        exit = 1;
      } else if (match !== undefined) {
        loc = match;
        exit = 1;
      }
      if (exit === 1) {
        leaf["uri"] = "file://" + loc.file;
        leaf["range"] = rangeJson(loc);
      }
      event(leaf);
    });
  });
}

function discoverEnd(total) {
  let d = {};
  d["event"] = "discoverEnd";
  d["total"] = total;
  event(d);
}

function packages(pkgs) {
  let d = {};
  d["event"] = "packages";
  let arr = pkgs.map(p => {
    let o = {};
    o["name"] = p.name;
    o["dir"] = p.dir;
    o["build"] = p.build;
    return o;
  });
  d["packages"] = arr;
  event(d);
}

function components(comps) {
  let d = {};
  d["event"] = "components";
  let arr = comps.map(c => {
    let o = {};
    o["dir"] = c.dir;
    o["kind"] = c.kind;
    o["name"] = c.name;
    return o;
  });
  d["components"] = arr;
  event(d);
}

function buildStart(pkg) {
  let d = {};
  d["event"] = "buildStart";
  d["package"] = pkg;
  event(d);
}

function buildOk(pkg, durationMs) {
  let d = {};
  d["event"] = "buildOk";
  d["package"] = pkg;
  d["durationMs"] = durationMs;
  event(d);
}

function buildFail(pkg, message) {
  let d = {};
  d["event"] = "buildFail";
  d["package"] = pkg;
  d["message"] = message;
  event(d);
}

function buildExternal(pkg) {
  let d = {};
  d["event"] = "buildExternal";
  d["package"] = pkg;
  event(d);
}

function runStart(total, filter) {
  let d = {};
  d["event"] = "runStart";
  d["total"] = total;
  d["filter"] = filter.map(prim => prim);
  event(d);
}

function testStart(id) {
  let d = {};
  d["event"] = "testStart";
  d["id"] = id;
  event(d);
}

function testPass(id, durationMs) {
  let d = {};
  d["event"] = "testPass";
  d["id"] = id;
  d["durationMs"] = durationMs;
  event(d);
}

function testSkip(id, reason) {
  let d = {};
  d["event"] = "testSkip";
  d["id"] = id;
  d["reason"] = reason;
  event(d);
}

function messagePayload(t) {
  let d = {};
  let m = t.mismatch;
  if (m !== undefined) {
    let hint = Hint$ReventlessGwt.forMismatch(t.slice, m);
    d["message"] = hint.message;
    switch (m.TAG) {
      case "ErrorMismatch" :
        let actual = m.actual;
        d["expected"] = "Error(" + RenderRescript$ReventlessGwt.render(undefined, m.expected) + ")";
        let actStr = actual !== undefined ? "Error(" + RenderRescript$ReventlessGwt.render(undefined, actual) + ")" : "Ok(" + RenderRescript$ReventlessGwt.renderMany(m.actualEvents) + ")";
        d["actual"] = actStr;
        break;
      case "StateMismatch" :
        d["expected"] = RenderRescript$ReventlessGwt.renderOption(m.expected);
        d["actual"] = RenderRescript$ReventlessGwt.renderOption(m.actual);
        break;
      case "NoEventExpected" :
        d["expected"] = "[]";
        d["actual"] = RenderRescript$ReventlessGwt.renderMany(m.actual);
        break;
      case "TodoMismatch" :
        d["expected"] = Outcome$ReventlessGwt.format(m);
        d["actual"] = "";
        break;
      case "AppendConditionMismatch" :
        d["expected"] = RenderRescript$ReventlessGwt.render(undefined, m.expected);
        d["actual"] = RenderRescript$ReventlessGwt.render(undefined, m.actual);
        break;
      case "TranslateError" :
        d["expected"] = m.expected;
        d["actual"] = Stdlib_Option.getOr(m.actual, "(none)");
        break;
      case "EventsMismatch" :
      case "QueryRowsMismatch" :
      case "PublishedActionsMismatch" :
        d["expected"] = RenderRescript$ReventlessGwt.renderMany(m.expected);
        d["actual"] = RenderRescript$ReventlessGwt.renderMany(m.actual);
        break;
      case "Throw" :
        d["expected"] = "";
        d["actual"] = m.error;
        break;
    }
    let loc = t.location;
    if (loc !== undefined) {
      let resLoc = locateInSource(loc.file, t.name);
      d["location"] = locationJson(Stdlib_Option.getOr(resLoc, loc));
    }
  } else {
    d["message"] = "failed";
  }
  return d;
}

function testFail(t, id) {
  let d = {};
  d["event"] = "testFail";
  d["id"] = id;
  d["durationMs"] = t.durationMs;
  d["messages"] = [messagePayload(t)];
  event(d);
}

function runEnd(s) {
  let d = {};
  d["event"] = "runEnd";
  d["passed"] = s.passed;
  d["failed"] = s.failed;
  d["skipped"] = s.skipped;
  d["durationMs"] = s.durationMs;
  event(d);
}

let protocolVersion = 2;

export {
  write,
  writeLine,
  setIfSome,
  uriOf,
  fileLabelOf,
  relativeToCwd,
  sourceLineCache,
  resetLocateCache,
  mjsToRes,
  readLinesCached,
  escapeForDouble,
  escapeForSingle,
  locateInSource,
  rangeJson,
  locationJson,
  event,
  protocolVersion,
  hello,
  discoverStart,
  emitDiscoveryItems,
  discoverEnd,
  packages,
  components,
  buildStart,
  buildOk,
  buildFail,
  buildExternal,
  runStart,
  testStart,
  testPass,
  testSkip,
  messagePayload,
  testFail,
  runEnd,
}
/* node:fs Not a pure module */
