// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Outcome$ReventlessGwt from "./Outcome.res.mjs";
import * as JestBind$ReventlessGwt from "./JestBind.res.mjs";
import * as Message$ReventlessCore from "@reventlessdev/reventless-core/src/Message.res.mjs";

function Make(Spec) {
  S.enableJson();
  let test = (name, body) => JestBind$ReventlessGwt.test(Spec.name, name, body);
  let errors = {
    contents: []
  };
  let givenEvents = consumed => consumed;
  let whenCmd = (history, cmd) => {
    errors.contents = [];
    let state = Stdlib_Array.reduce(history, Spec.initialState, Spec.evolve);
    let events = Spec.decide(state, cmd);
    if (events.TAG === "Ok") {
      return events._0;
    }
    errors.contents = [events._0];
    return [];
  };
  let encEvent = e => Message$ReventlessCore.encode(e, Spec.eventSchema);
  let encError = err => Message$ReventlessCore.encode(err, Spec.errorSchema);
  let unexpectedError = events => {
    let actual = Stdlib_Option.map(errors.contents[0], encError);
    return Outcome$ReventlessGwt.fail({
      TAG: "ErrorMismatch",
      expected: null,
      actual: actual,
      actualEvents: events.map(encEvent)
    });
  };
  let thenEvents = (events, expectedEvents) => {
    if (errors.contents.length !== 0) {
      return unexpectedError(events);
    } else if (Primitive_object.equal(events, expectedEvents)) {
      return Outcome$ReventlessGwt.pass;
    } else {
      return Outcome$ReventlessGwt.fail({
        TAG: "EventsMismatch",
        expected: expectedEvents.map(encEvent),
        actual: events.map(encEvent)
      });
    }
  };
  let thenEvent = (events, expectedEvent) => thenEvents(events, [expectedEvent]);
  let thenNoEvent = events => {
    if (errors.contents.length !== 0) {
      return unexpectedError(events);
    } else if (events.length === 0) {
      return Outcome$ReventlessGwt.pass;
    } else {
      return Outcome$ReventlessGwt.fail({
        TAG: "NoEventExpected",
        actual: events.map(encEvent)
      });
    }
  };
  let matchesError = (events, expectedEvents, expectedError) => {
    let expectedErrorJson = Message$ReventlessCore.encode(expectedError, Spec.errorSchema);
    let actual = errors.contents[0];
    if (actual === undefined) {
      return Outcome$ReventlessGwt.fail({
        TAG: "ErrorMismatch",
        expected: expectedErrorJson,
        actual: undefined,
        actualEvents: events.map(encEvent)
      });
    }
    let actual$1 = Primitive_option.valFromOption(actual);
    if (Primitive_object.notequal(actual$1, expectedError)) {
      return Outcome$ReventlessGwt.fail({
        TAG: "ErrorMismatch",
        expected: expectedErrorJson,
        actual: Message$ReventlessCore.encode(actual$1, Spec.errorSchema),
        actualEvents: events.map(encEvent)
      });
    } else if (Primitive_object.equal(events, expectedEvents)) {
      return Outcome$ReventlessGwt.pass;
    } else {
      return Outcome$ReventlessGwt.fail({
        TAG: "EventsMismatch",
        expected: expectedEvents.map(encEvent),
        actual: events.map(encEvent)
      });
    }
  };
  let thenError = (events, expectedError) => matchesError(events, [], expectedError);
  let thenEventWithError = (events, expectedEvent, expectedError) => matchesError(events, [expectedEvent], expectedError);
  let thenEventsWithError = matchesError;
  return {
    Spec: Spec,
    describe: JestBind$ReventlessGwt.describe,
    test: test,
    givenEvents: givenEvents,
    whenCmd: whenCmd,
    thenEvent: thenEvent,
    thenEvents: thenEvents,
    thenNoEvent: thenNoEvent,
    thenEventWithError: thenEventWithError,
    thenEventsWithError: thenEventsWithError,
    thenError: thenError
  };
}

export {
  Make,
}
/* S Not a pure module */
