// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReventlessSeedAws from "@reventlessdev/reventless-seed-aws/src/ReventlessSeedAws.res.mjs";
import * as Seed_Runner$ReventlessSeed from "@reventlessdev/reventless-seed/src/Seed_Runner.res.mjs";
import * as HybridSeedData$OnlineShopHybridSeed from "@reventlessdev/online-shop-hybrid-seed/src/HybridSeedData.res.mjs";

Seed_Runner$ReventlessSeed.seed(HybridSeedData$OnlineShopHybridSeed.dataSets, ReventlessSeedAws.connect(undefined, undefined, "https://api.pulumi.com", undefined));

/*  Not a pure module */
