// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Pulumi = require("@pulumi/pulumi");

function unwrappedToResource(unwrappedResource) {
  return {
          service: Pulumi.output(unwrappedResource.service),
          name: Pulumi.output(unwrappedResource.name),
          id: Pulumi.output(unwrappedResource.id),
          urn: Pulumi.output(unwrappedResource.urn),
          info: Pulumi.output(unwrappedResource.info)
        };
}

var stackRefResourceToResource = unwrappedToResource;

exports.unwrappedToResource = unwrappedToResource;
exports.stackRefResourceToResource = stackRefResourceToResource;
/* @pulumi/pulumi Not a pure module */
