// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Role$Reventless from "@reventlessdev/reventless-spec/src/types/Role.res.mjs";
import * as OwnerScope$Reventless from "@reventlessdev/reventless-spec/src/types/OwnerScope.res.mjs";

let key = "REVENTLESS_ELEVATED_GROUPS";

function entry() {
  let groups = OwnerScope$Reventless.elevatedGroups();
  if (groups.length !== 0) {
    return [
      key,
      groups.join(",")
    ];
  }
}

function applyElevatedGroupsDefault(variables) {
  if (Stdlib_Option.isNone(variables[key])) {
    return Stdlib_Option.forEach(entry(), param => {
      variables[param[0]] = param[1];
    });
  }
}

function applyRoleGroupsDefault(variables) {
  let match = variables[Role$Reventless.envKey];
  let match$1 = Role$Reventless.envValue();
  if (match !== undefined || match$1 === undefined) {
    return;
  } else {
    variables[Role$Reventless.envKey] = match$1;
    return;
  }
}

export {
  key,
  entry,
  applyElevatedGroupsDefault,
  applyRoleGroupsDefault,
}
/* Role-Reventless Not a pure module */
