// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as ReadModel$Reventless from "@reventlessdev/reventless-spec/src/components/ReadModel.res.mjs";

let stateSchema = S.schema(s => ({
  productId: s.m(S.string),
  name: s.m(S.string),
  description: s.m(S.string),
  price: s.m(S.float)
}));

let consumedEventSchema = S.union([
  S.schema(s => ({
    TAG: "ProductAdded",
    productId: s.m(DcbTag$Reventless.string),
    name: s.m(S.string),
    description: s.m(S.string),
    price: s.m(S.float)
  })),
  S.schema(s => ({
    TAG: "ProductNameChanged",
    productId: s.m(DcbTag$Reventless.string),
    name: s.m(S.string)
  })),
  S.schema(s => ({
    TAG: "ProductDescriptionChanged",
    productId: s.m(DcbTag$Reventless.string),
    description: s.m(S.string)
  })),
  S.schema(s => ({
    TAG: "ProductPriceChanged",
    productId: s.m(DcbTag$Reventless.string),
    price: s.m(S.float)
  }))
]);

let config = ReadModel$Reventless.config(undefined, undefined, undefined);

let name = "Products";

let Id;

let subIdConfig;

let moduleUrl = "@reventlessdev/online-shop-dcb-catalog/src/Product/StateViewSlice/Products.res.mjs";

let authorization = "AllowAuthenticated";

let visibility = "Public";

export {
  name,
  Id,
  stateSchema,
  consumedEventSchema,
  config,
  subIdConfig,
  moduleUrl,
  authorization,
  visibility,
}
/* stateSchema Not a pure module */
