// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Plugin from "./Plugin.res.mjs";
import * as Platform$ReventlessAws from "@reventlessdev/reventless-aws/src/Platform.res.mjs";
import * as PackageVersion$Reventless from "@reventlessdev/reventless-spec/src/PackageVersion.res.mjs";

let Platform = Platform$ReventlessAws.Make({});

let Ordering = Plugin.Make(Platform);

let $$default = Platform.deployPlugin(PackageVersion$Reventless.fromCaller(), {
  make: Ordering.make
}, undefined);

export {
  Platform,
  Ordering,
  $$default as default,
}
/* Platform Not a pure module */
