// Generated by ReScript, PLEASE EDIT WITH CARE


async function sendOrderConfirmation(param, param$1) {
  console.log("[EmailService] Order confirmation sent");
}

export {
  sendOrderConfirmation,
}
/* No side effect */
