// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Aws = require("@pulumi/aws");
var Lambda$PulumiAws = require("@reventless/bs-pulumi-aws/src/Lambda/Lambda.bs.js");

var name = "DeadLetterQueue";

var nameFifo = "FIFODeadLetterQueue";

var queue = new (Aws.sqs.Queue)(name, {
      visibilityTimeoutSeconds: 180,
      sqsManagedSseEnabled: false
    }, undefined);

var fifoQueue = new (Aws.sqs.Queue)(nameFifo, {
      contentBasedDeduplication: true,
      fifoQueue: true,
      visibilityTimeoutSeconds: 180,
      sqsManagedSseEnabled: false
    }, undefined);

function callback(evt, ctx) {
  return new Promise((function (resolve, param) {
                return resolve((console.log("DEAD LETTER ITEM:", evt, ctx), undefined));
              }));
}

var handler = new (Aws.lambda.CallbackFunction)(name, Curry.app(Lambda$PulumiAws.CallbackFunction.Args.make, [
          callback,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined,
          undefined
        ]), {
      parent: queue
    });

var subscription = queue.onEvent(name, handler, undefined, undefined);

var fifoSubscription = fifoQueue.onEvent(nameFifo, handler, undefined, undefined);

exports.name = name;
exports.nameFifo = nameFifo;
exports.queue = queue;
exports.fifoQueue = fifoQueue;
exports.callback = callback;
exports.handler = handler;
exports.subscription = subscription;
exports.fifoSubscription = fifoSubscription;
/* queue Not a pure module */
