// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Jest from "@glennsl/rescript-jest/src/jest.res.mjs";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as StateAnnotations$Reventless from "@reventlessdev/reventless-spec/src/components/StateAnnotations.res.mjs";
import * as SuryToJsonSchema$ReventlessCore from "../../src/components/Api/SuryToJsonSchema.res.mjs";

function getProperty(schema, key) {
  let obj = Stdlib_JSON.Decode.object(schema);
  if (obj !== undefined) {
    return obj[key];
  }
}

function getPropertyOf(schema, fieldName) {
  let props = getProperty(schema, "properties");
  if (props === undefined) {
    return;
  }
  let obj = Stdlib_JSON.Decode.object(props);
  if (obj !== undefined) {
    return obj[fieldName];
  }
}

let emptySpec_ids = [];

let emptySpec_compositeIds = [];

let emptySpec_subIds = [];

let emptySpec_compositeSubIds = [];

let emptySpec_indexes = [];

let emptySpec_hidden = [];

let emptySpec_summary = [];

let emptySpec_drillTargets = [];

let emptySpec_drillTargetKeys = [];

let emptySpec_collapsed = [];

let emptySpec = {
  ids: emptySpec_ids,
  compositeIds: emptySpec_compositeIds,
  subIds: emptySpec_subIds,
  compositeSubIds: emptySpec_compositeSubIds,
  indexes: emptySpec_indexes,
  hidden: emptySpec_hidden,
  summary: emptySpec_summary,
  drillTargets: emptySpec_drillTargets,
  drillTargetKeys: emptySpec_drillTargetKeys,
  collapsed: emptySpec_collapsed
};

Jest.describe("SuryToJsonSchema:", () => {
  Jest.describe("deriveObjectSchema with no annotations:", () => Jest.test("emits plain JSON Schema when no metadata is attached", () => {
    let schema = S.schema(s => ({
      id: s.m(S.string),
      name: s.m(S.string)
    }));
    let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema);
    let idSchema = getPropertyOf(json, "id");
    return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(idSchema, s => getProperty(s, "x-reventless-id"))), undefined);
  }));
  Jest.describe("deriveObjectSchema with stateAnnotations metadata:", () => {
    let withSpec = (schema, spec) => S.Metadata.set(schema, StateAnnotations$Reventless.stateAnnotationsId, spec);
    Jest.test("emits x-reventless-id on field listed in ids", () => {
      let schema = S.schema(s => ({
        entityId: s.m(S.string),
        name: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: ["entityId"],
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let entityIdSchema = getPropertyOf(json, "entityId");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(Stdlib_Option.flatMap(entityIdSchema, s => getProperty(s, "x-reventless-id")), Stdlib_JSON.Decode.bool)), true);
    });
    Jest.test("emits x-reventless-compositeId on each compositeId field", () => {
      let schema = S.schema(s => ({
        environment: s.m(S.string),
        platformName: s.m(S.string),
        name: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: [
          "environment",
          "platformName"
        ],
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let envSchema = getPropertyOf(json, "environment");
      let platformSchema = getPropertyOf(json, "platformName");
      return Jest.Expect.toEqual(Jest.Expect.expect([
        Stdlib_Option.flatMap(Stdlib_Option.flatMap(envSchema, s => getProperty(s, "x-reventless-compositeId")), Stdlib_JSON.Decode.bool),
        Stdlib_Option.flatMap(Stdlib_Option.flatMap(platformSchema, s => getProperty(s, "x-reventless-compositeId")), Stdlib_JSON.Decode.bool)
      ]), [
        true,
        true
      ]);
    });
    Jest.test("emits x-reventless-subId on field listed in subIds", () => {
      let schema = S.schema(s => ({
        itemId: s.m(S.string),
        version: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: ["version"],
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let versionSchema = getPropertyOf(json, "version");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(Stdlib_Option.flatMap(versionSchema, s => getProperty(s, "x-reventless-subId")), Stdlib_JSON.Decode.bool)), true);
    });
    Jest.test("emits x-reventless-index as the index name when named", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        ownerId: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: [[
            "ownerId",
            "byOwner"
          ]],
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let ownerIdSchema = getPropertyOf(json, "ownerId");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(Stdlib_Option.flatMap(ownerIdSchema, s => getProperty(s, "x-reventless-index")), Stdlib_JSON.Decode.string)), "byOwner");
    });
    Jest.test("emits x-reventless-index as true for unnamed @index", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        category: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: [[
            "category",
            ""
          ]],
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let categorySchema = getPropertyOf(json, "category");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(Stdlib_Option.flatMap(categorySchema, s => getProperty(s, "x-reventless-index")), Stdlib_JSON.Decode.bool)), true);
    });
    Jest.test("does not emit x-reventless-* on unannotated fields", () => {
      let schema = S.schema(s => ({
        entityId: s.m(S.string),
        name: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: ["entityId"],
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let nameSchema = getPropertyOf(json, "name");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(nameSchema, s => getProperty(s, "x-reventless-id"))), undefined);
    });
    Jest.test("emits x-reventless-hidden on field listed in hidden", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        deploymentId: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: ["deploymentId"],
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let deploymentIdSchema = getPropertyOf(json, "deploymentId");
      let idSchema = getPropertyOf(json, "id");
      return Jest.Expect.toEqual(Jest.Expect.expect([
        Stdlib_Option.flatMap(Stdlib_Option.flatMap(deploymentIdSchema, s => getProperty(s, "x-reventless-hidden")), Stdlib_JSON.Decode.bool),
        Stdlib_Option.flatMap(idSchema, s => getProperty(s, "x-reventless-hidden"))
      ]), [
        true,
        undefined
      ]);
    });
    Jest.test("emits x-reventless-summary on field listed in summary", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        pluginName: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: ["pluginName"],
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let pluginNameSchema = getPropertyOf(json, "pluginName");
      let idSchema = getPropertyOf(json, "id");
      return Jest.Expect.toEqual(Jest.Expect.expect([
        Stdlib_Option.flatMap(Stdlib_Option.flatMap(pluginNameSchema, s => getProperty(s, "x-reventless-summary")), Stdlib_JSON.Decode.bool),
        Stdlib_Option.flatMap(idSchema, s => getProperty(s, "x-reventless-summary"))
      ]), [
        true,
        undefined
      ]);
    });
    Jest.test("emits x-reventless-drillTarget as the slice name", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        components: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: [[
            "components",
            "ResourceInventory"
          ]],
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let componentsSchema = getPropertyOf(json, "components");
      let idSchema = getPropertyOf(json, "id");
      return Jest.Expect.toEqual(Jest.Expect.expect([
        Stdlib_Option.flatMap(Stdlib_Option.flatMap(componentsSchema, s => getProperty(s, "x-reventless-drillTarget")), Stdlib_JSON.Decode.string),
        Stdlib_Option.flatMap(idSchema, s => getProperty(s, "x-reventless-drillTarget"))
      ]), [
        "ResourceInventory",
        undefined
      ]);
    });
    Jest.test("emits x-reventless-drillTargetKey as the key path", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        components: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: [[
            "components",
            "ResourceInventory"
          ]],
        drillTargetKeys: [[
            "components",
            "kind/name"
          ]],
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let componentsSchema = getPropertyOf(json, "components");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(Stdlib_Option.flatMap(componentsSchema, s => getProperty(s, "x-reventless-drillTargetKey")), Stdlib_JSON.Decode.string)), "kind/name");
    });
    Jest.test("does not emit x-reventless-drillTargetKey when no key was supplied", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        components: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: [[
            "components",
            "ResourceInventory"
          ]],
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: emptySpec_collapsed
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let componentsSchema = getPropertyOf(json, "components");
      return Jest.Expect.toBe(Jest.Expect.expect(Stdlib_Option.flatMap(componentsSchema, s => getProperty(s, "x-reventless-drillTargetKey"))), undefined);
    });
    Jest.test("emits x-reventless-collapsed on field listed in collapsed", () => {
      let schema = S.schema(s => ({
        id: s.m(S.string),
        primaryResource: s.m(S.string)
      }));
      let schema$p = withSpec(schema, {
        ids: emptySpec_ids,
        compositeIds: emptySpec_compositeIds,
        subIds: emptySpec_subIds,
        compositeSubIds: emptySpec_compositeSubIds,
        indexes: emptySpec_indexes,
        hidden: emptySpec_hidden,
        summary: emptySpec_summary,
        drillTargets: emptySpec_drillTargets,
        drillTargetKeys: emptySpec_drillTargetKeys,
        collapsed: ["primaryResource"]
      });
      let json = SuryToJsonSchema$ReventlessCore.deriveObjectSchema(schema$p);
      let primarySchema = getPropertyOf(json, "primaryResource");
      let idSchema = getPropertyOf(json, "id");
      return Jest.Expect.toEqual(Jest.Expect.expect([
        Stdlib_Option.flatMap(Stdlib_Option.flatMap(primarySchema, s => getProperty(s, "x-reventless-collapsed")), Stdlib_JSON.Decode.bool),
        Stdlib_Option.flatMap(idSchema, s => getProperty(s, "x-reventless-collapsed"))
      ]), [
        true,
        undefined
      ]);
    });
  });
});

export {
  getProperty,
  getPropertyOf,
  emptySpec,
}
/*  Not a pure module */
