// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var DynamoDb_Util$AwsSdk = require("../src/DynamoDb_Util.res.js");
var UtilDynamodb = require("@aws-sdk/util-dynamodb");

console.log("----MARSHALL----");

var r = DynamoDb_Util$AwsSdk.MarshallOptions.topLevelContainerConverted(undefined, undefined, undefined, true);

var test = UtilDynamodb.marshall({
      a: 42,
      b: true
    }, r);

console.log(test);

console.log("----UNMARSHALL----");

var num = {
  N: "42"
};

var bool = {
  BOOL: true
};

var dict = Js_dict.fromArray([
      [
        "a",
        num
      ],
      [
        "b",
        bool
      ]
    ]);

var result = DynamoDb_Util$AwsSdk.unmarshallDict(undefined, dict);

console.log(result);

var attrV_M = dict;

var attrV = {
  M: attrV_M
};

var result$1 = DynamoDb_Util$AwsSdk.unmarshall(undefined, attrV);

console.log(result$1);

var result$2 = DynamoDb_Util$AwsSdk.unmarshall(undefined, bool);

console.log(result$2);

exports.r = r;
exports.test = test;
exports.num = num;
exports.bool = bool;
exports.dict = dict;
exports.attrV = attrV;
exports.result = result$2;
/*  Not a pure module */
