// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as TestRunner$ReventlessInMemory from "../../../src/test/TestRunner.res.mjs";
import * as InMemory_Bus$ReventlessInMemory from "../../../src/adapter/InMemory_Bus.res.mjs";
import * as EventTopic_Builder$ReventlessCore from "@reventlessdev/reventless-core/src/components/EventTopic/EventTopic_Builder.res.mjs";
import * as EventTopicPublisher_InMemory$ReventlessInMemory from "../../../src/adapter/EventTopic/EventTopicPublisher_InMemory.res.mjs";

let eventSchema = S.union([
  S.schema(s => ({
    TAG: "ItemPublished",
    name: s.m(S.string)
  })),
  S.schema(s => ({
    TAG: "ItemRemoved",
    id: s.m(S.string)
  }))
]);

let ItemEventTopicSpec = {
  Id: undefined,
  name: "TestItemEventTopic",
  eventSchema: eventSchema
};

let Bus = InMemory_Bus$ReventlessInMemory.Make({});

let capturedEventCount = {
  contents: 0
};

Bus.subscribeToEvents("TestItemEventTopicEventTopic", async (param, param$1, param$2) => {
  capturedEventCount.contents = capturedEventCount.contents + 1 | 0;
});

TestRunner$ReventlessInMemory.setup();

let EventTopicMaker = EventTopic_Builder$ReventlessCore.Make({
  Id: {
    schema: Id$Reventless.StringPure.schema,
    make: prim => prim,
    makeFromString: prim => prim,
    toString: prim => prim,
    cmp: Id$Reventless.StringPure.cmp
  },
  eventSchema: eventSchema
})(EventTopicPublisher_InMemory$ReventlessInMemory.Make(Bus));

let eventTopic = EventTopicMaker.make("TestItemEventTopic", [], undefined);

let testMeta = {
  service: "test",
  time: "2024-01-01T00:00:00.000Z",
  ip: "127.0.0.1",
  user: "testuser",
  msgId: "msg-001",
  correlationId: "corr-001"
};

function makeEvent$p(id, event) {
  return {
    id: id,
    meta: testMeta,
    event: event
  };
}

function reset() {
  capturedEventCount.contents = 0;
}

export {
  ItemEventTopicSpec,
  Bus,
  capturedEventCount,
  EventTopicMaker,
  eventTopic,
  testMeta,
  makeEvent$p,
  reset,
}
/* eventSchema Not a pure module */
