// Generated by ReScript, PLEASE EDIT WITH CARE


let IdentityPool;

let IdentityPoolRoleAttachment;

let UserGroup;

let UserPool;

let UserPoolClient;

export {
  IdentityPool,
  IdentityPoolRoleAttachment,
  UserGroup,
  UserPool,
  UserPoolClient,
}
/* No side effect */
