// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Result from "@rescript/runtime/lib/es6/Stdlib_Result.js";
import * as CliArgs$Reventless from "@reventlessdev/reventless-spec/src/CliArgs.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as AccountsManifest$Reventless from "@reventlessdev/reventless-spec/src/types/AccountsManifest.res.mjs";
import * as Util_AwsError$ReventlessAws from "../src/util/Util_AwsError.res.mjs";
import * as ProvisionCognito$ReventlessAws from "./ProvisionCognito.res.mjs";
import * as ProvisionProvider$ReventlessAws from "./ProvisionProvider.res.mjs";

function parseArgs(argv) {
  return Stdlib_Result.map(Stdlib_Result.flatMap(CliArgs$Reventless.parse([
    "provider-id",
    "stack",
    "file"
  ], undefined, undefined, undefined, argv), CliArgs$Reventless.noPositionals), a => ({
    providerId: CliArgs$Reventless.string(a, "provider-id"),
    stack: CliArgs$Reventless.string(a, "stack"),
    file: CliArgs$Reventless.string(a, "file"),
    help: CliArgs$Reventless.help(a)
  }));
}

let usage = `
Usage: provision-accounts [--provider-id <id>] [--stack <name>] [--file <path>]

Turn a declared cast of accounts into working sign-ins.

  --provider-id <id>   The identity provider to create the accounts in. Usually
                       omitted: it falls back to ` + ProvisionProvider$ReventlessAws.envKey + `,
                       then to the identityProviderId exported by the selected
                       Pulumi stack — which every deployment exports, whether it
                       created the pool or was handed one.
  --stack <name>       Read that output from this stack instead of the selected
                       one. The run always names the stack it used.
  --file <path>        The manifest. Defaults to .reventless/users.yaml relative
                       to the working directory, which is where both platforms
                       keep it.

For every entry: ensures the groups it names, ensures the account, sets a
permanent password, and applies the memberships. Generated passwords and the ids
the pool mints are written back into the manifest, so the seed client can read
them without anyone retyping a UUID.

A password already in the manifest is never replaced. Region and credentials come
from the environment, as for any AWS SDK call.
`;

function looksLikeEmail(username) {
  if (username.includes("@")) {
    return username.includes(".");
  } else {
    return false;
  }
}

async function checkPoolAcceptsUsernames(providerId, usernames) {
  let e = await ProvisionCognito$ReventlessAws.usernameAttributes(providerId);
  if (e.TAG !== "Ok") {
    return e;
  }
  let attributes = e._0;
  let signsInOnEmail = attributes.includes("email");
  let unusable = signsInOnEmail ? usernames.filter(u => !looksLikeEmail(u)) : [];
  if (unusable.length === 0) {
    console.log(`pool     signs in on ` + (
      attributes.length === 0 ? "username" : attributes.join(", ")
    ));
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: `pool "` + providerId + `" signs in on ` + attributes.join(", ") + `, so ` + unusable.join(", ") + ` could never authenticate. The sign-in attribute is fixed at pool creation and no update can change it — either name these accounts by address in the manifest, or provision them in a pool that signs in on a username.`
    };
  }
}

function describe(outcome) {
  if (outcome === "Created") {
    return "created";
  } else {
    return "already present";
  }
}

async function ensureGroups(providerId, entries) {
  let named = [];
  entries.forEach(entry => {
    entry.groups.forEach(group => {
      if (!named.includes(group)) {
        named.push(group);
        return;
      }
    });
  });
  for (let index = 0, index_finish = named.length; index < index_finish; ++index) {
    let group = named[index];
    let outcome = await ProvisionCognito$ReventlessAws.ensureGroup(providerId, group, "Declared in a Reventless accounts manifest");
    console.log(`group    ` + group + ` (` + describe(outcome) + `)`);
  }
}

async function applyEntry(providerId, entry) {
  let attributes = looksLikeEmail(entry.username) ? [
      {
        Name: "email",
        Value: entry.username
      },
      {
        Name: "email_verified",
        Value: "true"
      }
    ] : [];
  let outcome = await ProvisionCognito$ReventlessAws.ensureUser(providerId, entry.username, attributes);
  console.log(`user     ` + entry.username + ` (` + describe(outcome) + `)`);
  await ProvisionCognito$ReventlessAws.setPassword(providerId, entry.username, entry.password);
  for (let index = 0, index_finish = entry.groups.length; index < index_finish; ++index) {
    let group = entry.groups[index];
    await ProvisionCognito$ReventlessAws.addToGroup(providerId, entry.username, group);
    console.log(`member   ` + entry.username + ` in ` + group);
  }
  return await ProvisionCognito$ReventlessAws.subOf(providerId, entry.username);
}

function manifestNote(file) {
  return `
🚨 Generated passwords were written into ` + file + `. They are not printed here
   because that file is where they are read from — by you and by \`pnpm run seed\`.
   It is gitignored on every platform; keep it that way. These are bootstrap
   credentials for a deployment, not secrets to reuse anywhere real.`;
}

async function provision(file, providerId, checkPoolOpt) {
  let checkPool = checkPoolOpt !== undefined ? checkPoolOpt : checkPoolAcceptsUsernames;
  let message = AccountsManifest$Reventless.parseFile(file);
  if (message.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: file + `: ` + message._0
    };
  }
  let declared = message._0;
  if (declared.length === 0) {
    return {
      TAG: "Error",
      _0: file + ` declares no accounts`
    };
  }
  let e = await checkPool(providerId, declared.map(e => e.username));
  if (e.TAG !== "Ok") {
    return e;
  }
  let message$1 = AccountsManifest$Reventless.prepare(file);
  if (message$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: file + `: ` + message$1._0
    };
  }
  let prepared = message$1._0;
  let generated = prepared.filter(p => p.passwordGenerated).length;
  console.log(`manifest ` + file + ` (` + prepared.length.toString() + ` accounts, ` + generated.toString() + ` password(s) generated)`);
  let entries = prepared.map(p => p.entry);
  await ensureGroups(providerId, entries);
  let fills = [];
  for (let index = 0, index_finish = entries.length; index < index_finish; ++index) {
    let entry = entries[index];
    let userId = await applyEntry(providerId, entry);
    fills.push({
      index: index,
      password: undefined,
      userId: userId
    });
  }
  let message$2 = AccountsManifest$Reventless.fillFile(file, fills);
  if (message$2.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: file + `: ` + message$2._0
    };
  }
  let corrected = message$2._0.filter(r => r.userIdWritten).length;
  console.log(`manifest ` + file + ` (` + corrected.toString() + ` id(s) written back)` + manifestNote(file));
  return {
    TAG: "Ok",
    _0: undefined
  };
}

async function run(args) {
  let e = AccountsManifest$Reventless.locate(args.file, undefined);
  if (e.TAG !== "Ok") {
    return e;
  }
  let located = e._0;
  let file = AccountsManifest$Reventless.pathOf(located);
  if (located.TAG !== "Declared") {
    console.log(`manifest ` + file + ` (new, copied from ` + located._1 + `)`);
  }
  let message = ProvisionProvider$ReventlessAws.resolve(args.providerId, args.stack);
  if (message.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: message._0 + `. To fill in the manifest without creating anything, run prepare-accounts`
    };
  }
  let match = message._0;
  let providerId = match[0];
  console.log(`provider ` + providerId + ` (from ` + ProvisionProvider$ReventlessAws.describe(match[1]) + `)`);
  return await provision(file, providerId, undefined);
}

let cli = {
  bin: "provision-accounts",
  usage: usage,
  parse: parseArgs
};

function main() {
  return CliArgs$Reventless.run(cli, undefined, undefined, async args => {
    let message;
    try {
      message = await run(args);
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      console.error(`provision-accounts: ` + Util_AwsError$ReventlessAws.describe(exn));
      process.exit(1);
      return;
    }
    if (message.TAG === "Ok") {
      return;
    }
    console.error(`provision-accounts: ` + message._0);
    process.exit(1);
  });
}

let Cognito;

let Manifest;

export {
  Cognito,
  Manifest,
  parseArgs,
  usage,
  looksLikeEmail,
  checkPoolAcceptsUsernames,
  describe,
  ensureGroups,
  applyEntry,
  manifestNote,
  provision,
  run,
  cli,
  main,
}
/* CliArgs-Reventless Not a pure module */
