// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var DocumentClient;

var DynamoDb;

var Util;

exports.DocumentClient = DocumentClient;
exports.DynamoDb = DynamoDb;
exports.Util = Util;
/* No side effect */
