// Generated by ReScript, PLEASE EDIT WITH CARE


function pluralize(n) {
  if (/[^aeiou]y$/i.test(n)) {
    return n.slice(0, n.length - 1 | 0) + "ies";
  } else if (n.endsWith("s")) {
    return n + "es";
  } else {
    return n + "s";
  }
}

function singularize(n) {
  if (n.endsWith("ies")) {
    return n.slice(0, n.length - 3 | 0) + "y";
  } else if (n.endsWith("ses") || n.endsWith("xes") || n.endsWith("zes") || n.endsWith("ches") || n.endsWith("shes")) {
    return n.slice(0, n.length - 2 | 0);
  } else if (n.endsWith("s")) {
    return n.slice(0, n.length - 1 | 0);
  } else {
    return n;
  }
}

function stripViewSuffix(n) {
  if (n.endsWith("View")) {
    return n.slice(0, n.length - 4 | 0);
  } else {
    return n;
  }
}

function aggregateMutationField(plugin, aggregate, command) {
  return plugin + `_` + aggregate + `_` + command;
}

function sliceMutationField(plugin, slice) {
  return plugin + `_` + slice;
}

function queryFieldNamesForReadModel(plugin, name, connectionSpecOpt) {
  let connectionSpec = connectionSpecOpt !== undefined ? connectionSpecOpt : true;
  let singular = singularize(name);
  let plural = pluralize(name);
  return {
    singleFieldName: plugin + `_` + singular,
    listFieldName: plugin + `_` + plural,
    returnTypeName: plugin + `_` + singular,
    pluralTypeName: plugin + `_` + plural,
    includeIdParam: true,
    connectionSpec: connectionSpec
  };
}

function queryFieldNamesForStateView(plugin, viewName, connectionSpecOpt) {
  let connectionSpec = connectionSpecOpt !== undefined ? connectionSpecOpt : true;
  let entity = stripViewSuffix(viewName);
  let singular = singularize(entity);
  let plural = pluralize(entity);
  return {
    singleFieldName: plugin + `_` + singular,
    listFieldName: plugin + `_` + plural,
    returnTypeName: plugin + `_` + singular,
    pluralTypeName: plugin + `_` + plural,
    includeIdParam: true,
    connectionSpec: connectionSpec
  };
}

function queryFieldNamesForSliceQueryDb(plugin, queryDbName, connectionSpecOpt) {
  let connectionSpec = connectionSpecOpt !== undefined ? connectionSpecOpt : true;
  return {
    singleFieldName: plugin + `_` + queryDbName,
    listFieldName: plugin + `_` + pluralize(queryDbName),
    returnTypeName: plugin + `_` + queryDbName,
    pluralTypeName: plugin + `_` + pluralize(queryDbName),
    includeIdParam: false,
    connectionSpec: connectionSpec
  };
}

function adminField(name) {
  return `Platform_` + name;
}

export {
  pluralize,
  singularize,
  stripViewSuffix,
  aggregateMutationField,
  sliceMutationField,
  queryFieldNamesForReadModel,
  queryFieldNamesForStateView,
  queryFieldNamesForSliceQueryDb,
  adminField,
}
/* No side effect */
