// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_String from "@rescript/runtime/lib/es6/Stdlib_String.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as GraphQL_Stitcher$ReventlessCore from "@reventlessdev/reventless-core/src/components/Api/GraphQL_Stitcher.res.mjs";

function injectAwsSubscribe(sdl, sources) {
  if (sources.length === 0) {
    return sdl;
  }
  let sourceByField = {};
  sources.forEach(source => {
    sourceByField[source.field] = source.mutations;
  });
  let blockStart = Stdlib_String.indexOfOpt(sdl, "type Subscription");
  if (blockStart === undefined) {
    return sdl;
  }
  let before = sdl.slice(0, blockStart);
  let rest = sdl.slice(blockStart);
  let closeIdx = Stdlib_String.indexOfOpt(rest, "}");
  if (closeIdx === undefined) {
    return sdl;
  }
  let block = rest.slice(0, closeIdx);
  let after = rest.slice(closeIdx);
  let decorated = block.split("\n").map(line => {
    let name = GraphQL_Stitcher$ReventlessCore.extractLeadingName(line);
    let name$1 = name.endsWith(":") ? name.slice(0, name.length - 1 | 0) : name;
    let mutations = sourceByField[name$1];
    if (mutations === undefined) {
      return line;
    }
    let list = mutations.map(m => `"` + m + `"`).join(", ");
    return line + `\n    @aws_subscribe(mutations: [` + list + `])`;
  }).join("\n");
  return before + decorated + after;
}

function formatCognitoGroupsDirective(groups) {
  let quoted = groups.map(g => `"` + g + `"`).join(", ");
  return `@aws_cognito_user_pools(cognito_groups: [` + quoted + `])`;
}

let cognitoOpenDirective = "@aws_cognito_user_pools";

function formatDualAuthDirective(groups) {
  let cognito = groups !== undefined ? formatCognitoGroupsDirective(groups) : cognitoOpenDirective;
  return cognito + ` @aws_iam`;
}

function injectAwsAuthAll(fragment, group, iamFieldNamesOpt) {
  let iamFieldNames = iamFieldNamesOpt !== undefined ? iamFieldNamesOpt : [];
  let parts = GraphQL_Stitcher$ReventlessCore.decode(fragment);
  let cognitoOnly = formatCognitoGroupsDirective([group]);
  let augmentedMutations = parts.mutations.map(field => {
    if (iamFieldNames.includes(GraphQL_Stitcher$ReventlessCore.extractLeadingName(field))) {
      return field + `\n    ` + formatDualAuthDirective([group]);
    } else {
      return field + `\n    ` + cognitoOnly;
    }
  });
  let augmentedQueries = parts.queries.map(field => {
    if (iamFieldNames.includes(GraphQL_Stitcher$ReventlessCore.extractLeadingName(field))) {
      return field + ` ` + formatDualAuthDirective([group]);
    } else {
      return field + ` ` + cognitoOnly;
    }
  });
  let augmentedSubscriptions = parts.subscriptions.map(field => field + `\n    ` + cognitoOnly);
  return GraphQL_Stitcher$ReventlessCore.encode({
    types: parts.types,
    mutations: augmentedMutations,
    queries: augmentedQueries,
    subscriptions: augmentedSubscriptions,
    subscriptionSources: parts.subscriptionSources
  });
}

let sharedIamTypeNames = [
  "PageInfo",
  "CommandAccepted",
  "CommandRejected",
  "CommandPending"
];

function stampSharedIamTypes(sdl) {
  return Stdlib_Array.reduce(sharedIamTypeNames, sdl, (acc, name) => acc.replace(`type ` + name + ` {`, `type ` + name + ` @aws_cognito_user_pools @aws_iam {`));
}

function stampUndirectivedFields(fragment) {
  let parts = GraphQL_Stitcher$ReventlessCore.decode(fragment);
  let stamp = field => {
    if (field.includes("@aws_")) {
      return field;
    } else {
      return field + `\n    ` + cognitoOpenDirective;
    }
  };
  return GraphQL_Stitcher$ReventlessCore.encode({
    types: parts.types,
    mutations: parts.mutations.map(stamp),
    queries: parts.queries.map(stamp),
    subscriptions: parts.subscriptions.map(stamp),
    subscriptionSources: parts.subscriptionSources
  });
}

function stampAllTypesCognito(sdl) {
  return sdl.split("\n").map(line => {
    if (!(line.startsWith("type ") && !line.includes("@aws_"))) {
      return line;
    }
    let i = Stdlib_String.indexOfOpt(line, "{");
    if (i !== undefined) {
      return line.slice(0, i) + cognitoOpenDirective + " " + line.slice(i, line.length);
    } else {
      return line;
    }
  }).join("\n");
}

let enforcedDirectives = [
  "@aws_cognito_user_pools",
  "@aws_iam"
];

function hasEnforcedDirective(s) {
  return enforcedDirectives.some(d => s.includes(d));
}

let rootOperationTypes = [
  "Query",
  "Mutation",
  "Subscription"
];

function typeDeclNameOf(line) {
  if (!line.startsWith("type ")) {
    return;
  }
  let rest = line.slice(5, line.length);
  let i = rest.search(/[\s{]/);
  if (i !== -1) {
    return rest.slice(0, i);
  } else {
    return rest;
  }
}

function fieldNameOf(line) {
  let groups = line.match(/^ {2}(\w+)/);
  if (!(groups == null)) {
    return Stdlib_Option.flatMap(groups[1], x => x);
  }
}

function stampUndirectivedRootFields(sdl) {
  let out = [];
  let currentRoot = {
    contents: undefined
  };
  let buffer = {
    contents: []
  };
  let flush = () => {
    let entry = buffer.contents;
    if (entry.length !== 0) {
      entry.forEach(l => {
        out.push(l);
      });
      if (!hasEnforcedDirective(entry.join("\n"))) {
        out.push(`    ` + cognitoOpenDirective);
      }
      buffer.contents = [];
      return;
    }
  };
  sdl.split("\n").forEach(line => {
    let name = typeDeclNameOf(line);
    if (name !== undefined) {
      flush();
      currentRoot.contents = rootOperationTypes.includes(name) ? name : undefined;
      out.push(line);
      return;
    }
    if (line.startsWith("}")) {
      flush();
      currentRoot.contents = undefined;
      out.push(line);
      return;
    }
    if (Stdlib_Option.isSome(currentRoot.contents)) {
      let match = fieldNameOf(line);
      if (match !== undefined) {
        flush();
        buffer.contents = [line];
      } else if (buffer.contents.length !== 0) {
        buffer.contents = buffer.contents.concat([line]);
      } else {
        out.push(line);
      }
      return;
    }
    out.push(line);
  });
  flush();
  return out.join("\n");
}

function assertGateable(sdl) {
  let bareFields = [];
  let bareTypes = [];
  let inertDirectives = [];
  let currentRoot = {
    contents: undefined
  };
  let pending = {
    contents: undefined
  };
  let flush = () => {
    let match = pending.contents;
    if (match !== undefined) {
      if (!hasEnforcedDirective(match[1])) {
        bareFields.push(match[0]);
      }
      pending.contents = undefined;
      return;
    }
  };
  sdl.split("\n").forEach(line => {
    if (line.includes("@aws_auth")) {
      inertDirectives.push(line.trim());
    }
    let name = typeDeclNameOf(line);
    if (name !== undefined) {
      flush();
      if (!hasEnforcedDirective(line)) {
        bareTypes.push(name);
      }
      currentRoot.contents = rootOperationTypes.includes(name) ? name : undefined;
      return;
    }
    if (line.startsWith("}")) {
      flush();
      currentRoot.contents = undefined;
      return;
    }
    if (!Stdlib_Option.isSome(currentRoot.contents)) {
      return;
    }
    let fieldName = fieldNameOf(line);
    if (fieldName !== undefined) {
      flush();
      pending.contents = [
        fieldName,
        line
      ];
      return;
    }
    let match = pending.contents;
    if (match !== undefined) {
      pending.contents = [
        match[0],
        match[1] + "\n" + line
      ];
      return;
    }
  });
  flush();
  let problems = [];
  if (inertDirectives.length !== 0) {
    problems.push(`  ` + inertDirectives.length.toString() + ` field(s) carry @aws_auth, which AppSync IGNORES on a\n  multi-auth API (this adapter always adds AWS_IAM as an additional provider).\n  They are gated by nothing. Emit @aws_cognito_user_pools(cognito_groups: [...])\n  instead — see AppSync_SdlDecorate.formatCognitoGroupsDirective.\n    ` + inertDirectives.slice(0, 8).join("\n    "));
  }
  if (bareFields.length !== 0) {
    problems.push(`  ` + bareFields.length.toString() + ` root field(s) carry no enforced auth directive, so they are\n  reachable by ANY authenticated Cognito caller:\n    ` + bareFields.join(", "));
  }
  if (bareTypes.length !== 0) {
    problems.push(`  ` + bareTypes.length.toString() + ` object type(s) carry no enforced auth directive:\n    ` + bareTypes.join(", "));
  }
  if (problems.length !== 0) {
    Stdlib_JsError.throwWithMessage(`Refusing to push an AppSync schema that cannot be gated.\n\n` + problems.join("\n\n") + `\n\nEvery field and type must carry @aws_cognito_user_pools (optionally with\ncognito_groups) and/or @aws_iam. The sweep in stampUndirectivedFields /\nstampAllTypesCognito should have covered this — a failure here means a schema\nreached assembly by a path that bypasses them.\nSee docs/plans/appsync-group-authorization-unenforced.md.`);
  }
  return sdl;
}

let canonicalTypeNames = [
  "PageInfo",
  "CommandAccepted",
  "CommandRejected",
  "CommandPending"
];

function stampCanonicalTypes(sdl) {
  return sdl.split("\n").map(line => {
    let isObjectDef = canonicalTypeNames.some(name => line.startsWith(`type ` + name + ` `));
    let isNodeDef = line.startsWith("interface Node ") || line.startsWith("interface Node{");
    let isUnionDef = line.startsWith("union CommandResult ") || line.startsWith("union CommandResult=");
    if (line.includes("@canonical")) {
      return line;
    }
    if (isObjectDef || isNodeDef) {
      let braceIdx = Stdlib_String.indexOfOpt(line, "{");
      if (braceIdx === undefined) {
        return line;
      }
      let head = line.slice(0, braceIdx).trimEnd();
      let tail = line.slice(braceIdx);
      return head + ` @canonical ` + tail;
    }
    if (!isUnionDef) {
      return line;
    }
    let eqIdx = Stdlib_String.indexOfOpt(line, "=");
    if (eqIdx === undefined) {
      return line;
    }
    let head$1 = line.slice(0, eqIdx).trimEnd();
    let tail$1 = line.slice(eqIdx);
    return head$1 + ` @canonical ` + tail$1;
  }).join("\n");
}

export {
  injectAwsSubscribe,
  formatCognitoGroupsDirective,
  cognitoOpenDirective,
  formatDualAuthDirective,
  injectAwsAuthAll,
  sharedIamTypeNames,
  stampSharedIamTypes,
  stampUndirectivedFields,
  stampAllTypesCognito,
  enforcedDirectives,
  hasEnforcedDirective,
  rootOperationTypes,
  typeDeclNameOf,
  fieldNameOf,
  stampUndirectivedRootFields,
  assertGateable,
  canonicalTypeNames,
  stampCanonicalTypes,
}
/* GraphQL_Stitcher-ReventlessCore Not a pure module */
