// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as Api$ReventlessInfra from "@reventlessdev/reventless-infra/src/components/Api.res.mjs";
import * as GeoPoint$Reventless from "@reventlessdev/reventless-spec/src/semantic/GeoPoint.res.mjs";

let commandSchema = Sury.union([
  Sury.$schema(s => ({
    TAG: "Register",
    email: s.m(Sury.string),
    address: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "UpdateEmail",
    email: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "UpdateAddress",
    address: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "SetAddressLocation",
    address: s.m(Sury.string),
    location: s.m(GeoPoint$Reventless.schema)
  })),
  Sury.$schema(s => ({
    TAG: "SetLocation",
    location: s.m(GeoPoint$Reventless.schema),
    resolvedFrom: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "MarkAddressUnresolvable",
    address: s.m(Sury.string),
    reason: s.m(Sury.string)
  })),
  Sury.literal("Deactivate"),
  Sury.literal("Reactivate")
]);

let eventSchema = Sury.union([
  Sury.$schema(s => ({
    TAG: "Registered",
    email: s.m(Sury.string),
    address: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "EmailUpdated",
    email: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "AddressUpdated",
    address: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "LocationSet",
    location: s.m(GeoPoint$Reventless.schema),
    resolvedFrom: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "AddressLocated",
    address: s.m(Sury.string),
    location: s.m(GeoPoint$Reventless.schema)
  })),
  Sury.$schema(s => ({
    TAG: "AddressUnresolvable",
    address: s.m(Sury.string),
    reason: s.m(Sury.string)
  })),
  Sury.literal("Deactivated"),
  Sury.literal("Reactivated")
]);

let errorSchema = Sury.union([
  Sury.literal("CustomerAlreadyRegistered"),
  Sury.literal("CustomerNotFound"),
  Sury.literal("CustomerAlreadyDeactivated")
]);

let commandSchema$1 = Api$ReventlessInfra.markNoApiVariants(commandSchema, [
  "SetLocation",
  "MarkAddressUnresolvable"
]);

let commandSchema$2 = Api$ReventlessInfra.markAllowedStates(commandSchema$1, [
  [
    "UpdateEmail",
    ["Active"]
  ],
  [
    "UpdateAddress",
    ["Active"]
  ],
  [
    "SetAddressLocation",
    ["Active"]
  ],
  [
    "Deactivate",
    ["Active"]
  ],
  [
    "Reactivate",
    ["Deactivated"]
  ]
]);

let commandSchema$3 = Api$ReventlessInfra.markTargetState(commandSchema$2, [
  [
    "Deactivate",
    "Deactivated"
  ],
  [
    "Reactivate",
    "Active"
  ]
]);

function commandAuthorization(param) {
  return "AllowAuthenticated";
}

let name = "Customer";

let Id;

let moduleUrl = "@reventlessdev/online-shop-hybrid-ordering/src/Customer/Aggregate/Customer.res.mjs";

export {
  name,
  Id,
  eventSchema,
  errorSchema,
  commandSchema$3 as commandSchema,
  moduleUrl,
  commandAuthorization,
}
/* commandSchema Not a pure module */
