// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as Api_Naming$ReventlessCore from "../../components/Api/Api_Naming.res.mjs";
import * as PluginSpec$ReventlessCore from "../lifecycle/PluginSpec.res.mjs";
import * as ApiNoApiHelpers$ReventlessCore from "../../components/Api/ApiNoApiHelpers.res.mjs";
import * as PluginsReadModelSpec$ReventlessCore from "../lifecycle/PluginsReadModelSpec.res.mjs";
import * as PluginHistoryReadModelSpec$ReventlessCore from "../lifecycle/PluginHistoryReadModelSpec.res.mjs";
import * as Platform_EventGraphReadModelSpec$ReventlessCore from "../../admin/Platform_EventGraphReadModelSpec.res.mjs";

let adminAuth = {
  tableName: "Plugin",
  group: "Admin"
};

let pluginExcludeFields = [
  "eventCollector",
  "extensionPointNames",
  "extensionNames"
];

let pluginUIOnlyExcludeFields = pluginExcludeFields.concat([
  "apiSchemaFragment",
  "uiFragments",
  "structure"
]);

function indexQueriesOfConfig(config) {
  if (config.indexes.length !== 0) {
    return config.indexes;
  }
}

let queryEntries = [
  {
    singleFieldName: Api_Naming$ReventlessCore.adminField("Plugin"),
    listFieldName: Api_Naming$ReventlessCore.adminField("Plugins"),
    returnTypeName: Api_Naming$ReventlessCore.adminField("Plugin"),
    stateSchema: PluginsReadModelSpec$ReventlessCore.stateSchema,
    specName: PluginsReadModelSpec$ReventlessCore.name,
    authorization: adminAuth,
    excludeFields: pluginExcludeFields,
    subIdField: Stdlib_Option.map(undefined, c => c.subIdField),
    indexQueries: indexQueriesOfConfig(PluginsReadModelSpec$ReventlessCore.config)
  },
  {
    singleFieldName: Api_Naming$ReventlessCore.adminField("PlatformEventGraph"),
    listFieldName: Api_Naming$ReventlessCore.adminField("PlatformEventGraphs"),
    returnTypeName: Api_Naming$ReventlessCore.adminField("PlatformEventGraph"),
    stateSchema: Platform_EventGraphReadModelSpec$ReventlessCore.stateSchema,
    specName: Platform_EventGraphReadModelSpec$ReventlessCore.name,
    authorization: adminAuth,
    excludeFields: [],
    subIdField: Stdlib_Option.map(undefined, c => c.subIdField),
    indexQueries: indexQueriesOfConfig(Platform_EventGraphReadModelSpec$ReventlessCore.config)
  },
  {
    singleFieldName: Api_Naming$ReventlessCore.adminField("PluginHistoryEntry"),
    listFieldName: Api_Naming$ReventlessCore.adminField("PluginHistory"),
    returnTypeName: Api_Naming$ReventlessCore.adminField("PluginHistoryEntry"),
    stateSchema: PluginHistoryReadModelSpec$ReventlessCore.stateSchema,
    specName: PluginHistoryReadModelSpec$ReventlessCore.name,
    authorization: adminAuth,
    excludeFields: [],
    subIdField: Stdlib_Option.map(PluginHistoryReadModelSpec$ReventlessCore.subIdConfig, c => c.subIdField),
    indexQueries: indexQueriesOfConfig(PluginHistoryReadModelSpec$ReventlessCore.config)
  }
];

let constructorNames = DcbTag$Reventless.extractAllVariantNames(PluginSpec$ReventlessCore.commandSchema);

let filteredConstructorNames = ApiNoApiHelpers$ReventlessCore.filterNoApiVariants(constructorNames, PluginSpec$ReventlessCore.commandSchema);

let fieldNames = filteredConstructorNames.map(cname => Api_Naming$ReventlessCore.adminField(PluginSpec$ReventlessCore.name + "_" + cname));

let pluginAggregateMutationEntries = fieldNames.length === 0 ? [] : [{
      fieldNames: fieldNames,
      commandSchema: PluginSpec$ReventlessCore.commandSchema
    }];

export {
  adminAuth,
  pluginExcludeFields,
  pluginUIOnlyExcludeFields,
  indexQueriesOfConfig,
  queryEntries,
  pluginAggregateMutationEntries,
}
/* pluginUIOnlyExcludeFields Not a pure module */
