// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var Aws = require("@pulumi/aws");
var Caml_option = require("@rescript/std/lib/js/caml_option.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var IAM$PulumiAws = require("@reventless/bs-pulumi-aws/src/IAM/IAM.res.js");
var Pulumi = require("@pulumi/pulumi");
var Lambda$PulumiAws = require("@reventless/bs-pulumi-aws/src/Lambda/Lambda.res.js");
var AWS$ReventlessAws = require("../AWS.res.js");
var Adapter$Reventless = require("@reventless/reventless/src/adapter/Adapter.res.js");
var AWS_Tags$ReventlessAws = require("../AWS_Tags.res.js");
var Util_Pulumi$Reventless = require("@reventless/reventless/src/util/Util_Pulumi.res.js");
var CommandTopic$Reventless = require("@reventless/reventless/src/components/CommandTopic/CommandTopic.res.js");
var Util_Lambda$ReventlessAws = require("../../util/Util_Lambda.res.js");
var Util_IAM_Role$ReventlessAws = require("../../util/Util_IAM_Role.res.js");

function make(name, handler, memorySizeOpt, timeoutOpt, opts) {
  var memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 1024;
  var timeout = timeoutOpt !== undefined ? timeoutOpt : 30;
  var opts$1 = Core__Option.map(opts, Util_Pulumi$Reventless.ComponentResourceOptions.toCustomResourceOptions);
  var lambdaRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name + "Role", Pulumi.output(AWS$ReventlessAws.Lambda.principal), opts$1);
  var lambda = handler.apply(function (handler) {
        return new (Aws.lambda.CallbackFunction)(name, Lambda$PulumiAws.CallbackFunction.Args.make(handler, lambdaRole, undefined, undefined, undefined, memorySize, timeout, undefined, undefined, undefined, AWS_Tags$ReventlessAws.make(name, CommandTopic$Reventless.componentType), undefined), opts$1 !== undefined ? Caml_option.valFromOption(opts$1) : undefined);
      });
  return {
          parts: {
            lambda: lambda,
            lambdaRole: lambdaRole
          },
          resources: [
            Adapter$Reventless.outputToResource(lambda.apply(function (lambda) {
                      return Util_Lambda$ReventlessAws.toResource(lambda);
                    })),
            Util_IAM_Role$ReventlessAws.toResource(lambdaRole)
          ]
        };
}

function groupBySource($$event) {
  var dict = {};
  $$event.Records.forEach(function (record) {
        var eventSourceArn = record.eventSourceARN;
        var currentEvent = Core__Option.getOr(Js_dict.get(dict, eventSourceArn), {
              Records: []
            });
        dict[eventSourceArn] = {
          Records: currentEvent.Records.concat([record])
        };
      });
  return dict;
}

exports.make = make;
exports.groupBySource = groupBySource;
/* @pulumi/aws Not a pure module */
