// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TaskBucket_S3$ReventlessAws from "../adapter/Task/TaskBucket_S3.res.mjs";
import * as Task_Builder$ReventlessCore from "@reventlessdev/reventless-core/src/components/Task/Task_Builder.res.mjs";
import * as RuntimeEnvironment_Lambda$ReventlessAws from "../adapter/Runtime/RuntimeEnvironment_Lambda.res.mjs";
import * as TaskRuntime_Builder_PerBucket$ReventlessCore from "@reventlessdev/reventless-core/src/adapter/Runtime/TaskRuntime_Builder_PerBucket.res.mjs";
import * as EventCollectorChannel_DynamoDbStream$ReventlessAws from "../adapter/EventCollector/EventCollectorChannel_DynamoDbStream.res.mjs";
import * as SideEffectHandler_PerSideEffectHandler$ReventlessAws from "./SideEffectHandler_PerSideEffectHandler.res.mjs";
import * as EventCollectorRuntime_Builder_PerEventCollector$ReventlessCore from "@reventlessdev/reventless-core/src/adapter/Runtime/EventCollectorRuntime_Builder_PerEventCollector.res.mjs";

let EventCollectorRuntimeBuilder = EventCollectorRuntime_Builder_PerEventCollector$ReventlessCore.Make({
  make: RuntimeEnvironment_Lambda$ReventlessAws.make,
  groupBySource: RuntimeEnvironment_Lambda$ReventlessAws.groupBySource,
  asEventHandler: prim => prim,
  logger: RuntimeEnvironment_Lambda$ReventlessAws.logger
})({
  make: EventCollectorChannel_DynamoDbStream$ReventlessAws.make,
  connect: EventCollectorChannel_DynamoDbStream$ReventlessAws.connect
});

let TaskRuntimeBuilder = TaskRuntime_Builder_PerBucket$ReventlessCore.Make({
  make: RuntimeEnvironment_Lambda$ReventlessAws.make,
  groupBySource: RuntimeEnvironment_Lambda$ReventlessAws.groupBySource,
  asEventHandler: prim => prim,
  logger: RuntimeEnvironment_Lambda$ReventlessAws.logger
})({
  connect: TaskBucket_S3$ReventlessAws.connect,
  makeHandler: TaskBucket_S3$ReventlessAws.makeHandler,
  make: TaskBucket_S3$ReventlessAws.make
});

function Make(Spec) {
  return Task_Builder$ReventlessCore.Make(Spec)({
    make: RuntimeEnvironment_Lambda$ReventlessAws.make,
    groupBySource: RuntimeEnvironment_Lambda$ReventlessAws.groupBySource,
    asEventHandler: prim => prim,
    logger: RuntimeEnvironment_Lambda$ReventlessAws.logger
  })({
    make: EventCollectorChannel_DynamoDbStream$ReventlessAws.make,
    connect: EventCollectorChannel_DynamoDbStream$ReventlessAws.connect
  })(EventCollectorRuntimeBuilder)(TaskRuntimeBuilder)({
    connect: TaskBucket_S3$ReventlessAws.connect,
    makeHandler: TaskBucket_S3$ReventlessAws.makeHandler,
    make: TaskBucket_S3$ReventlessAws.make
  })({
    make: SideEffectHandler_PerSideEffectHandler$ReventlessAws.make
  });
}

let EventCollectorChannel;

let RuntimeEnvironment;

let TaskBucket;

let SideEffectHandler;

export {
  EventCollectorChannel,
  RuntimeEnvironment,
  EventCollectorRuntimeBuilder,
  TaskBucket,
  TaskRuntimeBuilder,
  SideEffectHandler,
  Make,
}
/* EventCollectorRuntimeBuilder Not a pure module */
