// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as Order$OrderingPlugin from "../Aggregate/Order.res.mjs";
import * as EmailService$OrderingPlugin from "../../Service/EmailService.res.mjs";

let Source = {
  name: Order$OrderingPlugin.name,
  Id: undefined,
  eventSchema: Order$OrderingPlugin.eventSchema
};

async function execute(orderId, _meta, event, _queryEngine) {
  if (typeof event !== "object" || event.TAG !== "Placed") {
    return;
  } else {
    return await EmailService$OrderingPlugin.sendOrderConfirmation(event.customerId, Id$Reventless.$$String.toString(orderId));
  }
}

let name = "Order_EmailNotification";

let Id;

let moduleUrl = "@reventlessdev/online-shop-aggregates-ordering/src/Order/SideEffect/Order_EmailNotification.res.mjs";

export {
  name,
  Id,
  Source,
  execute,
  moduleUrl,
}
/* Id-Reventless Not a pure module */
