// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Logger$ReventlessCore from "../../src/util/Logger.res.mjs";

globalThis.describe("Logger.debugLazy", () => {
  globalThis.test("does NOT invoke the thunk at the default Info level", () => {
    let called = {
      contents: false
    };
    let log = Logger$ReventlessCore.makeLogger("Info");
    log.debugLazy("Test", () => {
      called.contents = true;
      return "should never be built";
    });
    globalThis.expect(called.contents).toEqual(false);
  });
  globalThis.test("invokes the thunk when debug output is enabled", () => {
    let called = {
      contents: false
    };
    let log = Logger$ReventlessCore.makeLogger("Debug");
    log.debugLazy("Test", () => {
      called.contents = true;
      return "built";
    });
    globalThis.expect(called.contents).toEqual(true);
  });
  globalThis.test("the silent logger never invokes the thunk", () => {
    let called = {
      contents: false
    };
    Logger$ReventlessCore.silent.debugLazy("Test", () => {
      called.contents = true;
      return "x";
    });
    globalThis.expect(called.contents).toEqual(false);
  });
});

/*  Not a pure module */
