// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var Component$Reventless = require("../Component.res.js");
var ComponentType$Reventless = require("../../ComponentType.res.js");
var EventCollector$Reventless = require("./EventCollector.res.js");

function Make(Channel) {
  var connect = function (eventTopics, resources, runtime, eventCollector) {
    var eventCollectorResource = Component$Reventless.toPulumiResource(eventCollector);
    var name = ComponentType$Reventless.name(Core__Option.getOr(eventCollectorResource.__name, "Unnamed"), EventCollector$Reventless.componentType);
    var opts_parent = eventCollectorResource;
    var opts = {
      parent: opts_parent
    };
    var channel = eventCollector.channel;
    channel.connect(name, eventTopics, channel, runtime, resources, opts);
  };
  var makeHandler = function (eventCollector, eventsHandler) {
    var channel = eventCollector.channel;
    return channel.handleChannelEvent(eventsHandler);
  };
  var make = function (name, eventTopics, opts) {
    return Component$Reventless.make(ComponentType$Reventless.toString(EventCollector$Reventless.componentType), name, (function (extra, extra$1) {
                  var opts_parent = Component$Reventless.toPulumiResource(extra);
                  var opts = {
                    parent: opts_parent
                  };
                  var name = ComponentType$Reventless.name(extra$1, EventCollector$Reventless.componentType);
                  var channel = Channel.make(name, eventTopics, opts);
                  extra.channel = channel;
                  Component$Reventless.setOperations(extra, channel.enqueueEvent.apply(function (enqueueEvent) {
                            return {
                                    enqueueEvent: enqueueEvent
                                  };
                          }));
                  return Component$Reventless.setOutputs(extra, {
                              name: name,
                              resources: channel.resources
                            });
                }), opts);
  };
  return {
          connect: connect,
          makeHandler: makeHandler,
          make: make
        };
}

exports.Make = Make;
/* Component-Reventless Not a pure module */
