// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var name = "QueryDbStorage";

var DynamoDb = 0;

var DynamoDbStream = 0;

var DynamoDb_Runtime = 0;

exports.name = name;
exports.DynamoDb = DynamoDb;
exports.DynamoDbStream = DynamoDbStream;
exports.DynamoDb_Runtime = DynamoDb_Runtime;
/* No side effect */
