// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JsExn from "@rescript/runtime/lib/es6/Stdlib_JsExn.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Nodechild_process from "node:child_process";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as D2Classes$ReventlessVscodeProtocol from "../src/D2Classes.res.mjs";
import * as DomainGraphD2$ReventlessVscodeProtocol from "../src/DomainGraphD2.res.mjs";

let errCode = (e => (e && typeof e.code === 'string') ? e.code : undefined);

let nodes = [
  {
    id: "Catalog_Category_Add",
    kind: "Command",
    label: "Add",
    plugin: "Catalog"
  },
  {
    id: "Catalog:Category",
    kind: "Aggregate",
    label: "Category",
    plugin: "Catalog"
  },
  {
    id: "Catalog.Added",
    kind: "Event",
    label: "Added",
    plugin: "Catalog"
  },
  {
    id: "Catalog:Categories",
    kind: "ReadModel",
    label: "Categories",
    plugin: "Catalog"
  }
];

let edges = [
  {
    from: "Catalog_Category_Add",
    to: "Catalog:Category",
    kind: "Handles"
  },
  {
    from: "Catalog:Category",
    to: "Catalog.Added",
    kind: "Emits"
  },
  {
    from: "Catalog.Added",
    to: "Catalog:Categories",
    kind: "Projects"
  }
];

function missingFrom(hay, needles) {
  return needles.filter(s => !hay.includes(s));
}

globalThis.describe("class mapping", () => {
  globalThis.test("node kinds map to D2 colour classes; unknown falls back to box", () => {
    globalThis.expect([
      DomainGraphD2$ReventlessVscodeProtocol.nodeClassOf("Aggregate"),
      DomainGraphD2$ReventlessVscodeProtocol.nodeClassOf("Event"),
      DomainGraphD2$ReventlessVscodeProtocol.nodeClassOf("ReadModel"),
      DomainGraphD2$ReventlessVscodeProtocol.nodeClassOf("ExternalSystem"),
      DomainGraphD2$ReventlessVscodeProtocol.nodeClassOf("Whatever")
    ]).toEqual([
      "aggregate",
      "msg-event",
      "read-model",
      "external-system",
      "box"
    ]);
  });
  globalThis.test("edge relations map to connection classes; cross-plugin mechanisms fall through", () => {
    globalThis.expect([
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("Handles"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("Emits"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("Projects"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("Feeds"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("Reads"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("TranslatesIn"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("TranslatesOut"),
      DomainGraphD2$ReventlessVscodeProtocol.edgeClassOf("Extension")
    ]).toEqual([
      "command-flow",
      "event-flow",
      "projection-flow",
      "event-flow",
      "dcb-read",
      "cross-plugin",
      "cross-plugin",
      "cross-plugin"
    ]);
  });
});

globalThis.describe("legend", () => {
  globalThis.test("covers node kinds + edge classes with swatches; box fallback is reference-only", () => {
    let entries = DomainGraphD2$ReventlessVscodeProtocol.legend();
    let keys = entries.map(e => e.key);
    globalThis.expect([
      keys.includes("Event"),
      keys.includes("dcb-read"),
      keys.includes("cross-plugin"),
      entries.every(e => {
        if (e.swatch.startsWith("#")) {
          return e.description !== "";
        } else {
          return false;
        }
      }),
      entries.some(e => {
        if (e.key === "box") {
          return !e.toggleable;
        } else {
          return false;
        }
      })
    ]).toEqual([
      true,
      true,
      true,
      true,
      true
    ]);
  });
  globalThis.test("presentKeys = node kinds ∪ edge classes in the view (deduped)", () => {
    let keys = DomainGraphD2$ReventlessVscodeProtocol.presentKeys(nodes, edges);
    globalThis.expect([
      keys.includes("Aggregate"),
      keys.includes("event-flow"),
      keys.includes("projection-flow"),
      keys.includes("dcb-read")
    ]).toEqual([
      true,
      true,
      true,
      false
    ]);
  });
  globalThis.test("applyLegendFilter drops hidden node kinds and dangling edges", () => {
    let v = DomainGraphD2$ReventlessVscodeProtocol.applyLegendFilter(nodes, edges, ["Event"]);
    globalThis.expect([
      v.nodes.some(n => n.kind === "Event"),
      v.edges.every(e => {
        if (e.to !== "Catalog.Added") {
          return e.from !== "Catalog.Added";
        } else {
          return false;
        }
      }),
      v.edges.some(e => e.kind === "Handles")
    ]).toEqual([
      false,
      true,
      true
    ]);
  });
  globalThis.test("applyLegendFilter drops a hidden edge class but keeps its endpoints", () => {
    let v = DomainGraphD2$ReventlessVscodeProtocol.applyLegendFilter(nodes, edges, ["projection-flow"]);
    globalThis.expect([
      v.edges.every(e => e.kind !== "Projects"),
      v.nodes.some(n => n.id === "Catalog:Categories")
    ]).toEqual([
      true,
      true
    ]);
  });
});

globalThis.describe("toD2", () => {
  globalThis.test("emits the class block + nodes grouped in per-plugin containers, classed edges", () => {
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
      "classes: {",
      `"Catalog"."Catalog:Category": "Category" { class: aggregate }`,
      `"Catalog"."Catalog.Added": "Added" { class: msg-event }`,
      `"Catalog"."Catalog_Category_Add" -> "Catalog"."Catalog:Category" { class: command-flow }`
    ])).toEqual([]);
  });
  globalThis.test("an empty graph still produces valid D2 (class block + placeholder)", () => {
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2([], [], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
      "classes: {",
      `empty: "No plugins loaded"`
    ])).toEqual([]);
  });
  globalThis.test("ids/labels with quotes are escaped", () => {
    globalThis.expect(DomainGraphD2$ReventlessVscodeProtocol.toD2([{
        id: `a"b`,
        kind: "Event",
        label: `l"l`,
        plugin: "p"
      }], [], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined).includes("\"a\\\"b\": \"l\\\"l\"")).toBe(true);
  });
  globalThis.test("an external-system node renders outside the plugin; its boundary edge carries a label", () => {
    let nodes = [
      {
        id: "Ordering:SendEmail",
        kind: "OutboundTranslationSlice",
        label: "SendEmail",
        plugin: "Ordering"
      },
      {
        id: "ext:EmailService",
        kind: "ExternalSystem",
        label: "EmailService",
        plugin: ""
      }
    ];
    let edges = [{
        from: "Ordering:SendEmail",
        to: "ext:EmailService",
        kind: "TranslatesOut",
        label: "Placed"
      }];
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
      `"ext:EmailService": "EmailService" { class: external-system`,
      `-> "ext:EmailService": "Placed" { class: cross-plugin`
    ])).toEqual([]);
  });
  globalThis.test("a `reads` edge renders the dcb-read class", () => {
    globalThis.expect(DomainGraphD2$ReventlessVscodeProtocol.toD2([
      {
        id: "Catalog.Added",
        kind: "Event",
        label: "Added",
        plugin: "Catalog"
      },
      {
        id: "Catalog:Reserve",
        kind: "StateChangeSlice",
        label: "Reserve",
        plugin: "Catalog"
      }
    ], [{
        from: "Catalog.Added",
        to: "Catalog:Reserve",
        kind: "Reads"
      }], undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined).includes(`"Catalog"."Catalog.Added" -> "Catalog"."Catalog:Reserve" { class: dcb-read }`)).toBe(true);
  });
  globalThis.test("allPlugins declares an empty container for an element-less plugin", () => {
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, [
      "Catalog",
      "Billing"
    ], undefined, undefined, undefined, undefined), [
      `"Billing": { }`,
      `"Catalog"."Catalog:Category"`
    ])).toEqual([]);
  });
  globalThis.test("allPlugins lets an otherwise-empty graph still show plugin boxes", () => {
    let d2 = DomainGraphD2$ReventlessVscodeProtocol.toD2([], [], undefined, undefined, undefined, [
      "Catalog",
      "Ordering"
    ], undefined, undefined, undefined, undefined);
    globalThis.expect([
      missingFrom(d2, [
        `"Catalog": { }`,
        `"Ordering": { }`
      ]),
      d2.includes("No plugins loaded")
    ]).toEqual([
      [],
      false
    ]);
  });
});

globalThis.describe("toD2 focus", () => {
  globalThis.test("thickens the focus node border, leaves others plain", () => {
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, "Catalog:Category", undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
      `"Catalog"."Catalog:Category": "Category" { class: aggregate; style.stroke-width: 4`,
      `"Catalog"."Catalog.Added": "Added" { class: msg-event }`
    ])).toEqual([]);
  });
  globalThis.test("highlights every edge touching the focus, leaves others plain", () => {
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, "Catalog:Category", undefined, undefined, undefined, undefined, undefined, undefined, undefined), [
      `"Catalog"."Catalog_Category_Add" -> "Catalog"."Catalog:Category" { class: command-flow; style.stroke-width: 3; style.animated: true }`,
      `-> "Catalog"."Catalog.Added" { class: event-flow; style.stroke-width: 3`,
      `"Catalog"."Catalog.Added" -> "Catalog"."Catalog:Categories" { class: projection-flow }`
    ])).toEqual([]);
  });
});

globalThis.describe("toD2 chapters", () => {
  globalThis.test("nests chaptered nodes in a chapter sub-container, leaves the rest in the plugin", () => {
    let chapters = [
      [
        "Catalog:Category",
        "Catalog Management"
      ],
      [
        "Catalog_Category_Add",
        "Catalog Management"
      ]
    ];
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, chapters, undefined, undefined, undefined, undefined, undefined, undefined), [
      `"Catalog"."Catalog Management": "Catalog Management" { class: chapter }`,
      `"Catalog"."Catalog Management"."Catalog:Category": "Category" { class: aggregate }`,
      `"Catalog"."Catalog Management"."Catalog_Category_Add" -> "Catalog"."Catalog Management"."Catalog:Category" { class: command-flow }`,
      `"Catalog"."Catalog:Categories": "Categories" { class: read-model }`
    ])).toEqual([]);
  });
  globalThis.test("with no chapters is unchanged (the chapter level is opt-in)", () => {
    globalThis.expect(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, [], undefined, undefined, undefined, undefined, undefined, undefined)).toEqual(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  });
});

globalThis.describe("toD2 slices", () => {
  globalThis.test("wraps a write-side node + its command/event in a slice box", () => {
    let slices = [
      [
        "Catalog:Category",
        "Catalog:Category::slice"
      ],
      [
        "Catalog_Category_Add",
        "Catalog:Category::slice"
      ],
      [
        "Catalog.Added",
        "Catalog:Category::slice"
      ]
    ];
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, slices, undefined, undefined, undefined), [
      `"Catalog"."Catalog:Category::slice": "" { class: write-side }`,
      `"Catalog"."Catalog:Category::slice"."Catalog:Category": "Category" { class: aggregate }`,
      `"Catalog"."Catalog:Category::slice"."Catalog_Category_Add" -> "Catalog"."Catalog:Category::slice"."Catalog:Category" { class: command-flow }`,
      `"Catalog"."Catalog:Categories": "Categories" { class: read-model }`
    ])).toEqual([]);
  });
  globalThis.test("nests a slice box inside its write-side's chapter", () => {
    let chapters = [
      [
        "Catalog:Category",
        "Catalog Management"
      ],
      [
        "Catalog_Category_Add",
        "Catalog Management"
      ]
    ];
    let slices = [
      [
        "Catalog:Category",
        "Catalog:Category::slice"
      ],
      [
        "Catalog_Category_Add",
        "Catalog:Category::slice"
      ]
    ];
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, chapters, undefined, undefined, slices, undefined, undefined, undefined), [
      `"Catalog"."Catalog Management"."Catalog:Category::slice": "" { class: write-side }`,
      `"Catalog"."Catalog Management"."Catalog:Category::slice"."Catalog:Category": "Category" { class: aggregate }`
    ])).toEqual([]);
  });
  globalThis.test("with no slices is unchanged (the slice level is opt-in)", () => {
    globalThis.expect(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, [], undefined, undefined, undefined)).toEqual(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  });
  globalThis.test("wraps a read-side node in a read-slice box (anchor only)", () => {
    let slices = [[
        "Catalog:Categories",
        "Catalog:Categories::read-slice"
      ]];
    let sliceClass = [[
        "Catalog:Categories::read-slice",
        "read-side"
      ]];
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, slices, sliceClass, undefined, undefined), [
      `"Catalog"."Catalog:Categories::read-slice": "" { class: read-side }`,
      `"Catalog"."Catalog:Categories::read-slice"."Catalog:Categories": "Categories" { class: read-model }`
    ])).toEqual([]);
  });
  globalThis.test("recolours a slice box by its board-status class", () => {
    let slices = [[
        "Catalog:Categories",
        "Catalog:Categories::read-slice"
      ]];
    let done = DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, slices, [[
        "Catalog:Categories::read-slice",
        "slice-done"
      ]], undefined, undefined);
    let prog = DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, slices, [[
        "Catalog:Categories::read-slice",
        "slice-inprogress"
      ]], undefined, undefined);
    globalThis.expect([
      done.includes(`"Catalog"."Catalog:Categories::read-slice": "" { class: slice-done }`),
      prog.includes(`"Catalog"."Catalog:Categories::read-slice": "" { class: slice-inprogress }`)
    ]).toEqual([
      true,
      true
    ]);
  });
  globalThis.test("defaults an un-classed slice box to write-side", () => {
    let slices = [[
        "Catalog:Category",
        "Catalog:Category::slice"
      ]];
    globalThis.expect(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, slices, undefined, undefined, undefined).includes(`"Catalog"."Catalog:Category::slice": "" { class: write-side }`)).toBe(true);
  });
});

globalThis.describe("toD2 drift overrides", () => {
  globalThis.test("nodeClass replaces the palette class; edgeClass overrides the connection", () => {
    globalThis.expect(missingFrom(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, [[
        "Catalog:Categories",
        "drift-removed"
      ]], [[
        "Catalog.Added",
        "Catalog:Categories",
        "drift-removed-flow"
      ]]), [
      `"Catalog"."Catalog:Categories": "Categories" { class: drift-removed }`,
      `"Catalog"."Catalog.Added" -> "Catalog"."Catalog:Categories" { class: drift-removed-flow }`,
      `"Catalog"."Catalog:Category": "Category" { class: aggregate }`
    ])).toEqual([]);
  });
  globalThis.test("with no overrides is unchanged (the override level is opt-in)", () => {
    globalThis.expect(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, [], [])).toEqual(DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined));
  });
  globalThis.test("the drift palette classes exist in the generated class block", () => {
    globalThis.expect(missingFrom(D2Classes$ReventlessVscodeProtocol.classes, [
      `"drift-added"`,
      `"drift-removed"`,
      `"drift-added-flow"`,
      `"drift-removed-flow"`
    ])).toEqual([]);
  });
});

globalThis.describe("toD2 plugin highlight", () => {
  globalThis.test("outlines the highlighted plugin's container; empty leaves it unchanged", () => {
    globalThis.expect([
      DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, "Catalog", undefined, undefined, undefined, undefined, undefined).includes(`"Catalog": { style.stroke-width: 4; style.bold: true }`),
      DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, "", undefined, undefined, undefined, undefined, undefined) === DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)
    ]).toEqual([
      true,
      true
    ]);
  });
});

globalThis.describe("d2 binary smoke", () => {
  globalThis.test("generated D2 (incl. focus highlight) compiles with the d2 binary (passes trivially when d2 absent)", () => {
    let svg;
    try {
      svg = Nodechild_process.execFileSync("d2", [
        "-",
        "-"
      ], {
        input: DomainGraphD2$ReventlessVscodeProtocol.toD2(nodes, edges, "Catalog:Category", undefined, undefined, undefined, undefined, undefined, undefined, undefined),
        encoding: "utf8"
      });
    } catch (raw_exn) {
      let exn = Primitive_exceptions.internalToException(raw_exn);
      let match = Stdlib_Option.flatMap(Stdlib_JsExn.fromException(exn), errCode);
      if (match !== undefined) {
        if (match === "ENOENT") {
          svg = undefined;
        } else {
          throw exn;
        }
      } else {
        throw exn;
      }
    }
    globalThis.expect(Stdlib_Option.mapOr(svg, true, s => s.includes("<svg"))).toBe(true);
  });
});

export {
  errCode,
  nodes,
  edges,
  missingFrom,
}
/*  Not a pure module */
