// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var PluginApi$Reventless = require("./PluginApi.bs.js");

var mutationsSchema = PluginApi$Reventless.mutationsSchema + "\n	clone(restoreDateTime: String): String!\n    @aws_auth(cognito_groups: [\"Admin\"])\n";

var graphQLSchema = "\n" + PluginApi$Reventless.typesSchema + "\n\ntype Query {\n" + PluginApi$Reventless.queriesSchema + "\n}\n\ntype Mutation {\n" + mutationsSchema + "\n}\n";

var typesSchema = PluginApi$Reventless.typesSchema;

var queriesSchema = PluginApi$Reventless.queriesSchema;

exports.typesSchema = typesSchema;
exports.queriesSchema = queriesSchema;
exports.mutationsSchema = mutationsSchema;
exports.graphQLSchema = graphQLSchema;
/* No side effect */
