// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Products_Projections$CatalogPlugin from "../../../src/Product/ReadModel/Products_Projections.res.mjs";
import * as MultiSourceProjection_GWT$ReventlessGwt from "@reventlessdev/reventless-gwt/src/MultiSourceProjection_GWT.res.mjs";

let include = MultiSourceProjection_GWT$ReventlessGwt.Make(Products_Projections$CatalogPlugin.ProductMapping);

let describe = include.describe;

let test = include.test;

let givenEvents = include.givenEvents;

let whenEvent = include.whenEvent;

let thenState = include.thenState;

describe("Products ReadModel ← Product", () => {
  test("Added sets initial read model state", undefined, () => thenState(whenEvent(givenEvents([]), {
    TAG: "Added",
    name: "Laptop",
    description: "A laptop",
    price: 999.99
  }), {
    name: "Laptop",
    description: "A laptop",
    price: 999.99
  }));
  test("NameUpdated updates the name", undefined, () => thenState(whenEvent(givenEvents([{
      TAG: "Added",
      name: "Laptop",
      description: "A laptop",
      price: 999.99
    }]), {
    TAG: "NameUpdated",
    name: "Gaming Laptop"
  }), {
    name: "Gaming Laptop",
    description: "A laptop",
    price: 999.99
  }));
  test("DescriptionUpdated updates the description", undefined, () => thenState(whenEvent(givenEvents([{
      TAG: "Added",
      name: "Laptop",
      description: "A laptop",
      price: 999.99
    }]), {
    TAG: "DescriptionUpdated",
    description: "A high-end laptop"
  }), {
    name: "Laptop",
    description: "A high-end laptop",
    price: 999.99
  }));
  test("PriceUpdated updates the price", undefined, () => thenState(whenEvent(givenEvents([{
      TAG: "Added",
      name: "Laptop",
      description: "A laptop",
      price: 999.99
    }]), {
    TAG: "PriceUpdated",
    price: 899.99
  }), {
    name: "Laptop",
    description: "A laptop",
    price: 899.99
  }));
});

let describeWithId = include.describeWithId;

let givenEventsWithTime = include.givenEventsWithTime;

let whenEvents = include.whenEvents;

let whenEventWithTime = include.whenEventWithTime;

let whenEventsWithTime = include.whenEventsWithTime;

let thenStates = include.thenStates;

let thenStatesWithId = include.thenStatesWithId;

let thenAllStates = include.thenAllStates;

let thenStateWithId = include.thenStateWithId;

let thenNoState = include.thenNoState;

let thenThrow = include.thenThrow;

let thenFail = include.thenFail;

export {
  describe,
  describeWithId,
  test,
  givenEvents,
  givenEventsWithTime,
  whenEvent,
  whenEvents,
  whenEventWithTime,
  whenEventsWithTime,
  thenStates,
  thenStatesWithId,
  thenAllStates,
  thenState,
  thenStateWithId,
  thenNoState,
  thenThrow,
  thenFail,
}
/* include Not a pure module */
