// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as Api$ReventlessInfra from "@reventlessdev/reventless-infra/src/components/Api.res.mjs";

let consumedEventSchema = Sury.union([
  Sury.literal("OrderPlaced"),
  Sury.literal("OrderShipped"),
  Sury.literal("OrderCancelled")
]);

let commandSchema = Sury.$schema(s => ({
  TAG: "ShipOrder",
  orderId: s.m(DcbTag$Reventless.string)
}));

let errorSchema = Sury.union([
  Sury.literal("OrderNotFound"),
  Sury.literal("OrderAlreadyCancelled")
]);

let eventSchema = Sury.$schema(s => ({
  TAG: "OrderShipped",
  orderId: s.m(DcbTag$Reventless.string)
}));

let commandSchema$1 = Api$ReventlessInfra.markAllowedStates(commandSchema, [[
    "ShipOrder",
    ["Placed"]
  ]]);

let commandSchema$2 = Api$ReventlessInfra.markTargetState(commandSchema$1, [[
    "ShipOrder",
    "Shipped"
  ]]);

function commandAuthorization(param) {
  return "AllowAuthenticated";
}

let name = "ShipOrder";

let Id;

let moduleUrl = "@reventlessdev/online-shop-dcb-ordering/src/Order/StateChangeSlice/ShipOrder.res.mjs";

let readConsistency = "EscalateOnRetry";

export {
  name,
  Id,
  consumedEventSchema,
  errorSchema,
  eventSchema,
  commandSchema$2 as commandSchema,
  moduleUrl,
  commandAuthorization,
  readConsistency,
}
/* consumedEventSchema Not a pure module */
