// Generated by ReScript, PLEASE EDIT WITH CARE


function resolveMemory(hints, $$default) {
  if (hints === undefined) {
    return $$default;
  }
  let m = hints.memorySize;
  if (m !== undefined) {
    return Math.max($$default, m);
  } else {
    return $$default;
  }
}

function resolveTimeout(hints, $$default) {
  if (hints === undefined) {
    return $$default;
  }
  let t = hints.timeout;
  if (t !== undefined) {
    return t;
  } else {
    return $$default;
  }
}

let empty = {
  memorySize: undefined,
  timeout: undefined
};

export {
  empty,
  resolveMemory,
  resolveTimeout,
}
/* No side effect */
