// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Nodecrypto from "node:crypto";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

let lower = "abcdefghijkmnopqrstuvwxyz";

let upper = "ABCDEFGHJKLMNPQRSTUVWXYZ";

let digits = "23456789";

let alphabet = lower + upper + digits;

function randomInts(count) {
  let hex = Nodecrypto.randomBytes(count).toString("hex");
  return Stdlib_Array.fromInitializer(count, i => Stdlib_Option.getOr(Stdlib_Int.fromString(hex.substring((i << 1), (i << 1) + 2 | 0), 16), 0));
}

function charAt(source, n) {
  return source.charAt(Primitive_int.mod_(n, source.length));
}

function generate() {
  let ints = randomInts(30);
  let chars = ints.slice(0, 24).map(n => charAt(alphabet, n));
  let third = 8;
  [
    lower,
    upper,
    digits
  ].forEach((classAlphabet, block) => {
    let position = (block * third | 0) + Primitive_int.mod_(ints[24 + block | 0], third) | 0;
    chars[position] = charAt(classAlphabet, ints[27 + block | 0]);
  });
  return chars.join("");
}

let length = 24;

export {
  lower,
  upper,
  digits,
  alphabet,
  length,
  randomInts,
  charAt,
  generate,
}
/* node:crypto Not a pure module */
