// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as LocalBus$ReventlessLocal from "../../../src/adapter/LocalBus.res.mjs";
import * as TestRunner$ReventlessLocal from "../../../src/test/TestRunner.res.mjs";
import * as Task_Builder$ReventlessLocal from "../../../src/components/Task_Builder.res.mjs";

S.enableJson();

TestRunner$ReventlessLocal.setup();

let Bus = LocalBus$ReventlessLocal.Make({});

let TaskBuilderWithBus = Task_Builder$ReventlessLocal.Make(Bus);

let moduleUrl = import.meta.url;

function setup(_queryEngine, _queryBucketName, _opts) {
  return {};
}

let NoBucketsSpec = {
  name: "NoBucketsTask",
  moduleUrl: moduleUrl,
  setup: setup
};

let capturedEvents = {
  contents: []
};

let moduleUrl$1 = import.meta.url;

function setup$1(_queryEngine, _queryBucketName, _opts) {
  return {
    buckets: [{
        bucketName: "Reports",
        bucketMode: "Read",
        callback: async (eventName, key) => {
          capturedEvents.contents = capturedEvents.contents.concat([[
              eventName,
              key
            ]]);
          return [];
        }
      }]
  };
}

let OneBucketSpec = {
  name: "OneBucketTask",
  moduleUrl: moduleUrl$1,
  setup: setup$1
};

let mockPublishToAggregates = {};

function mockQueryBucketName(param, param$1) {
  return "in-memory-bucket";
}

let NoBucketsMaker = TaskBuilderWithBus.Make(NoBucketsSpec);

let OneBucketMaker = TaskBuilderWithBus.Make(OneBucketSpec);

function resetCaptures() {
  capturedEvents.contents = [];
}

export {
  Bus,
  TaskBuilderWithBus,
  NoBucketsSpec,
  capturedEvents,
  OneBucketSpec,
  mockPublishToAggregates,
  mockQueryBucketName,
  NoBucketsMaker,
  OneBucketMaker,
  resetCaptures,
}
/*  Not a pure module */
