// Generated by ReScript, PLEASE EDIT WITH CARE

import * as GraphQL_Stitcher$ReventlessCore from "../../components/Api/GraphQL_Stitcher.res.mjs";
import * as PluginBaseFragment$ReventlessCore from "./PluginBaseFragment.res.mjs";

let parts = GraphQL_Stitcher$ReventlessCore.decode(PluginBaseFragment$ReventlessCore.fragment);

let allMutations = parts.mutations.concat([`  Core_Clone(restoreDateTime: String): String!`]);

let encoded = JSON.stringify(Object.fromEntries([
  [
    "types",
    parts.types.map(prim => prim)
  ],
  [
    "mutations",
    allMutations.map(prim => prim)
  ],
  [
    "queries",
    parts.queries.map(prim => prim)
  ]
]));

let baseFragment = {
  encoded: encoded,
  protocol: "graphql"
};

export {
  baseFragment,
}
/* parts Not a pure module */
