// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var SQS$AwsSdk = require("@reventless/bs-aws-sdk/src/SQS.res.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var Logger$Reventless = require("../../util/Logger.res.js");
var Message$Reventless = require("../../Message.res.js");
var Util_Promise$Reventless = require("../../util/Util_Promise.res.js");

function Make(Spec) {
  var handleEvent = async function (eventJson$p, eventHandlersByService) {
    return await Core__Option.mapOr(Core__Option.flatMap(Message$Reventless.serviceNameOfMsg(eventJson$p), (function (serviceName) {
                      return Js_dict.get(eventHandlersByService, serviceName);
                    })), Promise.resolve(), (async function (eventHandlers) {
                  return await Util_Promise$Reventless.toUnit(Promise.all(eventHandlers.map(function (eventHandler) {
                                      return eventHandler(eventJson$p, Spec.pluginDefinition);
                                    })));
                }));
  };
  var detectUnhandledEvent = function (eventJson$p) {
    Core__Option.mapOr(Message$Reventless.serviceNameOfMsg(eventJson$p), undefined, (function (serviceName) {
            var match = Js_dict.get(Spec.outgoingExtensionPointEventHandlers, serviceName);
            var match$1 = Js_dict.get(Spec.outgoingExtensionEventHandlers, serviceName);
            var match$2 = Js_dict.get(Spec.incomingExtensionEventHandlers, serviceName);
            if (match !== undefined || match$1 !== undefined || match$2 !== undefined) {
              return ;
            } else {
              console.log("No mapping matches service name");
              return ;
            }
          }));
  };
  var handleJsonEvents = function (eventsJson) {
    var id = Spec.pluginDefinition.id;
    var count = eventsJson.length;
    return Util_Promise$Reventless.toUnit(Promise.all(eventsJson.map(async function (eventJson$p, idx) {
                        var idx$1 = idx + 1 | 0;
                        Logger$Reventless.logJsonEvent(undefined, undefined, eventJson$p, "Plugin " + id + " handleJsonEvents: incoming event " + String(idx$1) + "/" + String(count) + ":");
                        detectUnhandledEvent(eventJson$p);
                        await handleEvent(eventJson$p, Spec.incomingConnectExtensionEventHandlers);
                        return Promise.all([
                                    handleEvent(eventJson$p, Spec.outgoingExtensionPointEventHandlers),
                                    handleEvent(eventJson$p, Spec.outgoingExtensionEventHandlers),
                                    handleEvent(eventJson$p, Spec.incomingExtensionEventHandlers)
                                  ]);
                      })));
  };
  return {
          handleJsonEvents: handleJsonEvents
        };
}

function addStatement(policy, sid, queueArn, topicArn) {
  var newStatements = policy.Statement.filter(function (statement) {
          return statement.Sid !== sid;
        }).concat([{
          Sid: sid,
          Effect: "Allow",
          Principal: "*",
          Action: "sqs:SendMessage",
          Resource: queueArn,
          Condition: {
            ArnEquals: topicArn
          }
        }]);
  console.log("addStatement: adding 1 statement with Sid " + sid);
  return {
          Version: policy.Version,
          Id: policy.Id,
          Statement: newStatements
        };
}

function removeStatement(policy, sid) {
  var statements = policy.Statement;
  var newStatements = statements.filter(function (statement) {
        return statement.Sid !== sid;
      });
  var removedStatements = statements.length - newStatements.length | 0;
  console.log("removeStatement: removing " + String(removedStatements) + " statement(s) with Sid " + sid);
  return {
          Version: policy.Version,
          Id: policy.Id,
          Statement: newStatements
        };
}

async function _addPermission(sid, eventCollector, eventTopic) {
  var policy = await SQS$AwsSdk.getQueuePolicy(eventCollector);
  return SQS$AwsSdk.setQueuePolicy(eventCollector, addStatement(policy, sid, eventCollector, eventTopic));
}

async function _removePermission(sid, eventCollector) {
  var policy = await SQS$AwsSdk.getQueuePolicy(eventCollector);
  return SQS$AwsSdk.setQueuePolicy(eventCollector, removeStatement(policy, sid));
}

exports.Make = Make;
exports.addStatement = addStatement;
exports.removeStatement = removeStatement;
exports._addPermission = _addPermission;
exports._removePermission = _removePermission;
/* SQS-AwsSdk Not a pure module */
