// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Effect from "effect";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";
import * as Message$ReventlessCore from "../../Message.res.mjs";

function Make(Spec) {
  return Ops => {
    let name = Ops.name;
    let encodeEvent = event => {
      let json = S.reverseConvertToJsonOrThrow(event, Spec.eventSchema);
      let match = Message$ReventlessCore.splitMessage(json);
      let tags = DcbTag$Reventless.extractTags(Spec.eventSchema, event);
      return {
        eventType: match[0],
        data: match[1],
        tags: tags
      };
    };
    let decodeEvent = raw => {
      let json = Message$ReventlessCore.combineMessage(raw.eventType, Stdlib_Option.getOr(Stdlib_JSON.Decode.object(raw.data), {}));
      let event = S.parseJsonOrThrow(json, Spec.eventSchema);
      return {
        position: raw.position,
        event: event,
        tags: raw.tags
      };
    };
    let publishToEventTopic = async events => {
      await Promise.all(events.map(async event => {
        let json = S.reverseConvertToJsonOrThrow(event, Spec.eventSchema);
        let meta = Message$ReventlessCore.generateMeta(name, undefined, undefined);
        try {
          return await Ops.publishJson(name, meta, json);
        } catch (raw_err) {
          let err = Primitive_exceptions.internalToException(raw_err);
          if (err.RE_EXN_ID === "JsExn") {
            console.log(`DcbEventLog(` + name + `): EventTopic.publish Error:`, err._1);
            return;
          }
          throw err;
        }
      }));
    };
    let append = async (events, condition) => {
      let rawEvents = events.map(encodeEvent);
      let result = await Ops.storage.append(rawEvents, condition);
      if (result.TAG !== "Ok") {
        return result;
      }
      await publishToEventTopic(events);
      return {
        TAG: "Ok",
        _0: result._0
      };
    };
    let read = async (query, after) => {
      let rawResult = await Ops.storage.read(query, after);
      let events = rawResult.events.map(decodeEvent);
      return {
        events: events,
        headPosition: rawResult.headPosition
      };
    };
    let readStream = (query, after) => Effect.Stream.map(Ops.storage.readStream(query, after), decodeEvent);
    return {
      Spec: Spec,
      read: read,
      append: append,
      readStream: readStream
    };
  };
}

export {
  Make,
}
/* S Not a pure module */
