// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as Pulumi from "@pulumi/pulumi";
import * as Component$ReventlessCore from "../Component.res.mjs";
import * as DcbEventLog$ReventlessCore from "./DcbEventLog.res.mjs";
import * as Util_Pulumi$ReventlessCore from "../../util/Util_Pulumi.res.mjs";
import * as ComponentType$ReventlessCore from "../../ComponentType.res.mjs";
import * as EventTopic_Builder$ReventlessCore from "../EventTopic/EventTopic_Builder.res.mjs";
import * as DcbEventLog_Operations$ReventlessCore from "./DcbEventLog_Operations.res.mjs";

function Make(Storage) {
  return EventTopicPublisher => {
    let make = (name, indexesOpt, partitionTag, opts) => {
      let indexes = indexesOpt !== undefined ? indexesOpt : [];
      return Component$ReventlessCore.make(ComponentType$ReventlessCore.toString(DcbEventLog$ReventlessCore.componentType), name, (extra, extra$1) => {
        let opts_parent = Component$ReventlessCore.toPulumiResource(extra);
        let opts = {
          parent: opts_parent
        };
        let storage = Storage.make(ComponentType$ReventlessCore.name(extra$1, DcbEventLog$ReventlessCore.componentType), indexes, partitionTag, opts);
        let SpecificEventTopic = EventTopic_Builder$ReventlessCore.Make({
          Id: Id$Reventless.$$String,
          name: "DcbEventLog",
          eventSchema: S.json
        })(EventTopicPublisher);
        let eventTopic = SpecificEventTopic.make(extra$1, storage.resources, Util_Pulumi$ReventlessCore.ComponentResourceOptions.ofCustomResourceOptions(opts));
        Component$ReventlessCore.setOperations(extra, Pulumi.all([
          storage.operations,
          Component$ReventlessCore.operations(eventTopic)
        ]).apply(param => {
          let publishJson = param[1].publishJson;
          let Ops = DcbEventLog_Operations$ReventlessCore.Make({
            name: extra$1,
            storage: param[0],
            publishJson: publishJson
          });
          return {
            read: Ops.read,
            append: Ops.append,
            readStream: Ops.readStream,
            appendStream: Ops.appendStream
          };
        }));
        let outputs_resources = storage.resources;
        let outputs_eventTopic = Component$ReventlessCore.outputs(eventTopic);
        let outputs = {
          resources: outputs_resources,
          eventTopic: outputs_eventTopic
        };
        return Component$ReventlessCore.setOutputs(extra, outputs);
      }, opts);
    };
    return {
      make: make
    };
  };
}

export {
  Make,
}
/* S Not a pure module */
