// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";

let eventSchema = S.union([
  S.schema(s => ({
    TAG: "OrderPlaced",
    orderId: s.m(DcbTag$Reventless.string),
    address: s.m(S.string)
  })),
  S.schema(s => ({
    TAG: "ShipmentCreated",
    orderId: s.m(DcbTag$Reventless.string)
  }))
]);

let OrderEventLog = {
  eventSchema: eventSchema
};

let todoItemSchema = S.schema(s => ({
  orderId: s.m(S.string),
  address: s.m(S.string)
}));

let commandSchema = S.schema(s => ({
  TAG: "CreateShipment",
  orderId: s.m(DcbTag$Reventless.string)
}));

function collect(event) {
  if (event.TAG !== "OrderPlaced") {
    return [];
  }
  let orderId = event.orderId;
  return [[
      orderId,
      {
        orderId: orderId,
        address: event.address
      }
    ]];
}

function resolve(event) {
  if (event.TAG === "OrderPlaced") {
    return;
  } else {
    return event.orderId;
  }
}

function process(id, _item) {
  return [
    id,
    {
      TAG: "CreateShipment",
      orderId: id
    }
  ];
}

let ShipOrderSpec = {
  name: "ShipOrder",
  DcbEventLogSpec: undefined,
  todoItemSchema: todoItemSchema,
  commandSchema: commandSchema,
  collect: collect,
  resolve: resolve,
  process: process,
  maxRetries: 3,
  heartbeatInterval: 60
};

let todoItemSchema$1 = S.schema(s => ({
  orderId: s.m(S.string)
}));

let commandSchema$1 = S.literal("Noop");

function collect$1(event) {
  if (event.TAG !== "OrderPlaced") {
    return [];
  }
  let orderId = event.orderId;
  return [[
      orderId,
      {
        orderId: orderId
      }
    ]];
}

function resolve$1(event) {
  if (event.TAG === "OrderPlaced") {
    return;
  } else {
    return event.orderId;
  }
}

function process$1(_id, _item) {
  
}

let SkipProcessSpec = {
  name: "SkipProcess",
  DcbEventLogSpec: undefined,
  todoItemSchema: todoItemSchema$1,
  commandSchema: commandSchema$1,
  collect: collect$1,
  resolve: resolve$1,
  process: process$1,
  maxRetries: 0,
  heartbeatInterval: 60
};

export {
  OrderEventLog,
  ShipOrderSpec,
  SkipProcessSpec,
}
/* eventSchema Not a pure module */
