// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Aws from "@pulumi/aws";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as EC2_Common$PulumiAws from "./EC2_Common.res.mjs";

function make(name, args, opts) {
  return new (Aws.ec2.Vpc)(name, {
    cidrBlock: args.cidrBlock,
    enableDnsHostnames: args.enableDnsHostnames,
    tags: EC2_Common$PulumiAws.supplementTagsWithName(args.tags, name)
  }, opts !== undefined ? Primitive_option.valFromOption(opts) : undefined);
}

export {
  make,
}
/* @pulumi/aws Not a pure module */
