// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var S = require("sury/src/S.res.js");
var ComponentType$Reventless = require("../../ComponentType.res.js");

var counterEventSchema = S.literal("CountFinished");

var name = ComponentType$Reventless.toName("Counter");

var Source = {
  Id: undefined,
  name: name,
  eventSchema: counterEventSchema
};

var separator = "#";

function makeId(param) {
  return param[0] + (separator + param[1]);
}

function unmakeId(id) {
  var x = id.split(separator);
  var len = x.length;
  if (len !== 1) {
    if (len !== 0) {
      return [
              x[0],
              x[1]
            ];
    } else {
      return [
              "",
              ""
            ];
    }
  }
  var counterId = x[0];
  return [
          counterId,
          ""
        ];
}

var componentType = "Counter";

exports.componentType = componentType;
exports.counterEventSchema = counterEventSchema;
exports.Source = Source;
exports.separator = separator;
exports.makeId = makeId;
exports.unmakeId = unmakeId;
/* counterEventSchema Not a pure module */
