// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Effect from "@reventlessdev/rescript-effect/src/Effect.res.mjs";
import * as Stream from "@reventlessdev/rescript-effect/src/Stream.res.mjs";
import * as Effect$1 from "effect";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Math from "@rescript/runtime/lib/es6/Stdlib_Math.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as LibDynamodb from "@aws-sdk/lib-dynamodb";
import * as Message$ReventlessCore from "@reventlessdev/reventless-core/src/Message.res.mjs";
import * as Util_Error$ReventlessCore from "@reventlessdev/reventless-core/src/util/Util_Error.res.mjs";
import * as DynamoDb_DocumentClient$AwsSdk from "@reventlessdev/rescript-aws-sdk/src/DynamoDb_DocumentClient.res.mjs";

function put(table, item) {
  return DynamoDb_DocumentClient$AwsSdk.PutCommand.send(new LibDynamodb.PutCommand({
    Item: item,
    TableName: table.name
  }));
}

function putWithRetries(maxRetriesOpt, table, id, item) {
  let maxRetries = maxRetriesOpt !== undefined ? maxRetriesOpt : 5;
  let attempt = retry => Effect$1.Effect.catchAll(Effect$1.Effect.map(Effect.tryPromise(err => Util_Error$ReventlessCore.messageFromUnknown(err, "put"), () => put(table, item)), param => ({
    TAG: "Ok",
    _0: undefined
  })), errorMsg => Effect$1.Effect.flatMap(Effect$1.Effect.logInfo("Util_DynamoDb_Runtime-ReventlessAws" + (`.putWithRetries: id=` + id + `: retry ` + retry.toString() + ` failed: ` + errorMsg)), () => {
    if (retry >= maxRetries) {
      return Effect$1.Effect.succeed({
        TAG: "Error",
        _0: `put id=` + id + ` failed after ` + maxRetries.toString() + ` retries`
      });
    }
    let timeout = Stdlib_Math.Int.random(500, 1500);
    return Effect$1.Effect.flatMap(Effect$1.Effect.tap(Effect$1.Effect.sleep(Effect$1.Duration.millis(timeout)), () => Effect$1.Effect.logInfo(`Retry put after ` + timeout.toString() + ` ms`)), () => attempt(retry + 1 | 0));
  }));
  return attempt(0);
}

function putIfNotExistsWithRetries(maxRetriesOpt, idKey, sortKey, table, id, item) {
  let maxRetries = maxRetriesOpt !== undefined ? maxRetriesOpt : 5;
  let attempt = retry => Effect$1.Effect.catchAll(Effect$1.Effect.map(Effect.tryPromise(err => err, () => DynamoDb_DocumentClient$AwsSdk.putIfNotExists(table.name, idKey, sortKey, item)), param => ({
    TAG: "Ok",
    _0: undefined
  })), jsErr => {
    let match = DynamoDb_DocumentClient$AwsSdk.PutError.classify(jsErr);
    if (match.TAG === "ConditionCheckFailedException") {
      return Effect$1.Effect.succeed({
        TAG: "Error",
        _0: `Stale State: id=` + id
      });
    }
    let errorMsg = Util_Error$ReventlessCore.message(undefined, jsErr);
    return Effect$1.Effect.flatMap(Effect$1.Effect.logInfo("Util_DynamoDb_Runtime-ReventlessAws" + (`.putIfNotExistsWithRetries: id=` + id + `: retry ` + retry.toString() + ` failed: ` + errorMsg)), () => {
      if (retry >= maxRetries) {
        return Effect$1.Effect.succeed({
          TAG: "Error",
          _0: `putIfNotExists id=` + id + ` failed after ` + maxRetries.toString() + ` retries`
        });
      }
      let timeout = Stdlib_Math.Int.random(500, 1500);
      return Effect$1.Effect.flatMap(Effect$1.Effect.tap(Effect$1.Effect.sleep(Effect$1.Duration.millis(timeout)), () => Effect$1.Effect.logInfo(`Retry putIfNotExists after ` + timeout.toString() + ` ms`)), () => attempt(retry + 1 | 0));
    });
  });
  return attempt(0);
}

function $$delete(table, sort, id) {
  return DynamoDb_DocumentClient$AwsSdk.$$delete(sort, table.name, id);
}

function deleteWithRetries(maxRetriesOpt, sort, table, id) {
  let maxRetries = maxRetriesOpt !== undefined ? maxRetriesOpt : 5;
  let attempt = retry => Effect$1.Effect.catchAll(Effect$1.Effect.map(Effect.tryPromise(err => Util_Error$ReventlessCore.messageFromUnknown(err, "delete"), () => $$delete(table, sort, id)), param => ({
    TAG: "Ok",
    _0: undefined
  })), errorMsg => Effect$1.Effect.flatMap(Effect$1.Effect.logInfo("Util_DynamoDb_Runtime-ReventlessAws" + (`.delete: id=` + id + `: retry ` + retry.toString() + ` failed: ` + errorMsg)), () => {
    if (retry >= maxRetries) {
      return Effect$1.Effect.succeed({
        TAG: "Error",
        _0: `delete id=` + id + ` failed after ` + maxRetries.toString() + ` retries`
      });
    }
    let timeout = Stdlib_Math.Int.random(500, 1500);
    return Effect$1.Effect.flatMap(Effect$1.Effect.tap(Effect$1.Effect.sleep(Effect$1.Duration.millis(timeout)), () => Effect$1.Effect.logInfo(`Retry delete after ` + timeout.toString() + ` ms`)), () => attempt(retry + 1 | 0));
  }));
  return attempt(0);
}

function queryStream(params) {
  return Stream.paginateEffect(undefined, cursor => Effect$1.Effect.map(Effect.tryPromise(err => Util_Error$ReventlessCore.messageFromUnknown(err, "queryStream error"), () => {
    let p;
    if (cursor !== undefined) {
      let newrecord = {...params};
      newrecord.ExclusiveStartKey = cursor;
      p = newrecord;
    } else {
      p = params;
    }
    return DynamoDb_DocumentClient$AwsSdk.QueryCommand.send(new LibDynamodb.QueryCommand(p));
  }), res => [
    Stdlib_Option.getOr(res.Items, []),
    Stdlib_Option.map(res.LastEvaluatedKey, key => key)
  ]));
}

function scanStream(params) {
  return Stream.paginateEffect(undefined, cursor => Effect$1.Effect.map(Effect.tryPromise(err => Util_Error$ReventlessCore.messageFromUnknown(err, "scanStream error"), () => {
    let p;
    if (cursor !== undefined) {
      let newrecord = {...params};
      newrecord.ExclusiveStartKey = cursor;
      p = newrecord;
    } else {
      p = params;
    }
    return DynamoDb_DocumentClient$AwsSdk.ScanCommand.send(new LibDynamodb.ScanCommand(p));
  }), res => [
    Stdlib_Option.getOr(res.Items, []),
    Stdlib_Option.map(res.LastEvaluatedKey, key => key)
  ]));
}

function queryById(table, id) {
  return queryStream({
    TableName: table.name,
    ConsistentRead: true,
    ExpressionAttributeValues: Object.fromEntries([[
        ":id",
        id
      ]]),
    KeyConditionExpression: "id=:id"
  });
}

function keysFromResource(resource) {
  let parts = resource.info.get().split(",");
  let len = parts.length;
  if (len < 3) {
    switch (len) {
      case 0 :
        return Stdlib_JsError.throwWithMessage("No id field given for table " + resource.name.get());
      case 1 :
        let id = parts[0];
        return [
          id,
          undefined
        ];
      case 2 :
        let id$1 = parts[0];
        let match = parts[1];
        if (match === "") {
          return [
            id$1,
            undefined
          ];
        }
        break;
    }
  }
  return [
    parts[0],
    parts[1]
  ];
}

let purgeTimeAttributeName = "reventlessPurgeTime";

function calcPurgeTime(ttl) {
  let now_ms = Message$ReventlessCore.now();
  let now_s = now_ms / 1000.0;
  let now_s_rounded = now_s | 0;
  return now_s_rounded + ttl | 0;
}

function insertTtl(json, ttl) {
  if (ttl === undefined) {
    return json;
  }
  let obj = Stdlib_JSON.Decode.object(json);
  if (obj !== undefined) {
    obj[purgeTimeAttributeName] = calcPurgeTime(ttl);
    return obj;
  } else {
    return json;
  }
}

function batchWrite(itemRequestMap) {
  return DynamoDb_DocumentClient$AwsSdk.BatchWriteCommand.send(new LibDynamodb.BatchWriteCommand({
    RequestItems: itemRequestMap,
    ReturnConsumedCapacity: "NONE",
    ReturnItemCollectionMetrics: "NONE"
  }));
}

function hasUnprocessedItems(writeOutput) {
  return Stdlib_Option.mapOr(writeOutput.UnprocessedItems, 0, items => Object.keys(items).length) > 0;
}

function batchWriteWithRetries(maxRetriesOpt, batchWriteRequests) {
  let maxRetries = maxRetriesOpt !== undefined ? maxRetriesOpt : 5;
  let all = Object.values(batchWriteRequests).flat().length.toString();
  let attempt = (retry, requests) => {
    let handleRetry = (logMsg, retryRequests) => Effect$1.Effect.flatMap(Effect$1.Effect.logInfo(logMsg), () => {
      if (retry < maxRetries) {
        let timeout = Stdlib_Math.Int.random(500, 1500);
        return Effect$1.Effect.flatMap(Effect$1.Effect.tap(Effect$1.Effect.sleep(Effect$1.Duration.millis(timeout)), () => Effect$1.Effect.logInfo(`Retry batchWrite after ` + timeout.toString() + ` ms`)), () => attempt(retry + 1 | 0, retryRequests));
      }
      let count = Object.values(retryRequests).flat().length.toString();
      return Effect$1.Effect.succeed({
        TAG: "Error",
        _0: `batchWrite failed ` + count + `/` + all + ` requests after ` + maxRetries.toString() + ` retries`
      });
    });
    return Effect$1.Effect.catchAll(Effect$1.Effect.flatMap(Effect.tryPromise(err => Util_Error$ReventlessCore.messageFromUnknown(err, "batchWrite"), () => batchWrite(requests)), writeOutput => {
      if (!hasUnprocessedItems(writeOutput)) {
        return Effect$1.Effect.succeed({
          TAG: "Ok",
          _0: undefined
        });
      }
      let unprocessedRequests = Stdlib_Option.getOrThrow(writeOutput.UnprocessedItems, undefined);
      let count = Object.keys(unprocessedRequests).length.toString();
      return handleRetry("Util_DynamoDb_Runtime-ReventlessAws" + (`.batchWriteWithRetries: retry ` + retry.toString() + `: ` + count + ` unprocessed items`), unprocessedRequests);
    }), errorMsg => handleRetry("Util_DynamoDb_Runtime-ReventlessAws" + (`.batchWriteWithRetries: retry ` + retry.toString() + ` failed: ` + errorMsg), requests));
  };
  return attempt(0, batchWriteRequests);
}

function toPutRequest(json) {
  return {
    PutRequest: {
      Item: json
    }
  };
}

function toDeleteRequest(keys) {
  return {
    DeleteRequest: {
      Key: keys
    }
  };
}

function toTable(writeRequests, tableName) {
  return Object.fromEntries([[
      tableName,
      writeRequests
    ]]);
}

export {
  put,
  putWithRetries,
  putIfNotExistsWithRetries,
  $$delete,
  deleteWithRetries,
  queryStream,
  scanStream,
  queryById,
  keysFromResource,
  purgeTimeAttributeName,
  calcPurgeTime,
  insertTtl,
  batchWrite,
  hasUnprocessedItems,
  batchWriteWithRetries,
  toPutRequest,
  toDeleteRequest,
  toTable,
}
/* Effect Not a pure module */
