// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as CommandGenerator_Callback$ReventlessCore from "../../src/components/CommandGenerator/CommandGenerator_Callback.res.mjs";

S.enableJson();

let name = "TestCmdGenAgg";

let commandSchema = S.union([
  S.literal("Create"),
  S.schema(s => ({
    TAG: "CreateWithName",
    name: s.m(S.string)
  })),
  S.literal("Invalid")
]);

let eventSchema = S.union([
  S.literal("Created"),
  S.schema(s => ({
    TAG: "CreatedWithName",
    name: s.m(S.string)
  }))
]);

let errorSchema = S.literal("InvalidCommand");

let moduleUrl = import.meta.url;

let CmdGenAggSpec = {
  Id: undefined,
  name: name,
  commandSchema: commandSchema,
  eventSchema: eventSchema,
  errorSchema: errorSchema,
  moduleUrl: moduleUrl
};

let moduleUrl$1 = import.meta.url;

function evolve(_state, _event) {
  
}

function decide(_state, command) {
  if (typeof command !== "object") {
    if (command === "Create") {
      return {
        TAG: "Ok",
        _0: ["Created"]
      };
    } else {
      return {
        TAG: "Ok",
        _0: []
      };
    }
  } else {
    return {
      TAG: "Ok",
      _0: [{
          TAG: "CreatedWithName",
          name: command.name
        }]
    };
  }
}

let CmdGenBehavior = {
  Spec: undefined,
  moduleUrl: moduleUrl$1,
  initialState: undefined,
  evolve: evolve,
  decide: decide
};

let capturedCmds = {
  contents: []
};

async function publishJsons(cmds) {
  capturedCmds.contents = capturedCmds.contents.concat(cmds);
}

let MockPublishSpec = {
  publishJsons: publishJsons,
  publishJsonsAndWait: undefined
};

let TestGenerator = CommandGenerator_Callback$ReventlessCore.Make(MockPublishSpec)({
  Id: {
    schema: Id$Reventless.StringPure.schema,
    make: prim => prim,
    makeFromString: prim => prim,
    toString: prim => prim,
    cmp: Id$Reventless.StringPure.cmp
  },
  name: name,
  eventSchema: eventSchema,
  errorSchema: errorSchema,
  commandSchema: commandSchema,
  moduleUrl: moduleUrl
});

let singleTagCommandSchema = S.schema(s => ({
  TAG: "CreateItem",
  itemId: s.m(DcbTag$Reventless.string),
  name: s.m(S.string)
}));

let compositeTagCommandSchema = S.schema(s => ({
  TAG: "DeployVersion",
  environment: s.m(DcbTag$Reventless.compositePartitionMember(0, "-")),
  service: s.m(DcbTag$Reventless.compositePartitionMember(1, undefined)),
  version: s.m(S.string)
}));

let singleTagSliceGen = CommandGenerator_Callback$ReventlessCore.makeGenerateCommand(publishJsons, undefined, "SingleTagSlice", singleTagCommandSchema, "StateChangeSlice", false);

let compositeTagSliceGen = CommandGenerator_Callback$ReventlessCore.makeGenerateCommand(publishJsons, undefined, "CompositeTagSlice", compositeTagCommandSchema, "StateChangeSlice", false);

function makeSlicePayload(command, args) {
  return {
    command: command,
    arguments: args,
    meta: {
      ip: ["127.0.0.1"],
      user: "test-user",
      info: ""
    }
  };
}

function makeZeroParamPayload(id, command) {
  return {
    command: command,
    arguments: {
      id: id
    },
    meta: {
      ip: ["127.0.0.1"],
      user: "test-user",
      info: ""
    }
  };
}

function makeOneParamPayload(id, command, paramName, paramValue) {
  return {
    command: command,
    arguments: Object.fromEntries([
      [
        "id",
        id
      ],
      [
        paramName,
        paramValue
      ]
    ]),
    meta: {
      ip: ["127.0.0.1"],
      user: "test-user",
      info: ""
    }
  };
}

function reset() {
  capturedCmds.contents = [];
}

export {
  CmdGenAggSpec,
  CmdGenBehavior,
  capturedCmds,
  MockPublishSpec,
  TestGenerator,
  singleTagCommandSchema,
  compositeTagCommandSchema,
  singleTagSliceGen,
  compositeTagSliceGen,
  makeSlicePayload,
  makeZeroParamPayload,
  makeOneParamPayload,
  reset,
}
/*  Not a pure module */
