// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var Core__Array = require("@rescript/core/src/Core__Array.res.js");
var Pulumi = require("@pulumi/pulumi");
var Util_Pulumi$Reventless = require("@reventless/reventless/src/util/Util_Pulumi.res.js");
var EventCollectorChannel_Helpers$ReventlessAws = require("./EventCollectorChannel_Helpers.res.js");
var EventCollectorChannel_SQS_Runtime$ReventlessAws = require("./EventCollectorChannel_SQS_Runtime.res.js");

function connect(name, channelSpecs, runtime, opts) {
  var opts$1 = Util_Pulumi$Reventless.ComponentResourceOptions.toCustomResourceOptions(opts);
  var lambda = runtime.parts.lambda;
  var lambdaRole = runtime.parts.lambdaRole;
  var queues = [];
  var eventTopics = Core__Array.reduce(channelSpecs, {}, (function (acc, param) {
          return Object.assign(acc, param.eventTopics);
        }));
  var resources = channelSpecs.map(function (param) {
          return param.resources;
        }).flat();
  return EventCollectorChannel_Helpers$ReventlessAws.connectLambda(lambda, name, lambdaRole, queues, eventTopics, resources, opts$1);
}

function make(param, eventTopics, param$1) {
  var eventTopicResources = Js_dict.values(eventTopics).map(function (outputs) {
        return outputs.resources[0];
      });
  var enqueueEventNotSupported = function (delay, id, messageBody) {
    return Promise.resolve((console.log("EventCollectorChannel_DynamoDbStream-ReventlessAws" + " supports no enqueueEvent:", delay, id, messageBody), undefined));
  };
  var handleChannelEvent = function (handleEvents) {
    return Pulumi.output(EventCollectorChannel_SQS_Runtime$ReventlessAws.handleDynamoDbEvent(handleEvents));
  };
  return {
          parts: undefined,
          resources: eventTopicResources,
          enqueueEvent: Pulumi.output(enqueueEventNotSupported),
          handleChannelEvent: handleChannelEvent
        };
}

exports.connect = connect;
exports.make = make;
/* @pulumi/pulumi Not a pure module */
