// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var Aws = require("@pulumi/aws");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Pulumi = require("@pulumi/pulumi");
var Lambda$PulumiAws = require("@reventless/bs-pulumi-aws/src/Lambda/Lambda.bs.js");
var SQS_Queue$PulumiAws = require("@reventless/bs-pulumi-aws/src/SQS/SQS_Queue.bs.js");
var Util_SQS$ReventlessAws = require("../../util/Util_SQS.bs.js");
var Util_Aggregate$Reventless = require("@reventless/reventless/src/util/Util_Aggregate.bs.js");
var Util_SNS_FIFO$ReventlessAws = require("../../util/Util_SNS_FIFO.bs.js");
var Util_SQS_FIFO$ReventlessAws = require("../../util/Util_SQS_FIFO.bs.js");
var Util_ExtensionPoint$Reventless = require("@reventless/reventless/src/util/Util_ExtensionPoint.bs.js");
var Util_SqsQueuePolicy$ReventlessAws = require("../../util/Util_SqsQueuePolicy.bs.js");
var Util_DeadLetterQueue$ReventlessAws = require("../../util/Util_DeadLetterQueue.bs.js");
var Util_EventSourceMapping$ReventlessAws = require("../../util/Util_EventSourceMapping.bs.js");
var EventCollectorConnector_SQS_Runtime$ReventlessAws = require("./EventCollectorConnector_SQS_Runtime.bs.js");

function make(name, aggregateNames, extensionPointNames, policies, handleEvents, memorySize, timeout, opts, resources) {
  var queue = new (Aws.sqs.Queue)(name, {
        contentBasedDeduplication: true,
        fifoQueue: true,
        redrivePolicy: Util_DeadLetterQueue$ReventlessAws.fifoQueue.arn.apply((function (dlqArn) {
                return Curry._2(SQS_Queue$PulumiAws.Args.RedrivePolicy.make, dlqArn, 5);
              })),
        visibilityTimeoutSeconds: timeout,
        deduplicationScope: "messageGroup",
        fifoThroughputLimit: "perMessageGroupId"
      }, opts);
  Util_SqsQueuePolicy$ReventlessAws.make(name, queue, /* array */[
        Util_SqsQueuePolicy$ReventlessAws.allowAllSnsTopicsSendMessage(queue),
        Util_SqsQueuePolicy$ReventlessAws.allowCloudWatchEvents
      ], Caml_option.some(opts), /* () */0);
  var eventHandlerLambda = Pulumi.all(policies).apply((function (policies) {
          return new (Aws.lambda.CallbackFunction)(name, Curry.app(Lambda$PulumiAws.CallbackFunction.Args.make, [
                          (function (param, param$1) {
                              return EventCollectorConnector_SQS_Runtime$ReventlessAws.handleCallbackEvent(handleEvents, queue, param, param$1);
                            }),
                          undefined,
                          policies,
                          undefined,
                          undefined,
                          Caml_option.some(memorySize),
                          Caml_option.some(timeout),
                          undefined,
                          undefined,
                          undefined,
                          /* () */0
                        ]), opts);
        }));
  eventHandlerLambda.apply((function (eventHandlerLambda) {
          return queue.onEvent(name, eventHandlerLambda, undefined, opts);
        }));
  var match = Belt_Array.partition(Belt_Array.concat(Util_Aggregate$Reventless.eventTopics(resources, aggregateNames), Util_ExtensionPoint$Reventless.eventTopics(resources, extensionPointNames)), (function (param) {
          return param[0] === Util_SNS_FIFO$ReventlessAws.service;
        }));
  Belt_Array.map(match[0], (function (param) {
          return Util_SQS$ReventlessAws.subscribeToSnsTopic(queue, name, opts, param);
        }));
  Belt_Array.map(match[1], (function (param) {
          var match = param[1];
          return Util_EventSourceMapping$ReventlessAws.subscribe(undefined, eventHandlerLambda, name, match[0], match[1], opts, /* () */0);
        }));
  return /* record */[/* resource */Caml_option.some(Util_SQS_FIFO$ReventlessAws.toResource(queue))];
}

exports.make = make;
/* @pulumi/aws Not a pure module */
