// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as Plugin$Reventless from "@reventlessdev/reventless-spec/src/components/Plugin.res.mjs";
import * as Api$ReventlessInfra from "@reventlessdev/reventless-infra/src/components/Api.res.mjs";

let commandSchema = Sury.union([
  Sury.$schema(s => ({
    TAG: "RegisterUiFragment",
    pluginId: s.m(DcbTag$Reventless.string),
    manifest: s.m(Plugin$Reventless.uiFragmentManifestSchema),
    at: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "DeregisterUiFragment",
    pluginId: s.m(DcbTag$Reventless.string)
  }))
]);

let errorSchema = Sury.literal("RegistryError");

let eventSchema = Sury.union([
  Sury.$schema(s => ({
    TAG: "UiFragmentRegistered",
    pluginId: s.m(DcbTag$Reventless.string),
    manifest: s.m(Plugin$Reventless.uiFragmentManifestSchema),
    at: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "UiFragmentUpdated",
    pluginId: s.m(DcbTag$Reventless.string),
    previousManifest: s.m(Plugin$Reventless.uiFragmentManifestSchema),
    newManifest: s.m(Plugin$Reventless.uiFragmentManifestSchema),
    at: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "UiFragmentDeregistered",
    pluginId: s.m(DcbTag$Reventless.string)
  }))
]);

let commandSchema$1 = Api$ReventlessInfra.markNoApi(commandSchema);

function commandAuthorization(param) {
  return "AllowAuthenticated";
}

let name = "UiFragmentRegistry";

let Id;

let consumedEventSchema = eventSchema;

let moduleUrl = "@reventlessdev/reventless-core/src/admin/UiFragmentRegistry/StateChangeSlice/UiFragmentRegistry.res.mjs";

let readConsistency = "EscalateOnRetry";

export {
  name,
  Id,
  errorSchema,
  eventSchema,
  consumedEventSchema,
  commandSchema$1 as commandSchema,
  moduleUrl,
  commandAuthorization,
  readConsistency,
}
/* commandSchema Not a pure module */
