// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Nodeurl from "node:url";
import * as Nodepath from "node:path";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as DependencyBundler from "./DependencyBundler.res.mjs";
import * as DependencyBundler_PostProcess from "./DependencyBundler_PostProcess.res.mjs";

let dirname = Nodepath.dirname(Nodeurl.fileURLToPath(import.meta.url));

let pathToLayerData = Nodepath.resolve(dirname, "../builder/layer/");

let pathToSavedDependencies = Nodepath.resolve(dirname, "../builder/layer/nodejs/node_modules");

let sourcePackageVersion = Stdlib_Option.getOr(process.env["REVENTLESS_AWS_VERSION"], "latest");

let config_excludeScopes = [
  "pulumi",
  "types",
  "opentelemetry",
  "aws-sdk",
  "sigstore",
  "npmcli",
  "gar"
];

let config_excludeModules = [
  "aws-sdk",
  "sury-ppx",
  "fast-check",
  "ssh2",
  "tweetnacl",
  "bcrypt-pbkdf",
  "asn1",
  "esbuild",
  "@reventlessdev/rescript-pulumi-pulumi",
  "@reventlessdev/rescript-pulumi-aws",
  "esprima",
  "acorn",
  "source-map",
  "source-map-support",
  "cjs-module-lexer",
  "execa",
  "cross-spawn",
  "shebang-command",
  "shebang-regex",
  "cacache",
  "make-fetch-happen",
  "ssri",
  "minipass-fetch",
  "minipass-collect",
  "minipass-flush",
  "minipass-pipeline",
  "minipass-sized",
  "socks",
  "socks-proxy-agent",
  "http-proxy-agent",
  "https-proxy-agent",
  "hosted-git-info",
  "npm-install-checks",
  "npm-normalize-package-bin",
  "npm-package-arg",
  "npm-pick-manifest",
  "validate-npm-package-name",
  "spdx-exceptions",
  "spdx-expression-parse",
  "spdx-license-ids",
  "pure-rand",
  "ramda",
  "lodash",
  "graphql",
  "jsonschema2graphql",
  "debug",
  "ms",
  "semver",
  "graceful-fs",
  "js-yaml",
  "argparse",
  "camelcase",
  "escalade",
  "proc-log",
  "ansi-regex",
  "ansi-styles",
  "strip-ansi",
  "color-convert",
  "color-name",
  "merge-stream",
  "signal-exit",
  "module-details-from-path",
  "punycode",
  "wrappy",
  "once",
  "function-bind",
  "hasown",
  "is-core-module",
  "path-parse",
  "resolve",
  "supports-preserve-symlinks-flag",
  "safer-buffer",
  "sprintf-js",
  "type-fest",
  "inherits",
  "minipass",
  "minizlib"
];

let config_includeModules = ["@rescript/runtime"];

let config_registryOpts = Object.fromEntries([
  [
    "@reventlessdev:registry",
    "https://npm.pkg.github.com"
  ],
  [
    "//npm.pkg.github.com/:_authToken",
    Stdlib_Option.getOr(process.env["GITHUB_TOKEN"], "")
  ]
]);

let config_postProcess = Object.fromEntries([
  [
    ">rescript",
    DependencyBundler_PostProcess.rescriptDependent
  ],
  [
    "@reventlessdev/reventless-core",
    DependencyBundler_PostProcess.reventlessCoreDeploytime
  ],
  [
    "@reventlessdev/rescript-effect",
    DependencyBundler_PostProcess.deleteTests
  ],
  [
    "effect",
    DependencyBundler_PostProcess.deleteEffectSrc
  ],
  [
    "@reventlessdev/rescript-fast-csv",
    DependencyBundler_PostProcess.deleteTestsAndExamples
  ],
  [
    "fast-csv",
    DependencyBundler_PostProcess.deleteTestsAndExamples
  ]
]);

let config_rootPostProcess = DependencyBundler_PostProcess.reventlessAwsDeploytime;

let config = {
  sourcePackageName: "@reventlessdev/reventless-aws",
  sourcePackageVersion: sourcePackageVersion,
  pathToLayerData: pathToLayerData,
  pathToSavedDependencies: pathToSavedDependencies,
  excludeScopes: config_excludeScopes,
  excludeModules: config_excludeModules,
  includeModules: config_includeModules,
  registryOpts: config_registryOpts,
  postProcess: config_postProcess,
  rootPostProcess: config_rootPostProcess
};

DependencyBundler.build(config);

export {
  dirname,
  pathToLayerData,
  pathToSavedDependencies,
  sourcePackageVersion,
  config,
}
/* dirname Not a pure module */
