// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as Money$Reventless from "@reventlessdev/reventless-spec/src/semantic/Money.res.mjs";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as UploadableImage$Reventless from "@reventlessdev/reventless-spec/src/semantic/UploadableImage.res.mjs";

let externalInputSchema = Sury.$schema(s => ({
  sku: s.m(Sury.string),
  title: s.m(Sury.string),
  desc: s.m(Sury.string),
  unitPrice: s.m(Sury.int),
  currency: s.m(Sury.string),
  category: s.m(Sury.string)
}));

let commandSchema = Sury.$schema(s => ({
  TAG: "AddProduct",
  productId: s.m(DcbTag$Reventless.string),
  name: s.m(Sury.string),
  description: s.m(Sury.string),
  price: s.m(Money$Reventless.schema),
  productImage: s.m(Sury.$option(UploadableImage$Reventless.forField(undefined, "productImages"))),
  categoryId: s.m(DcbTag$Reventless.string)
}));

function commandAuthorization(command) {
  return {
    TAG: "AllowGroups",
    _0: [
      "Admin",
      "Merchandiser"
    ]
  };
}

let name = "ImportProduct";

let Id;

let targetName = "AddProduct";

let externalSystem = "SupplierFeed";

let moduleUrl = "@reventlessdev/online-shop-hybrid-catalog/src/Product/InboundTranslationSlice/ImportProduct.res.mjs";

export {
  name,
  Id,
  externalInputSchema,
  commandSchema,
  targetName,
  externalSystem,
  moduleUrl,
  commandAuthorization,
}
/* externalInputSchema Not a pure module */
