// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Aws = require("@pulumi/aws");
var Core__Array = require("@rescript/core/src/Core__Array.res.js");
var StringLabels = require("@rescript/std/lib/js/stringLabels.js");
var IAM$PulumiAws = require("@reventless/rescript-pulumi-aws/src/IAM/IAM.res.js");
var Output$Pulumi = require("@reventless/bs-pulumi-pulumi/src/Output.res.js");
var Pulumi = require("@pulumi/pulumi");
var Lambda$PulumiAws = require("@reventless/rescript-pulumi-aws/src/Lambda/Lambda.res.js");
var AWS$ReventlessAws = require("../AWS.res.js");
var Adapter$Reventless = require("@reventless/reventless/src/adapter/Adapter.res.js");
var Util_Pulumi$Reventless = require("@reventless/reventless/src/util/Util_Pulumi.res.js");
var Util_Adapter$Reventless = require("@reventless/reventless/src/util/Util_Adapter.res.js");
var PolicyDocument$PulumiAws = require("@reventless/rescript-pulumi-aws/src/IAM/PolicyDocument.res.js");
var AppSync_Resolver$PulumiAws = require("@reventless/rescript-pulumi-aws/src/AppSync/AppSync_Resolver.res.js");
var Util_AppSync$ReventlessAws = require("../../util/Util_AppSync.res.js");
var AppSync_Resolver_Templates$PulumiAws = require("@reventless/rescript-pulumi-aws/src/AppSync/AppSync_Resolver_Templates.res.js");

function handleResolversEvent(generateCommand) {
  return Pulumi.output(function ($$event, _context) {
              return generateCommand($$event);
            });
}

function make(name, api, fields, runtime, resources, opts) {
  var opts$1 = Util_Pulumi$Reventless.ComponentResourceOptions.toCustomResourceOptions(opts);
  var lambda = runtime.parts.lambda;
  var lambdaRole = runtime.parts.lambdaRole;
  var dataSourceRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name + "DataSource", Pulumi.output(AWS$ReventlessAws.AppSync.principal), opts$1);
  Pulumi.all([
          Output$Pulumi.flatMap(lambda, (function (lambda) {
                  return lambda.arn;
                })),
          Output$Pulumi.flatMap(lambda, (function (lambda) {
                  return lambda.name;
                })),
          lambdaRole.id,
          Adapter$Reventless.resourcesToUnwrappedOutput(resources)
        ]).apply(function (param) {
        var targetSqsResources = Util_Adapter$Reventless.filterSupportedUnwrappedResources(param[3], [
              AWS$ReventlessAws.SQS.service,
              AWS$ReventlessAws.SQS_FIFO.service
            ]);
        var lambdaSqsSendPolicyDocument = targetSqsResources.length > 0 ? PolicyDocument$PulumiAws.make(undefined, name + "SendSQS", [{
                  Sid: "LambdaAllowSendSQS",
                  Effect: "Allow",
                  Action: "sqs:SendMessage",
                  Resource: Adapter$Reventless.urns(targetSqsResources)
                }]) : undefined;
        new (Aws.iam.RolePolicy)(name, {
              policy: PolicyDocument$PulumiAws.mergePolicyDocuments(name + "LambdaPolicy", Core__Array.keepSome([
                        Lambda$PulumiAws.defaultLoggingPolicyDocument,
                        lambdaSqsSendPolicyDocument
                      ])),
              role: param[2]
            }, opts$1);
        new (Aws.lambda.Permission)(name, {
              action: "lambda:InvokeFunction",
              function: param[1],
              principal: AWS$ReventlessAws.CloudwatchEventRule.principal
            }, opts$1);
        new (Aws.iam.RolePolicy)(name + "DataSource", {
              policy: PolicyDocument$PulumiAws.toJsonString(PolicyDocument$PulumiAws.make(undefined, name + "DataSourcePolicy", [{
                          Sid: "AllowCloudWatchDataSourceInvokeLambda",
                          Effect: "Allow",
                          Action: "lambda:InvokeFunction",
                          Resource: param[0]
                        }])),
              role: dataSourceRole.id
            }, opts$1);
      });
  var dataSource = new (Aws.appsync.DataSource)(name, {
        type: "AWS_LAMBDA",
        apiId: Output$Pulumi.flatMap(api, (function (api) {
                return api.id;
              })),
        lambdaConfig: {
          functionArn: Output$Pulumi.flatMap(lambda, (function (lambda) {
                  return lambda.arn;
                }))
        },
        serviceRoleArn: dataSourceRole.arn
      }, opts$1);
  var invokeCommandGenerator = function (command) {
    return "\n  #set($parentTypeName = $context.info.parentTypeName)\n  #set($fieldName = $context.info.fieldName)\n  {\n    \"version\": \"2017-02-28\",\n    \"operation\": \"Invoke\",\n    \"payload\": {\n        \"command\": \"" + command + "\",\n        \"arguments\": $utils.toJson($context.arguments),\n        \"meta\": {\n          \"ip\": $util.toJson($context.identity.sourceIp),\n          \"user\": $util.toJson($context.identity.username),\n          \"info\": $util.toJson(\"$parentTypeName.$fieldName\")\n        }\n    }\n  }\n  ";
  };
  var resolvers = fields.map(function (field) {
        var match = field.split("_");
        var commandName = match.length !== 2 ? StringLabels.capitalize_ascii(field) : StringLabels.capitalize_ascii(match[1]);
        return AppSync_Resolver$PulumiAws.makeUnitResolver(StringLabels.capitalize_ascii(field), api, dataSource.name, "Mutation", field, invokeCommandGenerator(commandName), AppSync_Resolver_Templates$PulumiAws.result, opts$1);
      });
  var resources$1 = resolvers.map(Util_AppSync$ReventlessAws.toResource);
  return {
          resources: resources$1
        };
}

exports.handleResolversEvent = handleResolversEvent;
exports.make = make;
/* @pulumi/aws Not a pure module */
