// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var $$String = require("rescript/lib/js/string.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Aws = require("@pulumi/aws");
var Caml_option = require("rescript/lib/js/caml_option.js");
var IAM$PulumiAws = require("@reventless/bs-pulumi-aws/src/IAM/IAM.bs.js");
var Output$Pulumi = require("@reventless/bs-pulumi-pulumi/src/Output.bs.js");
var Pulumi = require("@pulumi/pulumi");
var Lambda$PulumiAws = require("@reventless/bs-pulumi-aws/src/Lambda/Lambda.bs.js");
var Logger$Reventless = require("@reventless/reventless/src/util/Logger.bs.js");
var AppSync_Resolver$PulumiAws = require("@reventless/bs-pulumi-aws/src/AppSync/AppSync_Resolver.bs.js");
var Util_AppSync$ReventlessAws = require("../../util/Util_AppSync.bs.js");
var AppSync_Resolver_Templates$PulumiAws = require("@reventless/bs-pulumi-aws/src/AppSync/AppSync_Resolver_Templates.bs.js");
var CommandGeneratorResolvers_AppSync_Runtime$ReventlessAws = require("./CommandGeneratorResolvers_AppSync_Runtime.bs.js");

function make(name, api, fields, commandGenerator, opts) {
  var commandGeneratorLambda = new (Aws.lambda.CallbackFunction)(name, Curry.app(Lambda$PulumiAws.CallbackFunction.Args.make, [
            (function (param, param$1) {
                return CommandGeneratorResolvers_AppSync_Runtime$ReventlessAws.generateCommand(commandGenerator, param, param$1);
              }),
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined
          ]), opts);
  var commandGeneratorArn = commandGeneratorLambda.arn;
  new (Aws.lambda.Permission)(name, {
        action: "lambda:InvokeFunction",
        function: commandGeneratorArn,
        principal: "appsync.amazonaws.com"
      }, opts);
  var dataSourceRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name + "DS", Pulumi.output("appsync.amazonaws.com"), Caml_option.some(opts), undefined);
  new (Aws.iam.RolePolicy)(name + "DS", {
        policy: commandGeneratorArn.apply(function (commandGeneratorArn) {
              return IAM$PulumiAws.RolePolicy.generatePolicy([commandGeneratorArn], "lambda:InvokeFunction");
            }),
        role: dataSourceRole.id
      }, opts);
  var dataSource = new (Aws.appsync.DataSource)(name, {
        type: "AWS_LAMBDA",
        apiId: Output$Pulumi.flatMap(api, (function (api) {
                return api.id;
              })),
        lambdaConfig: {
          functionArn: commandGeneratorArn
        },
        serviceRoleArn: dataSourceRole.arn
      }, Caml_option.some(opts));
  var invokeCommandGenerator = function (command) {
    return "\n      {\n        \"version\": \"2017-02-28\",\n        \"operation\": \"Invoke\",\n        \"payload\": {\n            \"command\": \"" + command + "\",\n            \"arguments\": \$utils.toJson(\$context.arguments),\n            \"meta\": {\n              \"ip\": \$util.toJson(\$context.identity.sourceIp),\n              \"user\": \$util.toJson(\$context.identity.username)\n            }\n        }\n      }\n      ";
  };
  var resolvers = Belt_Array.map(fields, (function (field) {
          var match = field.split("_");
          var commandName = match.length !== 2 ? $$String.capitalize_ascii(field) : $$String.capitalize_ascii(match[1]);
          Logger$Reventless.logOutput("File \"CommandGeneratorResolvers_AppSync.re\", line 123, characters 15-22", undefined, undefined, "datasource-name (" + name + ")", dataSource.name);
          return AppSync_Resolver$PulumiAws.makeUnitResolver($$String.capitalize_ascii(field), api, dataSource.name, "Mutation", field, invokeCommandGenerator(commandName), AppSync_Resolver_Templates$PulumiAws.result, Caml_option.some(opts), undefined);
        }));
  var resources = Belt_Array.map(resolvers, Util_AppSync$ReventlessAws.toResource);
  return {
          resources: resources
        };
}

exports.make = make;
/* @pulumi/aws Not a pure module */
