// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Money$Reventless from "@reventlessdev/reventless-spec/src/semantic/Money.res.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Currency$Reventless from "@reventlessdev/reventless-spec/src/semantic/Currency.res.mjs";

let initialState_placedOrderIds = [];

let initialState_availableProductIds = [];

let initialState_shelf = [];

let initialState_productImages = [];

let initialState = {
  placedOrderIds: initialState_placedOrderIds,
  availableProductIds: initialState_availableProductIds,
  shelf: initialState_shelf,
  productImages: initialState_productImages
};

function replacing(pairs, productId, value) {
  return pairs.filter(param => Primitive_object.notequal(param[0], productId)).concat([[
      productId,
      value
    ]]);
}

function without(pairs, productId) {
  return pairs.filter(param => Primitive_object.notequal(param[0], productId));
}

function lookup(pairs, productId) {
  return Stdlib_Option.map(pairs.find(param => Primitive_object.equal(param[0], productId)), param => param[1]);
}

function evolve(state, event) {
  switch (event.TAG) {
    case "OrderPlaced" :
      let orderId = event.orderId;
      return {
        placedOrderIds: state.placedOrderIds.includes(orderId) ? state.placedOrderIds : state.placedOrderIds.concat([orderId]),
        availableProductIds: state.availableProductIds,
        shelf: state.shelf,
        productImages: state.productImages
      };
    case "CatalogProductPriceChanged" :
      let productId = event.productId;
      let product = lookup(state.shelf, productId);
      return {
        placedOrderIds: state.placedOrderIds,
        availableProductIds: state.availableProductIds,
        shelf: product !== undefined ? replacing(state.shelf, productId, {
            name: product.name,
            price: event.price
          }) : state.shelf,
        productImages: state.productImages
      };
    case "CatalogProductWithdrawn" :
      let productId$1 = event.productId;
      return {
        placedOrderIds: state.placedOrderIds,
        availableProductIds: state.availableProductIds.filter(id => id !== productId$1),
        shelf: state.shelf,
        productImages: state.productImages
      };
    case "CatalogProductSynced" :
    case "CatalogProductRelisted" :
      break;
    case "CatalogProductImageChanged" :
      let productImage = event.productImage;
      let productId$2 = event.productId;
      return {
        placedOrderIds: state.placedOrderIds,
        availableProductIds: state.availableProductIds,
        shelf: state.shelf,
        productImages: productImage !== undefined ? replacing(state.productImages, productId$2, productImage) : without(state.productImages, productId$2)
      };
  }
  let productId$3 = event.productId;
  return {
    placedOrderIds: state.placedOrderIds,
    availableProductIds: state.availableProductIds.includes(productId$3) ? state.availableProductIds : state.availableProductIds.concat([productId$3]),
    shelf: replacing(state.shelf, productId$3, {
      name: event.name,
      price: event.price
    }),
    productImages: state.productImages
  };
}

function mergeLines(lineItems) {
  return Stdlib_Array.reduce(lineItems, [], (merged, param) => {
    let quantity = param.quantity;
    let productId = param.productId;
    let at = merged.findIndex(line => line.productId === productId);
    if (at !== -1) {
      return merged.map((line, i) => {
        if (i === at) {
          return {
            productId: line.productId,
            quantity: line.quantity + quantity | 0
          };
        } else {
          return line;
        }
      });
    } else {
      return merged.concat([{
          productId: productId,
          quantity: quantity
        }]);
    }
  });
}

function priceLine(state, param) {
  let quantity = param.quantity;
  let productId = param.productId;
  let match = lookup(state.shelf, productId);
  if (match === undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "ProductsNotAvailable",
        missing: [productId]
      }
    };
  }
  let price = match.price;
  let lineTotal = Money$Reventless.times(price, quantity);
  if (lineTotal.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: {
        productId: productId,
        name: match.name,
        quantity: quantity,
        unitPrice: price,
        lineTotal: lineTotal._0
      }
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidQuantity",
        productId: productId,
        quantity: quantity
      }
    };
  }
}

function priceLines(state, lineItems) {
  return Stdlib_Array.reduce(lineItems, {
    TAG: "Ok",
    _0: []
  }, (acc, lineItem) => {
    let match = priceLine(state, lineItem);
    if (acc.TAG === "Ok") {
      if (match.TAG === "Ok") {
        return {
          TAG: "Ok",
          _0: acc._0.concat([match._0])
        };
      } else {
        return match;
      }
    } else {
      return acc;
    }
  });
}

function decide(state, command) {
  let orderId = command.orderId;
  if (state.placedOrderIds.includes(orderId)) {
    return {
      TAG: "Error",
      _0: "OrderAlreadyPlaced"
    };
  }
  let lineItems = command.lineItems;
  if (lineItems.length === 0) {
    return {
      TAG: "Error",
      _0: "OrderIsEmpty"
    };
  }
  let match = lineItems.find(param => param.quantity <= 0);
  if (match !== undefined) {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidQuantity",
        productId: match.productId,
        quantity: match.quantity
      }
    };
  }
  let merged = mergeLines(lineItems);
  let missing = Stdlib_Array.filterMap(merged, param => {
    let productId = param.productId;
    if (state.availableProductIds.includes(productId)) {
      return;
    } else {
      return productId;
    }
  });
  if (missing.length !== 0) {
    return {
      TAG: "Error",
      _0: {
        TAG: "ProductsNotAvailable",
        missing: missing
      }
    };
  }
  let failed = priceLines(state, merged);
  if (failed.TAG !== "Ok") {
    return failed;
  }
  let lines = failed._0;
  let match$1 = Money$Reventless.sum(lines.map(line => line.lineTotal));
  if (match$1 === undefined) {
    return {
      TAG: "Error",
      _0: "OrderIsEmpty"
    };
  }
  if (match$1.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: {
        TAG: "MixedCurrencies",
        currencies: Stdlib_Array.reduce(lines, [], (codes, line) => {
          let code = Currency$Reventless.toString(line.unitPrice.currency);
          if (codes.includes(code)) {
            return codes;
          } else {
            return codes.concat([code]);
          }
        })
      }
    };
  }
  let first = Stdlib_Option.map(lines[0], line => line.productId);
  let firstProductName = Stdlib_Option.map(lines[0], line => line.name);
  let firstProductImage = Stdlib_Option.flatMap(first, id => lookup(state.productImages, id));
  return {
    TAG: "Ok",
    _0: [{
        TAG: "OrderPlaced",
        orderId: orderId,
        customerId: command.customerId,
        productIds: lines.map(line => line.productId),
        lines: lines,
        total: match$1._0,
        shippingMethod: command.shippingMethod,
        deliveryWindow: command.deliveryWindow,
        firstProductName: firstProductName,
        firstProductImage: firstProductImage
      }]
  };
}

let Spec;

let moduleUrl = "@reventlessdev/online-shop-hybrid-ordering/src/Order/StateChangeSlice/PlaceOrder_Behavior.res.mjs";

export {
  Spec,
  initialState,
  replacing,
  without,
  lookup,
  evolve,
  mergeLines,
  priceLine,
  priceLines,
  decide,
  moduleUrl,
}
/* Money-Reventless Not a pure module */
