// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Metrics$ReventlessCore from "../../src/util/Metrics.res.mjs";

function field(json, key) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    return json[key];
  }
}

function str(json) {
  return Stdlib_Option.flatMap(json, Stdlib_JSON.Decode.string);
}

function num(json) {
  return Stdlib_Option.flatMap(json, Stdlib_JSON.Decode.float);
}

globalThis.describe("Metrics.metricLine", () => {
  let line = Metrics$ReventlessCore.metricLine("AppendConflict", "AddItem", undefined);
  globalThis.test("is a provider-neutral line — no AWS/CloudWatch vocabulary", () => {
    globalThis.expect(field(line, "_aws")).toEqual(undefined);
    globalThis.expect(field(line, "CloudWatchMetrics")).toEqual(undefined);
  });
  globalThis.test("carries the metric discriminator and name", () => {
    let json = field(line, Metrics$ReventlessCore.discriminator);
    globalThis.expect(Stdlib_Option.flatMap(json, Stdlib_JSON.Decode.string)).toEqual("AppendConflict");
  });
  globalThis.test("carries the slice dimension and a default count of 1", () => {
    let json = field(line, "slice");
    globalThis.expect(Stdlib_Option.flatMap(json, Stdlib_JSON.Decode.string)).toEqual("AddItem");
    let json$1 = field(line, "value");
    globalThis.expect(Stdlib_Option.flatMap(json$1, Stdlib_JSON.Decode.float)).toEqual(1.0);
    let json$2 = field(line, "unit");
    globalThis.expect(Stdlib_Option.flatMap(json$2, Stdlib_JSON.Decode.string)).toEqual("Count");
  });
  globalThis.test("honours an explicit count value", () => {
    let l = Metrics$ReventlessCore.metricLine("AppendRetry", "S", 3);
    let json = field(l, "value");
    globalThis.expect(Stdlib_Option.flatMap(json, Stdlib_JSON.Decode.float)).toEqual(3.0);
    let json$1 = field(l, Metrics$ReventlessCore.discriminator);
    globalThis.expect(Stdlib_Option.flatMap(json$1, Stdlib_JSON.Decode.string)).toEqual("AppendRetry");
  });
});

export {
  field,
  str,
  num,
}
/*  Not a pure module */
