// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";

let consumedEventSchema = S.schema(s => ({
  TAG: "OrderPlaced",
  orderId: s.m(DcbTag$Reventless.string),
  customerId: s.m(DcbTag$Reventless.string)
}));

let outboundItemSchema = S.schema(s => ({
  orderId: s.m(S.string),
  customerId: s.m(S.string)
}));

let sourceNames = [];

let name = "SendOrderConfirmation";

let Id;

let inboundCommandSchema = S.unit;

let maxRetries = 3;

let heartbeatInterval = 60;

let targetName;

let externalSystem = "EmailService";

let moduleUrl = "@reventlessdev/online-shop-dcb-ordering/src/Order/OutboundTranslationSlice/SendOrderConfirmation.res.mjs";

export {
  name,
  Id,
  consumedEventSchema,
  outboundItemSchema,
  inboundCommandSchema,
  maxRetries,
  heartbeatInterval,
  targetName,
  sourceNames,
  externalSystem,
  moduleUrl,
}
/* consumedEventSchema Not a pure module */
