// Generated by ReScript, PLEASE EDIT WITH CARE


function project(param) {
  let event = param.event;
  switch (event.TAG) {
    case "CategoryAdded" :
      let categoryId = event.categoryId;
      return [{
          TAG: "Set",
          _0: categoryId,
          _1: {
            categoryId: categoryId,
            name: event.name,
            archived: false
          }
        }];
    case "CategoryRenamed" :
      let name = event.name;
      return [{
          TAG: "Update",
          _0: event.categoryId,
          _1: state => ({
            categoryId: state.categoryId,
            name: name,
            archived: state.archived
          })
        }];
    case "CategoryArchived" :
      return [{
          TAG: "Update",
          _0: event.categoryId,
          _1: state => ({
            categoryId: state.categoryId,
            name: state.name,
            archived: true
          })
        }];
  }
}

let Spec;

let moduleUrl = "@reventlessdev/online-shop-hybrid-catalog/src/Category/StateViewSliceStream/Categories_Projection.res.mjs";

export {
  Spec,
  project,
  moduleUrl,
}
/* No side effect */
