// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Aws from "@pulumi/aws";
import * as Stdlib_Dict from "@rescript/runtime/lib/es6/Stdlib_Dict.js";
import * as Stdlib_JSON from "@rescript/runtime/lib/es6/Stdlib_JSON.js";
import * as IAM$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/IAM/IAM.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Pulumi from "@pulumi/pulumi";
import * as Lambda$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/Lambda/Lambda.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as AWS$ReventlessAws from "../AWS.res.mjs";
import * as AWS_Tags$ReventlessAws from "../AWS_Tags.res.mjs";
import * as Adapter$ReventlessCore from "@reventlessdev/reventless-core/src/adapter/Adapter.res.mjs";
import * as Util_Bundle$ReventlessAws from "../../util/Util_Bundle.res.mjs";
import * as Util_Lambda$ReventlessAws from "../../util/Util_Lambda.res.mjs";
import * as Util_Pulumi$ReventlessCore from "@reventlessdev/reventless-core/src/util/Util_Pulumi.res.mjs";
import * as CommandTopic$ReventlessCore from "@reventlessdev/reventless-core/src/components/CommandTopic/CommandTopic.res.mjs";
import * as Util_IAM_Role$ReventlessAws from "../../util/Util_IAM_Role.res.mjs";

function make(name, handler, memorySizeOpt, timeoutOpt, opts) {
  let memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 1024;
  let timeout = timeoutOpt !== undefined ? timeoutOpt : 30;
  let opts$1 = Stdlib_Option.map(opts, Util_Pulumi$ReventlessCore.ComponentResourceOptions.toCustomResourceOptions);
  let lambdaRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name, Pulumi.output(AWS$ReventlessAws.Lambda.principal), opts$1);
  let lambda = handler.apply(handler => new (Aws.lambda.CallbackFunction)(name, Lambda$PulumiAws.CallbackFunction.Args.make(handler, lambdaRole, undefined, undefined, undefined, memorySize, timeout, undefined, undefined, undefined, AWS_Tags$ReventlessAws.make(name, CommandTopic$ReventlessCore.componentType), undefined), opts$1 !== undefined ? Primitive_option.valFromOption(opts$1) : undefined));
  return {
    parts: {
      lambda: lambda,
      lambdaRole: lambdaRole
    },
    resources: [
      Adapter$ReventlessCore.outputToResource(lambda.apply(Util_Lambda$ReventlessAws.toResource)),
      Util_IAM_Role$ReventlessAws.toResource(lambdaRole)
    ]
  };
}

function makeBundled(name, handlerRef, envVarsOpt, memorySizeOpt, timeoutOpt, opts) {
  let envVars = envVarsOpt !== undefined ? envVarsOpt : ({});
  let memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 1024;
  let timeout = timeoutOpt !== undefined ? timeoutOpt : 30;
  let opts$1 = Stdlib_Option.map(opts, Util_Pulumi$ReventlessCore.ComponentResourceOptions.toCustomResourceOptions);
  let lambdaRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name, Pulumi.output(AWS$ReventlessAws.Lambda.principal), opts$1);
  let code = Util_Bundle$ReventlessAws.bundleHandler(handlerRef.handlerModule, handlerRef.handlerExport);
  let layers = Stdlib_Option.getOr(Stdlib_Option.map(process.env.REVENTLESS_LAYER_ARN, arn => [arn]), []);
  let variables = Object.fromEntries([[
      "Environment",
      Pulumi.getStack()
    ]]);
  Stdlib_Dict.forEachWithKey(envVars, (value, key) => {
    variables[key] = value;
  });
  let lambda = new (Aws.lambda.Function)(name, {
    handler: "index.handler",
    runtime: "nodejs22.x",
    code: code,
    role: lambdaRole.arn,
    memorySize: memorySize,
    timeout: timeout,
    layers: layers,
    tags: AWS_Tags$ReventlessAws.make(name, CommandTopic$ReventlessCore.componentType),
    environment: {
      variables: variables
    }
  }, opts$1 !== undefined ? Primitive_option.valFromOption(opts$1) : undefined);
  let lambdaAsCallback = Pulumi.output(lambda);
  return {
    parts: {
      lambda: lambdaAsCallback,
      lambdaRole: lambdaRole
    },
    resources: [
      Util_Lambda$ReventlessAws.functionToResource(lambda),
      Util_IAM_Role$ReventlessAws.toResource(lambdaRole)
    ]
  };
}

function makeBundledFromEntryPoint(name, entryPointCode, envVarsOpt, memorySizeOpt, timeoutOpt, opts) {
  let envVars = envVarsOpt !== undefined ? envVarsOpt : ({});
  let memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 1024;
  let timeout = timeoutOpt !== undefined ? timeoutOpt : 30;
  let opts$1 = Stdlib_Option.map(opts, Util_Pulumi$ReventlessCore.ComponentResourceOptions.toCustomResourceOptions);
  let lambdaRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name, Pulumi.output(AWS$ReventlessAws.Lambda.principal), opts$1);
  let code = Util_Bundle$ReventlessAws.bundleEntryPoint(entryPointCode);
  let layers = Stdlib_Option.getOr(Stdlib_Option.map(process.env.REVENTLESS_LAYER_ARN, arn => [arn]), []);
  let variables = Object.fromEntries([[
      "Environment",
      Pulumi.getStack()
    ]]);
  Stdlib_Dict.forEachWithKey(envVars, (value, key) => {
    variables[key] = value;
  });
  let lambda = new (Aws.lambda.Function)(name, {
    handler: "index.handler",
    runtime: "nodejs22.x",
    code: code,
    role: lambdaRole.arn,
    memorySize: memorySize,
    timeout: timeout,
    layers: layers,
    tags: AWS_Tags$ReventlessAws.make(name, CommandTopic$ReventlessCore.componentType),
    environment: {
      variables: variables
    }
  }, opts$1 !== undefined ? Primitive_option.valFromOption(opts$1) : undefined);
  let lambdaAsCallback = Pulumi.output(lambda);
  return {
    parts: {
      lambda: lambdaAsCallback,
      lambdaRole: lambdaRole
    },
    resources: [
      Util_Lambda$ReventlessAws.functionToResource(lambda),
      Util_IAM_Role$ReventlessAws.toResource(lambdaRole)
    ]
  };
}

function groupBySource(event) {
  let dict = {};
  event.Records.forEach(record => {
    let eventSourceArn = record.eventSourceARN;
    let currentEvent = Stdlib_Option.getOr(dict[eventSourceArn], {
      Records: []
    });
    dict[eventSourceArn] = {
      Records: currentEvent.Records.concat([record])
    };
  });
  return dict;
}

function extractCorrelationId(event) {
  return Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.flatMap(Stdlib_Option.flatMap(event.Records[0], r => Stdlib_Option.flatMap(r.body, body => {
    try {
      return Stdlib_JSON.Decode.object(JSON.parse(body));
    } catch (exn) {
      return;
    }
  })), obj => obj["meta"]), Stdlib_JSON.Decode.object), meta => meta["correlationId"]), Stdlib_JSON.Decode.string);
}

export {
  make,
  makeBundled,
  makeBundledFromEntryPoint,
  groupBySource,
  extractCorrelationId,
}
/* @pulumi/aws Not a pure module */
