// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function NoResolvers(Config) {
  var make = function (param, param$1, param$2, param$3, param$4, param$5, param$6, param$7, param$8) {
    return {
            resources: [],
            resourcesMaker: (function (param) {
                return [];
              })
          };
  };
  return {
          make: make
        };
}

exports.NoResolvers = NoResolvers;
/* No side effect */
