// Generated by ReScript, PLEASE EDIT WITH CARE


function mapIncomingCommand(_id, _command, _meta) {
  return [];
}

let mapOutgoingEvent = (_id, event, _meta, _queryEngine) => {
  if (typeof event !== "object") {
    return [];
  }
  switch (event.TAG) {
    case "Placed" :
      let customerId = event.customerId;
      return event.productIds.map(productId => ({
        TAG: "PublishEvent",
        _0: productId,
        _1: {
          TAG: "ItemOrdered",
          productId: productId,
          orderId: _id,
          customerId: customerId
        }
      }));
    case "Cancelled" :
      return event.productIds.map(productId => ({
        TAG: "PublishEvent",
        _0: productId,
        _1: {
          TAG: "ItemOrderCancelled",
          productId: productId,
          orderId: _id
        }
      }));
    case "Refunded" :
      return [];
  }
};

let name = "Orders";

let Id;

let ExtensionPoint;

let Delegate;

let moduleUrl = "@reventlessdev/online-shop-aggregates-ordering/src/ExtensionPoint/Orders_ExtensionPointMapping.res.mjs";

export {
  name,
  Id,
  ExtensionPoint,
  Delegate,
  mapIncomingCommand,
  mapOutgoingEvent,
  moduleUrl,
}
/* No side effect */
