// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");
var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var Aws = require("@pulumi/aws");
var Caml_option = require("@rescript/std/lib/js/caml_option.js");
var Lambda$PulumiAws = require("@reventless/bs-pulumi-aws/src/Lambda/Lambda.bs.js");
var SQS_Queue$PulumiAws = require("@reventless/bs-pulumi-aws/src/SQS/SQS_Queue.bs.js");
var Util_SQS_FIFO$ReventlessAws = require("../../util/Util_SQS_FIFO.bs.js");
var Util_SqsQueuePolicy$ReventlessAws = require("../../util/Util_SqsQueuePolicy.bs.js");
var Util_DeadLetterQueue$ReventlessAws = require("../../util/Util_DeadLetterQueue.bs.js");
var CommandTopicConnector_SQS_Runtime$ReventlessAws = require("./CommandTopicConnector_SQS_Runtime.bs.js");

function make(name, handleCommands, memorySize, timeout, opts) {
  var queue = new (Aws.sqs.Queue)(name, {
        contentBasedDeduplication: true,
        fifoQueue: true,
        redrivePolicy: Util_DeadLetterQueue$ReventlessAws.fifoQueue.arn.apply(function (dlqArn) {
              return Curry._2(SQS_Queue$PulumiAws.Args.RedrivePolicy.make, dlqArn, 5);
            }),
        tags: Js_dict.fromArray([
              [
                "Name",
                name
              ],
              [
                "Type",
                "CommandTopic"
              ]
            ]),
        visibilityTimeoutSeconds: Math.imul(6, timeout),
        deduplicationScope: "messageGroup",
        fifoThroughputLimit: "perMessageGroupId",
        sqsManagedSseEnabled: false
      }, opts);
  Util_SqsQueuePolicy$ReventlessAws.make(name, queue, [Util_SqsQueuePolicy$ReventlessAws.allowCloudWatchEvents], Caml_option.some(opts), undefined);
  var handler = new (Aws.lambda.CallbackFunction)(name, Curry.app(Lambda$PulumiAws.CallbackFunction.Args.make, [
            (function (param, param$1) {
                return CommandTopicConnector_SQS_Runtime$ReventlessAws.handleQueueEvent(handleCommands, queue, param, param$1);
              }),
            undefined,
            Lambda$PulumiAws.Policy.defaultPolicies,
            undefined,
            undefined,
            Caml_option.some(memorySize),
            Caml_option.some(timeout),
            undefined,
            undefined,
            undefined,
            Caml_option.some(Js_dict.fromArray([
                      [
                        "Name",
                        name
                      ],
                      [
                        "Type",
                        "CommandTopic"
                      ]
                    ])),
            undefined
          ]), opts);
  queue.onEvent(name, handler, undefined, opts);
  return {
          resources: [Util_SQS_FIFO$ReventlessAws.toResource(queue)],
          publish: CommandTopicConnector_SQS_Runtime$ReventlessAws.publish(queue, Util_SQS_FIFO$ReventlessAws.service)
        };
}

exports.make = make;
/* @pulumi/aws Not a pure module */
