// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as AwsNative from "@pulumi/aws-native";
import * as AwsNative_AppSync_Api$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/AwsNative/AppSync/AwsNative_AppSync_Api.res.mjs";

function make(name, opts) {
  let iamMode = {
    authType: AwsNative_AppSync_Api$PulumiAws.awsIam
  };
  let iamProvider = {
    authType: AwsNative_AppSync_Api$PulumiAws.awsIam
  };
  let api = new (AwsNative.appsync.Api)(name, {
    eventConfig: {
      authProviders: [iamProvider],
      connectionAuthModes: [iamMode],
      defaultPublishAuthModes: [iamMode],
      defaultSubscribeAuthModes: [iamMode]
    }
  }, opts);
  let newrecord = {...opts};
  let defaultNamespace = new (AwsNative.appsync.ChannelNamespace)(name + "DefaultNS", {
    apiId: api.apiId,
    name: "default"
  }, (newrecord.parent = api, newrecord));
  return {
    api: api,
    defaultNamespace: defaultNamespace
  };
}

function httpEndpoint(eventsApi) {
  return eventsApi.api.dns.apply(dns => "https://" + Stdlib_Option.getOr(dns.http, ""));
}

let Api;

let ChannelNamespace;

export {
  Api,
  ChannelNamespace,
  make,
  httpEndpoint,
}
/* @pulumi/aws-native Not a pure module */
