// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";

let consumedEventSchema = S.union([
  S.literal("CategoryAdded"),
  S.literal("CategoryArchived")
]);

let commandSchema = S.schema(s => ({
  TAG: "AddCategory",
  categoryId: s.m(DcbTag$Reventless.string),
  name: s.m(S.string)
}));

let errorSchema = S.literal("CategoryAlreadyExists");

let eventSchema = S.schema(s => ({
  TAG: "CategoryAdded",
  categoryId: s.m(DcbTag$Reventless.string),
  name: s.m(S.string)
}));

let name = "AddCategory";

let Id;

let moduleUrl = "@reventlessdev/online-shop-dcb-catalog/src/Category/StateChangeSlice/AddCategory.res.mjs";

export {
  name,
  Id,
  consumedEventSchema,
  commandSchema,
  errorSchema,
  eventSchema,
  moduleUrl,
}
/* consumedEventSchema Not a pure module */
