// Generated by ReScript, PLEASE EDIT WITH CARE


function evolve(state, event) {
  if (typeof event !== "object") {
    return {
      exists: state.exists,
      archived: true,
      name: state.name
    };
  } else if (event.TAG === "CategoryAdded") {
    return {
      exists: true,
      archived: false,
      name: event.name
    };
  } else {
    return {
      exists: state.exists,
      archived: state.archived,
      name: event.name
    };
  }
}

function decide(state, command) {
  if (!state.exists) {
    return {
      TAG: "Error",
      _0: "CategoryNotFound"
    };
  }
  if (state.archived) {
    return {
      TAG: "Error",
      _0: "CategoryAlreadyArchived"
    };
  }
  let name = command.name;
  if (name === state.name) {
    return {
      TAG: "Ok",
      _0: []
    };
  } else {
    return {
      TAG: "Ok",
      _0: [{
          TAG: "CategoryRenamed",
          categoryId: command.categoryId,
          name: name
        }]
    };
  }
}

let Spec;

let initialState = {
  exists: false,
  archived: false,
  name: ""
};

let moduleUrl = "@reventlessdev/online-shop-dcb-catalog/src/Category/StateChangeSlice/RenameCategory_Behavior.res.mjs";

export {
  Spec,
  initialState,
  evolve,
  decide,
  moduleUrl,
}
/* No side effect */
