// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Id$Reventless from "@reventlessdev/reventless-spec/src/types/Id.res.mjs";
import * as Product$CatalogPlugin from "../../src/Product/Aggregate/Product.res.mjs";
import * as Delegate_GWT$ReventlessGwt from "@reventlessdev/reventless-gwt/src/Delegate_GWT.res.mjs";
import * as Products_ExtensionPoint$CatalogSpec from "@reventlessdev/online-shop-aggregates-catalog-spec/src/Products_ExtensionPoint.res.mjs";
import * as Products_ExtensionPointMapping$CatalogPlugin from "../../src/ExtensionPoint/Products_ExtensionPointMapping.res.mjs";

let include = Delegate_GWT$ReventlessGwt.FromExtensionPoint({
  ExtensionPoint: {
    name: Products_ExtensionPoint$CatalogSpec.name,
    moduleUrl: Products_ExtensionPoint$CatalogSpec.moduleUrl,
    commandSchema: Products_ExtensionPoint$CatalogSpec.commandSchema,
    eventSchema: Products_ExtensionPoint$CatalogSpec.eventSchema,
    directiveSchema: Products_ExtensionPoint$CatalogSpec.directiveSchema
  },
  Delegate: {
    Id: Id$Reventless.$$String,
    name: Product$CatalogPlugin.name,
    eventSchema: Product$CatalogPlugin.eventSchema,
    errorSchema: Product$CatalogPlugin.errorSchema,
    commandSchema: Product$CatalogPlugin.commandSchema,
    moduleUrl: Product$CatalogPlugin.moduleUrl,
    commandAuthorization: Product$CatalogPlugin.commandAuthorization
  },
  moduleUrl: Products_ExtensionPointMapping$CatalogPlugin.moduleUrl,
  mapIncomingCommand: Products_ExtensionPointMapping$CatalogPlugin.mapIncomingCommand,
  mapOutgoingEvent: Products_ExtensionPointMapping$CatalogPlugin.mapOutgoingEvent
});

let describe = include.describe;

let test = include.test;

let thenPublishesNothing = include.thenPublishesNothing;

let whenDelegateEvent = include.whenDelegateEvent;

let thenPublishesEvent = include.thenPublishesEvent;

describe("Products ExtensionPoint mapping", () => {
  test("Added publishes ProductBecameAvailable", undefined, () => thenPublishesEvent(whenDelegateEvent({
    TAG: "Added",
    name: "Book",
    description: "A good book",
    price: 9.99
  }), "gwt-id", {
    TAG: "ProductBecameAvailable",
    productId: "gwt-id",
    name: "Book",
    price: 9.99
  }));
  test("PriceUpdated publishes ProductPriceChanged", undefined, () => thenPublishesEvent(whenDelegateEvent({
    TAG: "PriceUpdated",
    price: 7.5
  }), "gwt-id", {
    TAG: "ProductPriceChanged",
    productId: "gwt-id",
    price: 7.5
  }));
  test("NameUpdated publishes nothing", undefined, () => thenPublishesNothing(whenDelegateEvent({
    TAG: "NameUpdated",
    name: "Better Book"
  })));
  test("DescriptionUpdated publishes nothing", undefined, () => thenPublishesNothing(whenDelegateEvent({
    TAG: "DescriptionUpdated",
    description: "A really good book"
  })));
});

let encEvent = include.encEvent;

let encCommand = include.encCommand;

let encDirective = include.encDirective;

let EvCore = include.EvCore;

let CmdCore = include.CmdCore;

let thenPublishesEvents = include.thenPublishesEvents;

let whenIncomingCommand = include.whenIncomingCommand;

let thenPublishesCommand = include.thenPublishesCommand;

let thenPublishesCommands = include.thenPublishesCommands;

let thenHandlesDirective = include.thenHandlesDirective;

let thenHandlesDirectives = include.thenHandlesDirectives;

let thenHandlesNoDirective = include.thenHandlesNoDirective;

export {
  encEvent,
  encCommand,
  encDirective,
  EvCore,
  CmdCore,
  describe,
  test,
  thenPublishesNothing,
  whenDelegateEvent,
  thenPublishesEvent,
  thenPublishesEvents,
  whenIncomingCommand,
  thenPublishesCommand,
  thenPublishesCommands,
  thenHandlesDirective,
  thenHandlesDirectives,
  thenHandlesNoDirective,
}
/* include Not a pure module */
