// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("@rescript/std/lib/js/curry.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var Output$Pulumi = require("@reventless/bs-pulumi-pulumi/src/Output.res.js");
var Task$Reventless = require("./Task.res.js");
var Aggregate$Reventless = require("../Aggregate/Aggregate.res.js");
var Component$Reventless = require("../Component.res.js");
var Util_Promise$Reventless = require("../../util/Util_Promise.res.js");
var ComponentType$Reventless = require("../../ComponentType.res.js");

function Make(Spec, RuntimeEnvironment, EventCollectorChannel, EventCollectorRuntimeBuilder, TaskRuntimeBuilder, TaskBucket, SpecificSideEffectHandler) {
  var make = function (queryBucketName, scheduler, publishToAggregates, queryEngine, allAggregates, opts) {
    return Component$Reventless.make(ComponentType$Reventless.toString(Task$Reventless.componentType), Spec.name, (function (extra, extra$1) {
                  var opts_parent = Component$Reventless.toPulumiResource(extra);
                  var opts = {
                    parent: opts_parent
                  };
                  var allCommandTopics = Aggregate$Reventless.allCommandTopics(allAggregates);
                  var publishCommands = function (aggregateName, cmdJsons) {
                    return Core__Option.getExn(publishToAggregates[aggregateName], undefined)(cmdJsons);
                  };
                  var config = Spec.setup(queryEngine, queryBucketName, opts);
                  var sideEffectHandler = Core__Option.map(config.sideEffects, (function (sideEffects) {
                          return SpecificSideEffectHandler.make(extra$1, sideEffects, Aggregate$Reventless.allEventTopics(allAggregates), allCommandTopics, undefined, queryEngine, scheduler, undefined, undefined, opts);
                        }));
                  var taskActionsHandler = function (taskActions, operations) {
                    return Util_Promise$Reventless.toUnit(Promise.all(taskActions.map(async function (taskAction) {
                                        switch (taskAction.TAG) {
                                          case "PublishCommands" :
                                              return await publishCommands(taskAction._0, taskAction._1);
                                          case "CreateSchedule" :
                                              if (operations !== undefined) {
                                                return await operations.createSchedule(taskAction._0);
                                              } else {
                                                console.log("No SideEffectHandler to create schedule");
                                                return ;
                                              }
                                          case "DeleteSchedule" :
                                              if (operations !== undefined) {
                                                return await operations.deleteSchedule(taskAction._0);
                                              } else {
                                                console.log("No SideEffectHandler to delete schedule");
                                                return ;
                                              }
                                          
                                        }
                                      })));
                  };
                  var createHandler = function (sideEffectHandler, callback) {
                    return Output$Pulumi.allOpt(Core__Option.map(sideEffectHandler, (function (sideEffectHandler) {
                                        return Component$Reventless.operations(sideEffectHandler);
                                      }))).apply(function (operations) {
                                return async function ($$event, context) {
                                  var handler = TaskBucket.makeHandler(callback);
                                  var taskActions = await handler($$event, context);
                                  return await taskActionsHandler(taskActions, operations);
                                };
                              });
                  };
                  var bucketNames = Core__Option.map(config.buckets, (function (buckets) {
                          return Object.fromEntries(buckets.map(function (bucketSpec) {
                                          var bucketName = Core__Option.getOr(bucketSpec.bucketName, "Bucket");
                                          var name = extra$1 + bucketName;
                                          var bucket = TaskBucket.make(name, opts);
                                          var opts_parent = bucket.parts;
                                          var opts$1 = {
                                            parent: opts_parent
                                          };
                                          Core__Option.forEach(bucketSpec.callback, (function (callback) {
                                                  TaskRuntimeBuilder.forBucketCallback(createHandler(sideEffectHandler, callback), (function (none) {
                                                          return Curry._6(TaskBucket.connect, name, bucket, bucketSpec.bucketMode, allCommandTopics, none, opts$1);
                                                        }), 4096, 600, bucketName, extra);
                                                }));
                                          return [
                                                  bucketName,
                                                  bucket.resources[0].id
                                                ];
                                        }));
                        }));
                  var sideEffectSources = Core__Option.map(config.sideEffects, (function (sideEffect) {
                          return sideEffect.map(function (SideEffect) {
                                      return SideEffect.Source.name;
                                    });
                        }));
                  return Component$Reventless.setOutputs(extra, {
                              name: extra$1,
                              bucketNames: bucketNames,
                              sideEffectSources: sideEffectSources
                            });
                }), opts);
  };
  return {
          Spec: Spec,
          make: make
        };
}

exports.Make = Make;
/* Output-Pulumi Not a pure module */
