// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Pulumi from "@pulumi/pulumi";
import * as QueryDb$Reventless from "../../components/QueryDb/QueryDb.res.mjs";
import * as Component$Reventless from "../../components/Component.res.mjs";
import * as Core_Callback$Reventless from "./Core_Callback.res.mjs";
import * as Plugin_Helpers$Reventless from "../../components/Plugin/Plugin_Helpers.res.mjs";
import * as EventCollector_Builder$Reventless from "../../components/EventCollector/EventCollector_Builder.res.mjs";

function createResolvers(allQueryDbs) {
  return QueryDb$Reventless.allResolversMakers(allQueryDbs).map(resolverMaker => resolverMaker(allQueryDbs)).flat();
}

function MakeEventCollectorHelper(RuntimeEnvironment) {
  return EventCollectorChannel => (CoreRuntimeBuilder => {
    let CoreEventCollector = EventCollector_Builder$Reventless.Make(RuntimeEnvironment)(EventCollectorChannel);
    let make = (name, eventTopics, opts) => {
      let eventCollector = CoreEventCollector.make(name, eventTopics, opts);
      let eventCollectorOutputs = Component$Reventless.outputs(eventCollector);
      return [
        eventCollector,
        eventCollectorOutputs
      ];
    };
    let connect = (eventCollector, eventTopics, extensionPointsOutputs, extensionPointsOutgoingEventHandlers) => {
      let resources = Pulumi.all(extensionPointsOutputs.map(extensionPoint => extensionPoint.eventTopic)).apply(eventTopics => eventTopics.map(eventTopic => eventTopic.resources).flat());
      return resources.apply(resources => {
        let fakePluginDefinition = {
          id: "Core@FAKE",
          name: "Core",
          version: "FAKE",
          extensionPoints: [],
          extensions: [],
          eventCollector: "NOT-SET"
        };
        let Callback = Core_Callback$Reventless.Make({
          pluginDefinition: fakePluginDefinition,
          outgoingExtensionPointEventHandlers: extensionPointsOutgoingEventHandlers
        });
        let handler = CoreEventCollector.makeHandler(eventCollector, Callback.handleJsonEvents);
        CoreRuntimeBuilder.forPluginEventCollector(handler, eventTopics, resources, undefined, undefined, eventCollector);
      });
    };
    return {
      CoreEventCollector: CoreEventCollector,
      make: make,
      connect: connect
    };
  });
}

let addEventMapperFns = Plugin_Helpers$Reventless.addEventMapperFns;

let aggregateResources = Plugin_Helpers$Reventless.aggregateResources;

let publishToAggregates = Plugin_Helpers$Reventless.publishToAggregates;

let createAggregatesWithoutEventMappers = Plugin_Helpers$Reventless.createAggregatesWithoutEventMappers;

let addEventMappers = Plugin_Helpers$Reventless.addEventMappers;

let createReadModels = Plugin_Helpers$Reventless.createReadModels;

let createExtensionPoints = Plugin_Helpers$Reventless.createExtensionPoints;

export {
  addEventMapperFns,
  aggregateResources,
  publishToAggregates,
  createAggregatesWithoutEventMappers,
  addEventMappers,
  createReadModels,
  createExtensionPoints,
  createResolvers,
  MakeEventCollectorHelper,
}
/* @pulumi/pulumi Not a pure module */
