// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var Logger$Reventless = require("../../util/Logger.res.js");
var Util_Promise$Reventless = require("../../util/Util_Promise.res.js");

function Make(Spec) {
  var eventsHandler = function (events$pJson) {
    var count = events$pJson.length;
    return Util_Promise$Reventless.toUnit(Promise.all(Belt_Array.mapWithIndex(events$pJson, (async function (idx, event$pJson) {
                          var idx$1 = idx + 1 | 0;
                          Logger$Reventless.logEvent$pJson(undefined, undefined, event$pJson, "Core eventHandler: outgoing event " + String(idx$1) + "/" + String(count) + ":");
                          return Util_Promise$Reventless.toUnit(Promise.all(Belt_Array.map(Spec.outgoingExtensionPointEventHandlers, (function (handleEvent) {
                                                return handleEvent(event$pJson, Spec.pluginDefinition);
                                              }))));
                        }))));
  };
  return {
          eventsHandler: eventsHandler
        };
}

exports.Make = Make;
/* Logger-Reventless Not a pure module */
