// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sury from "sury";
import * as Money$Reventless from "@reventlessdev/reventless-spec/src/semantic/Money.res.mjs";
import * as ReadModel$Reventless from "@reventlessdev/reventless-spec/src/components/ReadModel.res.mjs";
import * as CaptionedImage$Reventless from "@reventlessdev/reventless-spec/src/semantic/CaptionedImage.res.mjs";
import * as UploadableImage$Reventless from "@reventlessdev/reventless-spec/src/semantic/UploadableImage.res.mjs";
import * as StateAnnotations$Reventless from "@reventlessdev/reventless-spec/src/components/StateAnnotations.res.mjs";

let consumedEventSchema = Sury.union([
  Sury.$schema(s => ({
    TAG: "ProductAdded",
    productId: s.m(Sury.string),
    name: s.m(Sury.string),
    description: s.m(Sury.string),
    price: s.m(Money$Reventless.schema),
    categoryId: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "ProductPriceChanged",
    productId: s.m(Sury.string),
    price: s.m(Money$Reventless.schema)
  })),
  Sury.$schema(s => ({
    TAG: "ProductNameChanged",
    productId: s.m(Sury.string),
    name: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "ProductDescriptionChanged",
    productId: s.m(Sury.string),
    description: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "ProductImageAttached",
    productId: s.m(Sury.string),
    productImage: s.m(UploadableImage$Reventless.forField(undefined, "productImages")),
    altText: s.m(Sury.$option(Sury.string))
  })),
  Sury.$schema(s => ({
    TAG: "ProductImageRemoved",
    productId: s.m(Sury.string),
    productImage: s.m(UploadableImage$Reventless.forField(undefined, "productImages"))
  })),
  Sury.$schema(s => ({
    TAG: "ProductPrimaryImageSet",
    productId: s.m(Sury.string),
    productImage: s.m(UploadableImage$Reventless.forField(undefined, "productImages"))
  })),
  Sury.$schema(s => ({
    TAG: "ProductImageAltTextSet",
    productId: s.m(Sury.string),
    productImage: s.m(UploadableImage$Reventless.forField(undefined, "productImages")),
    altText: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "ProductArchived",
    productId: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "ProductUnarchived",
    productId: s.m(Sury.string)
  })),
  Sury.$schema(s => ({
    TAG: "ProductDiscontinued",
    productId: s.m(Sury.string)
  }))
]);

let shelfStatusSchema = Sury.union([
  Sury.literal("Listed"),
  Sury.literal("Archived"),
  Sury.literal("Discontinued")
]);

let stateSchema = Sury.$schema(s => ({
  productId: s.m(Sury.string),
  name: s.m(Sury.string),
  description: s.m(Sury.string),
  price: s.m(Money$Reventless.schema),
  productImages: s.m(Sury.array(CaptionedImage$Reventless.forField(undefined, "productImages"))),
  categoryId: s.m(Sury.string),
  shelfStatus: s.m(shelfStatusSchema)
}));

let config = ReadModel$Reventless.config(undefined, undefined, [{
    index: "categoryId",
    type_: "S",
    projectionType: "ALL"
  }]);

let stateSchema$1 = Sury.$Metadata_set(stateSchema, StateAnnotations$Reventless.stateAnnotationsId, {
  ids: [],
  compositeIds: [],
  subIds: [],
  compositeSubIds: [],
  indexes: [[
      "categoryId",
      ""
    ]],
  hidden: [],
  summary: [],
  internal: [],
  drillTargets: [],
  drillTargetKeys: [],
  collapsed: [],
  scan: [],
  scanSort: [],
  semantic: [],
  metric: [],
  lifecycle: "shelfStatus",
  groupBy: undefined,
  visibility: undefined,
  live: undefined,
  retired: {
    field: "shelfStatus",
    label: "",
    showWhenFalse: false,
    values: [
      "Archived",
      "Discontinued"
    ],
    namedWhenRetired: true
  }
});

let name = "Products";

let Id;

let subIdConfig;

let moduleUrl = "@reventlessdev/online-shop-hybrid-catalog/src/Product/StateViewSliceStream/Products.res.mjs";

let authorization = "AllowAuthenticated";

let visibility = "Public";

export {
  name,
  Id,
  consumedEventSchema,
  shelfStatusSchema,
  config,
  subIdConfig,
  stateSchema$1 as stateSchema,
  moduleUrl,
  authorization,
  visibility,
}
/* consumedEventSchema Not a pure module */
