// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("@rescript/std/lib/js/belt_Array.js");
var DynamoDb_DocumentClient$AwsSdk = require("@reventless/bs-aws-sdk/src/DynamoDb_DocumentClient.bs.js");
var Util_DynamoDb_Runtime$ReventlessAws = require("../../util/Util_DynamoDb_Runtime.bs.js");

function append(table) {
  return async function (_sequenceNr, _id, jsons) {
    var result = Util_DynamoDb_Runtime$ReventlessAws.batchWriteWithRetries(undefined, undefined, Util_DynamoDb_Runtime$ReventlessAws.toTable(Belt_Array.map(jsons, Util_DynamoDb_Runtime$ReventlessAws.toPutRequest), table.name.get()));
    var unprocessedItems;
    try {
      unprocessedItems = await result;
    }
    catch (exn){
      return {
              TAG: /* Error */1,
              _0: "AwsSdk.DynamoDb.DocumentClient.batchWriteWithRetries failed !"
            };
    }
    if (unprocessedItems.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: undefined
            };
    }
    console.log("Error: unprocessed items:", unprocessedItems._0);
    return {
            TAG: /* Error */1,
            _0: "AwsSdk.DynamoDb.DocumentClient.batchWriteWithRetries resulted in unprocessed items !"
          };
  };
}

function replay(table) {
  return function (id) {
    return DynamoDb_DocumentClient$AwsSdk.queryById(table.name.get(), id);
  };
}

exports.append = append;
exports.replay = replay;
/* DynamoDb_DocumentClient-AwsSdk Not a pure module */
