// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("@rescript/std/lib/js/js_dict.js");
var Core__Option = require("@rescript/core/src/Core__Option.res.js");
var Pulumi = require("@pulumi/pulumi");
var PolicyDocument$PulumiAws = require("../IAM/PolicyDocument.res.js");

function make(callback, role, policies, deadLetterConfig, tracingConfig, memorySizeOpt, timeoutOpt, runtimeOpt, layersOpt, vpcConfig, tags, environmentOpt) {
  var memorySize = memorySizeOpt !== undefined ? memorySizeOpt : 1024;
  var timeout = timeoutOpt !== undefined ? timeoutOpt : 180;
  var runtime = runtimeOpt !== undefined ? runtimeOpt : "nodejs22.x";
  var layers = layersOpt !== undefined ? layersOpt : Core__Option.getOr(Core__Option.map(process.env.REVENTLESS_LAYER_ARN, (function (arn) {
                return [arn];
              })), []);
  var environment = environmentOpt !== undefined ? environmentOpt : ({
        variables: Js_dict.fromArray([[
                "Environment",
                Pulumi.getStack()
              ]])
      });
  return {
          callback: callback,
          runtime: runtime,
          role: role,
          policies: policies,
          deadLetterConfig: deadLetterConfig,
          tracingConfig: tracingConfig,
          memorySize: memorySize,
          timeout: timeout,
          layers: layers,
          vpcConfig: vpcConfig,
          tags: tags,
          environment: environment
        };
}

var Args = {
  make: make
};

var CallbackFunction = {
  Args: Args
};

var Permission = {};

var defaultLoggingPolicyDocument = PolicyDocument$PulumiAws.make(undefined, undefined, [{
        Sid: "DefaultLambdaLoggingPolicy",
        Effect: "Allow",
        Action: [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ],
        Resource: "arn:aws:logs:*:*:*"
      }]);

exports.CallbackFunction = CallbackFunction;
exports.Permission = Permission;
exports.defaultLoggingPolicyDocument = defaultLoggingPolicyDocument;
/* defaultLoggingPolicyDocument Not a pure module */
