// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as TestRunner$ReventlessInMemory from "../../../src/test/TestRunner.res.mjs";
import * as TaskFixtures$ReventlessInMemory from "./TaskFixtures.res.mjs";

describe("Task_Builder.Make:", () => {
  beforeEach(() => TaskFixtures$ReventlessInMemory.resetCaptures());
  describe("make — no buckets:", () => {
    test("creates component with correct output name", async () => {
      let task = TaskFixtures$ReventlessInMemory.NoBucketsMaker.make(TaskFixtures$ReventlessInMemory.mockQueryBucketName, TaskFixtures$ReventlessInMemory.mockScheduler, TaskFixtures$ReventlessInMemory.mockPublishToAggregates, TaskFixtures$ReventlessInMemory.mockQueryEngine, TaskFixtures$ReventlessInMemory.mockResourceNaming, {}, undefined);
      let outputs = TaskFixtures$ReventlessInMemory.NoBucketsMaker.outputs(task);
      expect(outputs.name).toBe("NoBucketsTask");
    });
    test("task with no buckets has no bucketNames in outputs", async () => {
      let task = TaskFixtures$ReventlessInMemory.NoBucketsMaker.make(TaskFixtures$ReventlessInMemory.mockQueryBucketName, TaskFixtures$ReventlessInMemory.mockScheduler, TaskFixtures$ReventlessInMemory.mockPublishToAggregates, TaskFixtures$ReventlessInMemory.mockQueryEngine, TaskFixtures$ReventlessInMemory.mockResourceNaming, {}, undefined);
      let outputs = TaskFixtures$ReventlessInMemory.NoBucketsMaker.outputs(task);
      expect(Stdlib_Option.isSome(outputs.bucketNames)).toBe(false);
    });
  });
  describe("make — one named bucket with callback:", () => {
    test("creates component with correct output name", async () => {
      let task = TaskFixtures$ReventlessInMemory.OneBucketMaker.make(TaskFixtures$ReventlessInMemory.mockQueryBucketName, TaskFixtures$ReventlessInMemory.mockScheduler, TaskFixtures$ReventlessInMemory.mockPublishToAggregates, TaskFixtures$ReventlessInMemory.mockQueryEngine, TaskFixtures$ReventlessInMemory.mockResourceNaming, {}, undefined);
      let outputs = TaskFixtures$ReventlessInMemory.OneBucketMaker.outputs(task);
      expect(outputs.name).toBe("OneBucketTask");
    });
    test("bucketNames dict contains the named bucket key", async () => {
      let task = TaskFixtures$ReventlessInMemory.OneBucketMaker.make(TaskFixtures$ReventlessInMemory.mockQueryBucketName, TaskFixtures$ReventlessInMemory.mockScheduler, TaskFixtures$ReventlessInMemory.mockPublishToAggregates, TaskFixtures$ReventlessInMemory.mockQueryEngine, TaskFixtures$ReventlessInMemory.mockResourceNaming, {}, undefined);
      let outputs = TaskFixtures$ReventlessInMemory.OneBucketMaker.outputs(task);
      let bucketNames = outputs.bucketNames;
      expect(Object.keys(bucketNames)).toEqual(["Reports"]);
    });
    test("bucket id resolves to the bucket name (in-memory dummy resource)", async () => {
      let task = TaskFixtures$ReventlessInMemory.OneBucketMaker.make(TaskFixtures$ReventlessInMemory.mockQueryBucketName, TaskFixtures$ReventlessInMemory.mockScheduler, TaskFixtures$ReventlessInMemory.mockPublishToAggregates, TaskFixtures$ReventlessInMemory.mockQueryEngine, TaskFixtures$ReventlessInMemory.mockResourceNaming, {}, undefined);
      let outputs = TaskFixtures$ReventlessInMemory.OneBucketMaker.outputs(task);
      let bucketNames = outputs.bucketNames;
      let idOutput = bucketNames["Reports"];
      let id = await TestRunner$ReventlessInMemory.resolve(idOutput);
      expect(id).toBe("OneBucketTaskReports");
    });
  });
});

/*  Not a pure module */
