// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.res.mjs";
import * as Output$Pulumi from "@reventlessdev/rescript-pulumi-pulumi/src/Output.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Pulumi from "@pulumi/pulumi";
import * as Belt_SetString from "@rescript/runtime/lib/es6/Belt_SetString.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as DcbTag$Reventless from "@reventlessdev/reventless-spec/src/components/DcbTag.res.mjs";
import * as Plugin$ReventlessCore from "./Plugin.res.mjs";
import * as StackReference$Pulumi from "@reventlessdev/rescript-pulumi-pulumi/src/StackReference.res.mjs";
import * as Adapter$ReventlessCore from "../../adapter/Adapter.res.mjs";
import * as Aggregate$ReventlessCore from "../Aggregate/Aggregate.res.mjs";
import * as Component$ReventlessCore from "../Component.res.mjs";
import * as ReadModel$ReventlessCore from "../ReadModel/ReadModel.res.mjs";
import * as Api_Naming$ReventlessCore from "../Api/Api_Naming.res.mjs";
import * as Interstack$ReventlessCore from "../../util/Interstack.res.mjs";
import * as PackageVersion$Reventless from "@reventlessdev/reventless-spec/src/PackageVersion.res.mjs";
import * as Dcb_Builder$ReventlessCore from "../Dcb/Dcb_Builder.res.mjs";
import * as SchemaWalker$ReventlessCore from "./SchemaWalker.res.mjs";
import * as ComponentType$ReventlessCore from "../../ComponentType.res.mjs";
import * as ExportMeta$ReventlessInterop from "@reventlessdev/reventless-interop/src/ExportMeta.res.mjs";
import * as ExtensionPoint$ReventlessCore from "../ExtensionPoint/ExtensionPoint.res.mjs";
import * as Plugin_Helpers$ReventlessCore from "./Plugin_Helpers.res.mjs";
import * as ApiNoApiHelpers$ReventlessCore from "../Api/ApiNoApiHelpers.res.mjs";
import * as GraphQL_Stitcher$ReventlessCore from "../Api/GraphQL_Stitcher.res.mjs";
import * as Plugin_Structure$ReventlessCore from "./Plugin_Structure.res.mjs";
import * as AdapterDeploytime$ReventlessCore from "../../adapter/AdapterDeploytime.res.mjs";
import * as ExtensionMapping$ReventlessInfra from "@reventlessdev/reventless-infra/src/types/ExtensionMapping.res.mjs";
import * as ExtensionPoint$ReventlessInterop from "@reventlessdev/reventless-interop/src/components/ExtensionPoint.res.mjs";
import * as Heartbeat_Builder$ReventlessCore from "../Heartbeat/Heartbeat_Builder.res.mjs";
import * as PluginExtensionPointSpec$ReventlessInfra from "@reventlessdev/reventless-infra/src/types/PluginExtensionPointSpec.res.mjs";
import * as Plugin_SubscriptionSchema$ReventlessCore from "./Plugin_SubscriptionSchema.res.mjs";

function Make(Spec) {
  return ApiSpec => (FragmentProvider => (RuntimeEnvironment => (EventCollectorChannel => (QueryEngineAdapter => (PluginExtensionPointRemoteChannel => (HeartbeatRunner => (PluginRuntimeBuilder => (DcbEventLogStorage => (DcbEventTopicPublisher => (DcbCommandTopicChannel => (DcbCommandTopicChannelAsync => {
    let makeAutoUIManifest = (remoteEntryUrl, name, aggregates, readModels, readModelPositionsOpt, aggregatePositionsOpt) => {
      let readModelPositions = readModelPositionsOpt !== undefined ? readModelPositionsOpt : [];
      let aggregatePositions = aggregatePositionsOpt !== undefined ? aggregatePositionsOpt : [];
      let panels = readModels.map(R => ({
        fragmentId: name + "." + R.Spec.name + ".list",
        title: R.Spec.name,
        description: "",
        positions: readModelPositions,
        requiredAccess: undefined
      })).concat(aggregates.map(M => ({
        fragmentId: name + "." + M.Spec.name + ".detail",
        title: M.Spec.name,
        description: "",
        positions: aggregatePositions,
        requiredAccess: undefined
      })));
      let pages = readModels.map(R => ({
        fragmentId: name + "." + R.Spec.name + ".list",
        title: R.Spec.name,
        menuEntry: {
          label: R.Spec.name,
          icon: undefined,
          group: undefined,
          sortOrder: 0
        },
        requiredAccess: undefined
      }));
      return {
        remoteEntryUrl: remoteEntryUrl,
        panels: panels,
        pages: pages
      };
    };
    let makePluginDefinition = (name, aggregatesOpt, readModelsOpt, stateViewSlicesOpt, stateChangeSlicesOpt, automationSlicesOpt, outboundTranslationSlicesOpt, inboundTranslationSlicesOpt, extensionsOpt) => {
      let aggregates = aggregatesOpt !== undefined ? aggregatesOpt : [];
      let readModels = readModelsOpt !== undefined ? readModelsOpt : [];
      let stateViewSlices = stateViewSlicesOpt !== undefined ? stateViewSlicesOpt : [];
      let stateChangeSlices = stateChangeSlicesOpt !== undefined ? stateChangeSlicesOpt : [];
      let automationSlices = automationSlicesOpt !== undefined ? automationSlicesOpt : [];
      let outboundTranslationSlices = outboundTranslationSlicesOpt !== undefined ? outboundTranslationSlicesOpt : [];
      let inboundTranslationSlices = inboundTranslationSlicesOpt !== undefined ? inboundTranslationSlicesOpt : [];
      let extensions = extensionsOpt !== undefined ? extensionsOpt : [];
      return Plugin_Structure$ReventlessCore.make(name, aggregates, readModels, stateViewSlices, stateChangeSlices, automationSlices, outboundTranslationSlices, inboundTranslationSlices, extensions);
    };
    let make = (name, heartbeatInterval, extensionPointsOpt, extensionsOpt, aggregatesOpt, readModelsOpt, tasksOpt, stateChangeSlicesOpt, stateViewSlicesOpt, automationSlicesOpt, outboundTranslationSlicesOpt, inboundTranslationSlicesOpt, uiFragments, pluginStructure, opts) => {
      let extensionPoints = extensionPointsOpt !== undefined ? extensionPointsOpt : [];
      let extensions = extensionsOpt !== undefined ? extensionsOpt : [];
      let aggregates = aggregatesOpt !== undefined ? aggregatesOpt : [];
      let readModels = readModelsOpt !== undefined ? readModelsOpt : [];
      let tasks = tasksOpt !== undefined ? tasksOpt : [];
      let stateChangeSlices = stateChangeSlicesOpt !== undefined ? stateChangeSlicesOpt : [];
      let stateViewSlices = stateViewSlicesOpt !== undefined ? stateViewSlicesOpt : [];
      let automationSlices = automationSlicesOpt !== undefined ? automationSlicesOpt : [];
      let outboundTranslationSlices = outboundTranslationSlicesOpt !== undefined ? outboundTranslationSlicesOpt : [];
      let inboundTranslationSlices = inboundTranslationSlicesOpt !== undefined ? inboundTranslationSlicesOpt : [];
      PluginRuntimeBuilder.registerPluginName(name);
      let version = PackageVersion$Reventless.fromCaller();
      return Component$ReventlessCore.make(ComponentType$ReventlessCore.toString(Plugin$ReventlessCore.componentType), name, (extra, extra$1) => {
        let s = Spec.hooks.scheduler.contents;
        let scheduler = s !== undefined ? s : Stdlib_JsError.throwWithMessage("Plugin_Builder: scheduler not set — call makePlatform/deployPlugin first");
        let match = Spec.hooks.api.contents;
        let api = match !== undefined ? match.val : Stdlib_JsError.throwWithMessage("Plugin_Builder: api not set — call makePlatform/deployPlugin first");
        let match$1 = Spec.hooks.apiRole.contents;
        let apiRole = match$1 !== undefined ? match$1.val : Stdlib_JsError.throwWithMessage("Plugin_Builder: apiRole not set — call makePlatform/deployPlugin first");
        let id = Plugin$ReventlessCore.makeId(extra$1, version);
        let opts_parent = Component$ReventlessCore.toPulumiResource(extra);
        let opts = {
          parent: opts_parent
        };
        let childName = ComponentType$ReventlessCore.name(extra$1, Plugin$ReventlessCore.componentType);
        let DcbBuilder = Dcb_Builder$ReventlessCore.Make(DcbEventLogStorage)(DcbEventTopicPublisher)(DcbCommandTopicChannel)(DcbCommandTopicChannelAsync)(PluginRuntimeBuilder)({
          hooks: Spec.hooks
        });
        let dcbResult = DcbBuilder.construct(extra$1, childName, stateChangeSlices, stateViewSlices, automationSlices, outboundTranslationSlices, inboundTranslationSlices, pluginStructure, opts);
        let mutationEntriesFromAggregates = aggregates.flatMap(M => {
          let commandSchema = M.Spec.commandSchema;
          if (ApiNoApiHelpers$ReventlessCore.isNoApi(commandSchema)) {
            return [];
          }
          let constructorNames = DcbTag$Reventless.extractVariantNames(M.Spec.commandSchema);
          let filteredConstructorNames = ApiNoApiHelpers$ReventlessCore.filterNoApiVariants(constructorNames, commandSchema);
          let fieldNames = filteredConstructorNames.map(cname => Api_Naming$ReventlessCore.aggregateMutationField(extra$1, M.Spec.name, cname));
          Plugin_Helpers$ReventlessCore.aggregateMutationFieldsRegistry[M.Spec.name] = fieldNames;
          if (fieldNames.length === 0) {
            return [];
          }
          Stdlib_Option.forEach(Spec.hooks.mutationResolverHook, registerResolver => registerResolver("Aggregate", fieldNames, commandSchema));
          let aggDef = Stdlib_Option.flatMap(pluginStructure, s => s.aggregates.find(d => d.name === M.Spec.name));
          return [{
              fieldNames: fieldNames,
              commandSchema: commandSchema,
              linkedViews: Stdlib_Option.map(aggDef, d => d.linkedViews),
              consistencyRead: Stdlib_Option.flatMap(aggDef, d => d.consistencyRead)
            }];
        });
        let mutationEntries = mutationEntriesFromAggregates.concat(dcbResult.mutationEntries);
        let queryEntriesFromReadModels = readModels.map(R => {
          let qn = Api_Naming$ReventlessCore.queryFieldNamesForReadModel(extra$1, R.Spec.name, undefined);
          let subIdField = Stdlib_Option.map(R.Spec.subIdConfig, c => c.subIdField);
          return {
            singleFieldName: qn.singleFieldName,
            listFieldName: qn.listFieldName,
            returnTypeName: qn.returnTypeName,
            stateSchema: R.Spec.stateSchema,
            authorization: undefined,
            connectionSpec: true,
            subIdField: subIdField
          };
        });
        let queryEntries = queryEntriesFromReadModels.concat(dcbResult.queryEntries);
        let eventLogEntriesFromAggregates = aggregates.map(M => ({
          busKey: M.Spec.name + "AggrEventLog",
          displayName: M.Spec.name,
          eventSchema: M.Spec.eventSchema
        }));
        let eventLogEntries = eventLogEntriesFromAggregates.concat(dcbResult.eventLogEntries);
        readModels.forEach(R => {
          let qn = Api_Naming$ReventlessCore.queryFieldNamesForReadModel(extra$1, R.Spec.name, undefined);
          let match = R.Spec.subIdConfig;
          let qn$1;
          if (match !== undefined) {
            let newrecord = {...qn};
            newrecord.filterTypeName = qn.returnTypeName + "Filter";
            newrecord.itemsFieldName = qn.singleFieldName + "Items";
            qn$1 = newrecord;
          } else {
            qn$1 = qn;
          }
          Plugin_Helpers$ReventlessCore.queryFieldNamesRegistry[R.Spec.name] = qn$1;
        });
        let baseFragment = FragmentProvider.generateFragment(mutationEntries, queryEntries);
        let subResult = Plugin_SubscriptionSchema$ReventlessCore.generate(mutationEntries, queryEntries, eventLogEntries);
        let parts = GraphQL_Stitcher$ReventlessCore.decode(baseFragment);
        let apiSchemaFragment = GraphQL_Stitcher$ReventlessCore.encode({
          types: parts.types.concat(subResult.extraTypes),
          mutations: parts.mutations,
          queries: parts.queries,
          subscriptions: subResult.subscriptionFields
        });
        Stdlib_Option.forEach(Spec.hooks.schemaTypeRegistrationHook, registerTypes => {
          let parts = GraphQL_Stitcher$ReventlessCore.decode(apiSchemaFragment);
          registerTypes(parts.types);
        });
        Stdlib_Option.forEach(Spec.hooks.mcpSchemaRegistrationHook, registerMcp => registerMcp({
          pluginName: extra$1,
          mutationEntries: mutationEntries,
          queryEntries: queryEntries,
          eventLogEntries: eventLogEntries,
          subscriptionFields: GraphQL_Stitcher$ReventlessCore.decode(apiSchemaFragment).subscriptions
        }));
        let aggregatesWithoutEventMappers = Plugin_Helpers$ReventlessCore.createAggregatesWithoutEventMappers(aggregates, api, opts);
        let allEventTopics = Aggregate$ReventlessCore.allEventTopics(aggregatesWithoutEventMappers);
        let dcbOutputs = dcbResult.dcbEventLogOutputs;
        if (dcbOutputs !== undefined) {
          allEventTopics[extra$1 + "DcbEventLog"] = dcbOutputs.eventTopic;
        }
        let readModelsOutputs = Plugin_Helpers$ReventlessCore.createReadModels(readModels, api, apiRole, allEventTopics, opts);
        let allQueryDbs = ReadModel$ReventlessCore.allQueryDbs(readModelsOutputs);
        Object.entries(dcbResult.stateViewSlicesOutputs).forEach(param => {
          allQueryDbs[param[0]] = param[1].queryDb;
        });
        Object.entries(dcbResult.inboundTranslationSlicesOutputs).forEach(param => {
          allQueryDbs[param[0]] = param[1].queryDb;
        });
        let queryEngine = QueryEngineAdapter.make(allQueryDbs);
        let aggregateComponents = aggregates.map(M => {
          let schema_commandTypes = DcbTag$Reventless.extractVariantNames(M.Spec.commandSchema);
          let schema_eventTypes = DcbTag$Reventless.extractVariantNames(M.Spec.eventSchema);
          let schema_errorTypes = DcbTag$Reventless.extractVariantNames(M.Spec.errorSchema);
          let schema_commandSchemas = [SchemaWalker$ReventlessCore.walk(M.Spec.name + ".command", M.Spec.commandSchema)];
          let schema_eventSchemas = [SchemaWalker$ReventlessCore.walk(M.Spec.name + ".event", M.Spec.eventSchema)];
          let schema = {
            commandTypes: schema_commandTypes,
            eventTypes: schema_eventTypes,
            errorTypes: schema_errorTypes,
            commandSchemas: schema_commandSchemas,
            eventSchemas: schema_eventSchemas
          };
          Plugin_Helpers$ReventlessCore.componentSchemaRegistry[M.Spec.name] = schema;
          return {
            name: M.Spec.name,
            kind: "Aggregate",
            schema: schema
          };
        });
        let readModelComponents = readModels.map(R => {
          let qn = Api_Naming$ReventlessCore.queryFieldNamesForReadModel(extra$1, R.Spec.name, undefined);
          let schema_queryFields = [
            qn.singleFieldName,
            qn.listFieldName
          ];
          let schema = {
            queryFields: schema_queryFields
          };
          Plugin_Helpers$ReventlessCore.componentSchemaRegistry[R.Spec.name] = schema;
          return {
            name: R.Spec.name,
            kind: "ReadModel",
            schema: schema
          };
        });
        let mapNames = (d, kind) => Object.keys(d).map(name => ({
          name: name,
          kind: kind,
          schema: {}
        }));
        let components = [
          aggregateComponents,
          readModelComponents,
          mapNames(dcbResult.stateChangeSlicesOutputs, "StateChangeSlice"),
          mapNames(dcbResult.stateViewSlicesOutputs, "StateViewSlice"),
          mapNames(dcbResult.automationSlicesOutputs, "AutomationSlice"),
          mapNames(dcbResult.outboundTranslationSlicesOutputs, "OutboundTranslationSlice"),
          mapNames(dcbResult.inboundTranslationSlicesOutputs, "InboundTranslationSlice")
        ].flat();
        let hook = Plugin_Helpers$ReventlessCore.onPluginBuiltHook.contents;
        if (hook !== undefined) {
          let meta = Plugin_Helpers$ReventlessCore.pluginMetadataRegistry.contents;
          hook({
            name: extra$1,
            version: version,
            kind: Stdlib_Option.flatMap(meta, m => m.kind),
            displayName: Stdlib_Option.flatMap(meta, m => m.displayName),
            vendor: Stdlib_Option.flatMap(meta, m => m.vendor),
            architectureType: Stdlib_Option.flatMap(meta, m => m.architectureType),
            components: components
          });
        }
        let interstackAdminExtensionPoints = Stdlib_Option.mapOr(Interstack$ReventlessCore.coreStackReference, Pulumi.output(undefined), coreStack => coreStack.getOutput("extensionPoints"));
        let localAdminResolvedEP = Output$Pulumi.flatMap(Spec.hooks.adminExtensionPoints.contents, eps => {
          let ep = eps[PluginExtensionPointSpec$ReventlessInfra.name];
          if (ep !== undefined) {
            return ExtensionPoint$ReventlessCore.toResolvedOutputs(ep).apply(r => r);
          } else {
            return Pulumi.output(undefined);
          }
        });
        let pushSchema = Spec.hooks.preResolversSchemaHook;
        let schemaPushed = pushSchema !== undefined ? pushSchema(extra$1, apiSchemaFragment) : Pulumi.output();
        let builderOutputs = Pulumi.all([
          Pulumi.all([
            interstackAdminExtensionPoints,
            localAdminResolvedEP,
            schemaPushed
          ]),
          Pulumi.all(Plugin_Helpers$ReventlessCore.aggregateResources),
          Pulumi.all(Plugin_Helpers$ReventlessCore.publishToAggregates),
          Pulumi.all(Plugin_Helpers$ReventlessCore.publishToReadModels),
          scheduler,
          queryEngine
        ]).apply(param => {
          let queryEngine = param[5];
          let scheduler = param[4];
          let publishToReadModels = param[3];
          let publishToAggregates = param[2];
          let match = param[0];
          let localAdminResolvedEP = match[1];
          let interstackAdminExtensionPoints = match[0];
          let aggregatesOutputs = Plugin_Helpers$ReventlessCore.addEventMappers(allEventTopics, queryEngine);
          let match$1 = Plugin_Helpers$ReventlessCore.createExtensionPoints(extensionPoints, param[1], publishToAggregates, scheduler, queryEngine, Spec.resourceNaming, opts);
          let extensionPointsHandlers = match$1[1];
          let extensionPointsOutputs = match$1[0];
          let coreSetup;
          if (interstackAdminExtensionPoints !== undefined) {
            let pluginExtensionPointUnwrapped = S.parseOrThrow(StackReference$Pulumi.get(interstackAdminExtensionPoints, PluginExtensionPointSpec$ReventlessInfra.name), ExtensionPoint$ReventlessInterop.resolvedOutputsSchema);
            let pluginExtensionPointCommandTopicRemoteChannel = PluginExtensionPointRemoteChannel.make(pluginExtensionPointUnwrapped.commandTopic.resources.map(Adapter$ReventlessCore.fromInteropResolved));
            coreSetup = [
              pluginExtensionPointUnwrapped,
              pluginExtensionPointCommandTopicRemoteChannel
            ];
          } else if (localAdminResolvedEP !== undefined) {
            let remoteChannel = PluginExtensionPointRemoteChannel.make(localAdminResolvedEP.commandTopic.resources.map(Adapter$ReventlessCore.fromInteropResolved));
            coreSetup = [
              localAdminResolvedEP,
              remoteChannel
            ];
          } else {
            coreSetup = undefined;
          }
          let publishToPluginExtensionPoint = coreSetup !== undefined ? coreSetup[1].remotePublish : async param => {};
          let match$2 = Plugin_Helpers$ReventlessCore.createExtensions(extensions, extra$1, publishToPluginExtensionPoint, publishToAggregates, publishToReadModels, queryEngine, opts);
          let extensionsHandlers = match$2[1];
          let extensionsOutputs = match$2[0];
          let extensionPointsDefinitions = Plugin_Helpers$ReventlessCore.extractExtensionPointDefinitions(extensionPointsOutputs);
          let extensionsDefinitions = Plugin_Helpers$ReventlessCore.extractExtensionDefinitions(extensionsOutputs);
          let collectAggregateNames = ex => Belt_SetString.remove(Belt_SetString.fromArray(ex), ExtensionMapping$ReventlessInfra.NoDelegate.name);
          let extensionPointAggregateNames = collectAggregateNames(extensionPointsOutputs.flatMap(ex => ex.aggregateNames));
          let extensionAggregateNames = collectAggregateNames(extensionsOutputs.flatMap(ex => ex.aggregateNames));
          let eventTopics = Aggregate$ReventlessCore.filterEventTopics(aggregatesOutputs, Belt_SetString.union(extensionPointAggregateNames, extensionAggregateNames));
          let dcbOutputs = dcbResult.dcbEventLogOutputs;
          if (dcbOutputs !== undefined) {
            eventTopics[extra$1 + "DcbEventLog"] = dcbOutputs.eventTopic;
          }
          if (coreSetup !== undefined) {
            eventTopics[PluginExtensionPointSpec$ReventlessInfra.name] = {
              resources: coreSetup[0].eventTopic.resources.map(AdapterDeploytime$ReventlessCore.fromInteropResource)
            };
          }
          let childName = ComponentType$ReventlessCore.name(extra$1, Plugin$ReventlessCore.componentType);
          let EventCollectorHelper = Plugin_Helpers$ReventlessCore.MakeEventCollectorHelper(RuntimeEnvironment)(EventCollectorChannel)(PluginRuntimeBuilder);
          let match$3 = EventCollectorHelper.make(childName, eventTopics, opts);
          let eventCollector = match$3[0];
          let capturedDeployTarget = Spec.hooks.deployTarget.contents;
          let pluginDefinition = Pulumi.all([
            extensionPointsDefinitions,
            match$3[2]
          ]).apply(param => ({
            id: id,
            name: extra$1,
            version: version,
            extensionPoints: param[0],
            extensions: extensionsDefinitions,
            eventCollector: param[1],
            extensionProtocols: [],
            apiSchemaFragment: apiSchemaFragment,
            apiTarget: capturedDeployTarget,
            uiFragments: uiFragments,
            structure: pluginStructure
          }));
          if (coreSetup !== undefined) {
            let match$4 = Plugin_Helpers$ReventlessCore.createConnectPluginExtension(pluginDefinition, extensionPointsOutputs, extensionsOutputs, publishToPluginExtensionPoint, publishToAggregates, Plugin_Helpers$ReventlessCore.readModelNamesForSourceName, publishToReadModels, queryEngine, Spec.runtimeOps, Spec.resourceNaming, opts);
            EventCollectorHelper.connect(eventCollector, eventTopics, extensionPointsOutputs, extensionsOutputs, coreSetup[0], pluginDefinition, match$4[1], extensionsHandlers, extensionPointsHandlers, match$4[0]);
          } else {
            EventCollectorHelper.connect(eventCollector, eventTopics, extensionPointsOutputs, extensionsOutputs, undefined, pluginDefinition, undefined, extensionsHandlers, extensionPointsHandlers, undefined);
          }
          let tasksOutputs = Plugin_Helpers$ReventlessCore.createTasks(tasks, aggregatesOutputs, scheduler, publishToAggregates, queryEngine, Spec.resourceNaming, opts);
          let resolvers = Plugin_Helpers$ReventlessCore.createResolvers(allQueryDbs);
          Stdlib_Option.forEach(Spec.hooks.subscriptionInfraHook, hook => hook({
            allQueryDbs: allQueryDbs,
            allEventTopics: allEventTopics,
            eventLogEntries: eventLogEntries,
            opts: opts
          }));
          let SpecificHeartbeat = Heartbeat_Builder$ReventlessCore.Make(HeartbeatRunner);
          let heartbeat = SpecificHeartbeat.make(childName, opts);
          let handler = SpecificHeartbeat.makeHandler(id, heartbeatInterval, publishToPluginExtensionPoint);
          if (coreSetup !== undefined) {
            let pluginExtensionPointCommandTopicRemoteChannel$1 = coreSetup[1];
            Stdlib_Option.forEach(Spec.hooks.onHeartbeatEpChannelAvailable, hook => hook(pluginExtensionPointCommandTopicRemoteChannel$1));
            PluginRuntimeBuilder.forPluginHeartbeat(handler, none => SpecificHeartbeat.connect(none, pluginExtensionPointCommandTopicRemoteChannel$1, heartbeatInterval, heartbeat), undefined, undefined, heartbeat);
          } else {
            PluginRuntimeBuilder.forPluginHeartbeat(handler, param => {}, undefined, undefined, heartbeat);
          }
          Stdlib_Option.forEach(dcbResult.dcbRuntimeSetup, dcbRuntimeSetup => dcbRuntimeSetup());
          return {
            id: id,
            version: version,
            heartbeatInterval: heartbeatInterval,
            eventCollector: match$3[1],
            extensionPoints: Object.fromEntries(extensionPointsOutputs.map(el => [
              el.name,
              el
            ])),
            extensions: Object.fromEntries(extensionsOutputs.map(el => [
              el.name,
              el
            ])),
            aggregates: aggregatesOutputs,
            stateChangeSlices: dcbResult.stateChangeSlicesOutputs,
            stateViewSlices: dcbResult.stateViewSlicesOutputs,
            automationSlices: dcbResult.automationSlicesOutputs,
            outboundTranslationSlices: dcbResult.outboundTranslationSlicesOutputs,
            inboundTranslationSlices: dcbResult.inboundTranslationSlicesOutputs,
            readModels: readModelsOutputs,
            tasks: Object.fromEntries(tasksOutputs.map(el => [
              el.name,
              el
            ])),
            resolvers: resolvers,
            heartbeat: Component$ReventlessCore.outputs(heartbeat),
            dcbEventLog: dcbResult.dcbEventLogOutputs,
            uiFragments: uiFragments
          };
        });
        let pluginOutputs_id = builderOutputs.apply(outputs => outputs.id);
        let pluginOutputs_version = builderOutputs.apply(outputs => outputs.version);
        let pluginOutputs_heartbeatInterval = builderOutputs.apply(outputs => outputs.heartbeatInterval);
        let pluginOutputs_eventCollector = builderOutputs.apply(outputs => outputs.eventCollector);
        let pluginOutputs_extensionPoints = builderOutputs.apply(outputs => outputs.extensionPoints);
        let pluginOutputs_extensions = builderOutputs.apply(outputs => outputs.extensions);
        let pluginOutputs_aggregates = builderOutputs.apply(outputs => outputs.aggregates);
        let pluginOutputs_readModels = builderOutputs.apply(outputs => outputs.readModels);
        let pluginOutputs_tasks = builderOutputs.apply(outputs => outputs.tasks);
        let pluginOutputs_resolvers = builderOutputs.apply(outputs => outputs.resolvers);
        let pluginOutputs_heartbeat = builderOutputs.apply(outputs => outputs.heartbeat);
        let pluginOutputs_apiSchemaFragment = Pulumi.output(apiSchemaFragment);
        let pluginOutputs_uiFragments = builderOutputs.apply(outputs => outputs.uiFragments);
        let pluginOutputs_pluginStructure = Pulumi.output(pluginStructure);
        let pluginOutputs_dcbEventLog = builderOutputs.apply(outputs => outputs.dcbEventLog);
        let pluginOutputs_stateChangeSlices = builderOutputs.apply(outputs => outputs.stateChangeSlices);
        let pluginOutputs_stateViewSlices = builderOutputs.apply(outputs => outputs.stateViewSlices);
        let pluginOutputs_automationSlices = builderOutputs.apply(outputs => outputs.automationSlices);
        let pluginOutputs_outboundTranslationSlices = builderOutputs.apply(outputs => outputs.outboundTranslationSlices);
        let pluginOutputs_inboundTranslationSlices = builderOutputs.apply(outputs => outputs.inboundTranslationSlices);
        let pluginOutputs = {
          id: pluginOutputs_id,
          version: pluginOutputs_version,
          heartbeatInterval: pluginOutputs_heartbeatInterval,
          eventCollector: pluginOutputs_eventCollector,
          extensionPoints: pluginOutputs_extensionPoints,
          extensions: pluginOutputs_extensions,
          aggregates: pluginOutputs_aggregates,
          readModels: pluginOutputs_readModels,
          tasks: pluginOutputs_tasks,
          resolvers: pluginOutputs_resolvers,
          heartbeat: pluginOutputs_heartbeat,
          apiSchemaFragment: pluginOutputs_apiSchemaFragment,
          uiFragments: pluginOutputs_uiFragments,
          pluginStructure: pluginOutputs_pluginStructure,
          dcbEventLog: pluginOutputs_dcbEventLog,
          stateChangeSlices: pluginOutputs_stateChangeSlices,
          stateViewSlices: pluginOutputs_stateViewSlices,
          automationSlices: pluginOutputs_automationSlices,
          outboundTranslationSlices: pluginOutputs_outboundTranslationSlices,
          inboundTranslationSlices: pluginOutputs_inboundTranslationSlices
        };
        Component$ReventlessCore.setOutputs(extra, pluginOutputs);
        Plugin_Helpers$ReventlessCore.interopMetaOutput.contents = builderOutputs.apply(outputs => S.reverseConvertToJsonOrThrow(Plugin_Helpers$ReventlessCore.toInteropMeta(outputs), ExportMeta$ReventlessInterop.schema));
      }, opts);
    };
    return {
      make: make,
      makeAutoUIManifest: makeAutoUIManifest,
      makePluginDefinition: makePluginDefinition
    };
  })))))))))));
}

let PluginExtensionPointSpec;

export {
  PluginExtensionPointSpec,
  Make,
}
/* S Not a pure module */
