// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Component$ReventlessCore from "@reventlessdev/reventless-core/src/components/Component.res.mjs";
import * as QueryDbStorage_InMemory$ReventlessInMemory from "../adapter/QueryDb/QueryDbStorage_InMemory.res.mjs";
import * as QueryDbResolvers_GraphQL$ReventlessInMemory from "../adapter/QueryDb/QueryDbResolvers_GraphQL.res.mjs";
import * as InboundTranslationSlice_Builder$ReventlessCore from "@reventlessdev/reventless-core/src/components/InboundTranslationSlice/InboundTranslationSlice_Builder.res.mjs";

function Make(Bus) {
  let QueryDbStorage = QueryDbStorage_InMemory$ReventlessInMemory.Make(Bus);
  let QueryDbResolvers = QueryDbResolvers_GraphQL$ReventlessInMemory.Make(Bus);
  let api = () => {};
  let apiRole = () => {};
  let Api = {
    api: api,
    apiRole: apiRole
  };
  let CoreMaker = InboundTranslationSlice_Builder$ReventlessCore.Make({
    make: QueryDbStorage.make
  })({
    make: QueryDbResolvers.make
  })(Api);
  let Make$1 = Spec => {
    let LeanSpec_name = Spec.name;
    let LeanSpec_moduleUrl = Spec.moduleUrl;
    let LeanSpec_externalInputSchema = Spec.externalInputSchema;
    let LeanSpec_commandSchema = Spec.commandSchema;
    let LeanSpec_targetName = Spec.targetName;
    let LeanSpec = {
      name: LeanSpec_name,
      moduleUrl: LeanSpec_moduleUrl,
      externalInputSchema: LeanSpec_externalInputSchema,
      commandSchema: LeanSpec_commandSchema,
      targetName: LeanSpec_targetName
    };
    let TranslationImpl_translate = Spec.translate;
    let TranslationImpl_moduleUrl = Spec.moduleUrl;
    let TranslationImpl = {
      translate: TranslationImpl_translate,
      moduleUrl: TranslationImpl_moduleUrl
    };
    let Inner = CoreMaker.Make(LeanSpec)(TranslationImpl);
    return {
      LeanSpec: LeanSpec,
      TranslationImpl: TranslationImpl,
      Inner: Inner,
      Spec: Spec,
      Translation: undefined,
      queryDbName: Inner.queryDbName,
      make: Inner.make,
      operations: Component$ReventlessCore.operations
    };
  };
  return {
    QueryDbStorage: QueryDbStorage,
    QueryDbResolvers: QueryDbResolvers,
    Api: Api,
    CoreMaker: CoreMaker,
    Make: Make$1
  };
}

export {
  Make,
}
/* Component-ReventlessCore Not a pure module */
