// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ExtensionPoint_Builder$Reventless from "@reventlessdev/reventless/src/components/ExtensionPoint/ExtensionPoint_Builder.res.mjs";
import * as CommandTopicChannel_SQS$ReventlessAws from "../adapter/CommandTopic/CommandTopicChannel_SQS.res.mjs";
import * as EventTopicPublisher_SNS$ReventlessAws from "../adapter/EventTopic/EventTopicPublisher_SNS.res.mjs";
import * as RuntimeEnvironment_Lambda$ReventlessAws from "../adapter/Runtime/RuntimeEnvironment_Lambda.res.mjs";
import * as ExtensionPointRuntime_Builder_PerExtensionPoint$Reventless from "@reventlessdev/reventless/src/adapter/Runtime/ExtensionPointRuntime_Builder_PerExtensionPoint.res.mjs";

let ExtensionPointRuntimeBuilder = ExtensionPointRuntime_Builder_PerExtensionPoint$Reventless.Make({
  make: RuntimeEnvironment_Lambda$ReventlessAws.make,
  groupBySource: RuntimeEnvironment_Lambda$ReventlessAws.groupBySource,
  asEventHandler: prim => prim
})({
  make: CommandTopicChannel_SQS$ReventlessAws.make
});

function Make(Spec) {
  return Mappings => ExtensionPoint_Builder$Reventless.Make(Spec)(Mappings)({
    make: RuntimeEnvironment_Lambda$ReventlessAws.make,
    groupBySource: RuntimeEnvironment_Lambda$ReventlessAws.groupBySource,
    asEventHandler: prim => prim
  })({
    make: CommandTopicChannel_SQS$ReventlessAws.make
  })(EventTopicPublisher_SNS$ReventlessAws)({
    forCommandTopic: ExtensionPointRuntimeBuilder.forCommandTopic
  });
}

let CommandTopicChannel;

let RuntimeEnvironment;

export {
  CommandTopicChannel,
  RuntimeEnvironment,
  ExtensionPointRuntimeBuilder,
  Make,
}
/* ExtensionPointRuntimeBuilder Not a pure module */
