// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ExtensionPoint_Builder$Reventless = require("@reventless/reventless/src/components/ExtensionPoint/ExtensionPoint_Builder.res.js");
var CommandTopicChannel_SQS$ReventlessAws = require("../adapter/CommandTopic/CommandTopicChannel_SQS.res.js");
var EventTopicPublisher_SNS$ReventlessAws = require("../adapter/EventTopic/EventTopicPublisher_SNS.res.js");
var RuntimeEnvironment_Lambda$ReventlessAws = require("../adapter/Runtime/RuntimeEnvironment_Lambda.res.js");
var ExtensionPointRuntime_Builder_Micro$Reventless = require("@reventless/reventless/src/adapter/Runtime/ExtensionPointRuntime_Builder_Micro.res.js");

function Make(Spec, Mappings) {
  var partial_arg = EventTopicPublisher_SNS$ReventlessAws;
  var partial_arg$1 = {
    make: CommandTopicChannel_SQS$ReventlessAws.make
  };
  var partial_arg$2 = RuntimeEnvironment_Lambda$ReventlessAws;
  var partial_arg$3 = ExtensionPoint_Builder$Reventless.Make;
  var partial_arg$4 = RuntimeEnvironment_Lambda$ReventlessAws;
  var partial_arg$5 = ExtensionPointRuntime_Builder_Micro$Reventless.Make;
  var $$let = (function (param) {
        return partial_arg$5(partial_arg$4, param);
      })({
        make: CommandTopicChannel_SQS$ReventlessAws.make
      });
  var param = {
    forExtensionPointCommandTopic: $$let.forExtensionPointCommandTopic
  };
  return partial_arg$3(Spec, Mappings, partial_arg$2, partial_arg$1, partial_arg, param);
}

var CommandTopicChannel;

var RuntimeEnvironment;

exports.CommandTopicChannel = CommandTopicChannel;
exports.RuntimeEnvironment = RuntimeEnvironment;
exports.Make = Make;
/* ExtensionPoint_Builder-Reventless Not a pure module */
