// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Aws from "@pulumi/aws";
import * as IAM$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/IAM/IAM.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Pulumi from "@pulumi/pulumi";
import * as Lambda$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/Lambda/Lambda.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as AWS$ReventlessAws from "../AWS.res.mjs";
import * as AWS_Tags$ReventlessAws from "../AWS_Tags.res.mjs";
import * as PolicyDocument$PulumiAws from "@reventlessdev/rescript-pulumi-aws/src/IAM/PolicyDocument.res.mjs";
import * as Util_Bundle$ReventlessAws from "../../util/Util_Bundle.res.mjs";
import * as Util_Pulumi$ReventlessCore from "@reventlessdev/reventless-core/src/util/Util_Pulumi.res.mjs";

let defaultServedPrefix = "uploads";

function make(bucketName, corsOriginsOpt, servedPrefixOpt, nameOpt, opts) {
  let corsOrigins = corsOriginsOpt !== undefined ? corsOriginsOpt : ["*"];
  let servedPrefix = servedPrefixOpt !== undefined ? servedPrefixOpt : defaultServedPrefix;
  let name = nameOpt !== undefined ? nameOpt : "UploadPresignService";
  let opts$1 = Stdlib_Option.map(opts, Util_Pulumi$ReventlessCore.ComponentResourceOptions.toCustomResourceOptions);
  let lambdaRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name, Pulumi.output(AWS$ReventlessAws.Lambda.principal), AWS_Tags$ReventlessAws.make(name, "Platform", "Identity", "Platform", undefined, undefined, undefined, undefined), opts$1);
  bucketName.apply(b => {
    let arn = `arn:aws:s3:::` + b + `/` + servedPrefix + `/*`;
    new (Aws.iam.RolePolicy)(name + `Policy`, {
      policy: PolicyDocument$PulumiAws.toJsonString(PolicyDocument$PulumiAws.make(undefined, name + `Policy`, [
        {
          Sid: "AllowLambdaLogging",
          Effect: "Allow",
          Action: [
            "logs:CreateLogGroup",
            "logs:CreateLogStream",
            "logs:PutLogEvents"
          ],
          Resource: "arn:aws:logs:*:*:*"
        },
        {
          Sid: "AllowUploadPut",
          Effect: "Allow",
          Action: "s3:PutObject",
          Resource: arn
        }
      ])),
      role: lambdaRole.id
    }, opts$1 !== undefined ? Primitive_option.valFromOption(opts$1) : undefined);
  });
  let packageDirs = Object.fromEntries([[
      "@reventlessdev/reventless-aws",
      Util_Bundle$ReventlessAws.resolvePackageRoot(undefined, "@reventlessdev/reventless-aws")
    ]]);
  let match = Util_Bundle$ReventlessAws.buildCodeArchive("@reventlessdev/reventless-aws/src/adapter/Upload/Upload_Presign_S3_Ops.res.mjs", packageDirs, undefined);
  let layers = Stdlib_Option.getOr(Stdlib_Option.map(Lambda$PulumiAws.reventlessLayerArn, arn => [arn]), []);
  let lambda = new (Aws.lambda.Function)(name, {
    handler: "index.handler",
    runtime: "nodejs22.x",
    code: match.code,
    role: lambdaRole.arn,
    memorySize: 256,
    timeout: 30,
    layers: layers,
    tags: AWS_Tags$ReventlessAws.make(name, "Platform", "Runtime", "Platform", undefined, undefined, undefined, undefined),
    environment: {
      variables: Object.fromEntries([
        [
          "Environment",
          Pulumi.getStack()
        ],
        [
          "UPLOAD_BUCKET",
          bucketName
        ],
        [
          "SERVED_PREFIX",
          servedPrefix
        ],
        [
          "NODE_OPTIONS",
          Util_Bundle$ReventlessAws.esmLoaderNodeOptions
        ],
        [
          "ESM_FALLBACK_DIRS",
          Util_Bundle$ReventlessAws.esmFallbackDirs
        ]
      ])
    },
    sourceCodeHash: match.sourceCodeHash
  }, opts$1 !== undefined ? Primitive_option.valFromOption(opts$1) : undefined);
  let functionUrl = new (Aws.lambda.FunctionUrl)(name + `Url`, {
    authorizationType: "NONE",
    functionName: lambda.name,
    cors: {
      allowHeaders: [
        "content-type",
        "authorization"
      ].map(prim => prim),
      allowMethods: ["POST"].map(prim => prim),
      allowOrigins: corsOrigins.map(prim => prim)
    }
  }, opts$1 !== undefined ? Primitive_option.valFromOption(opts$1) : undefined);
  return {
    url: functionUrl.functionUrl,
    resources: [
      lambda.arn,
      functionUrl.functionArn
    ]
  };
}

export {
  defaultServedPrefix,
  make,
}
/* @pulumi/aws Not a pure module */
