// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Aws = require("@pulumi/aws");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var IAM$PulumiAws = require("@reventless/bs-pulumi-aws/src/IAM/IAM.bs.js");
var Output$Pulumi = require("@reventless/bs-pulumi-pulumi/src/Output.bs.js");
var Pulumi = require("@pulumi/pulumi");
var Lambda$PulumiAws = require("@reventless/bs-pulumi-aws/src/Lambda/Lambda.bs.js");
var AppSync_Resolver$PulumiAws = require("@reventless/bs-pulumi-aws/src/AppSync/AppSync_Resolver.bs.js");
var Util_AppSync$ReventlessAws = require("../../util/Util_AppSync.bs.js");
var AppSync_Resolver_Templates$PulumiAws = require("@reventless/bs-pulumi-aws/src/AppSync/AppSync_Resolver_Templates.bs.js");
var ClonerRunner_Fargate_Runtime$ReventlessAws = require("./ClonerRunner_Fargate_Runtime.bs.js");

function make(name, api, fullQualifiedStackName, reventlessCiSecretUrn, secretUrns, opts, param) {
  var cluster = new (Aws.ecs.Cluster)(name, {
        name: name
      }, opts);
  var containerDefinitions = Belt_Option.getExn(Caml_option.undefined_to_opt(JSON.stringify(/* array */[{
                  name: "reventless-ci",
                  image: new Pulumi.Config("ci").require("image"),
                  memory: 512,
                  secrets: /* array */[{
                      name: "reventless-ci",
                      valueFrom: reventlessCiSecretUrn
                    }]
                }])));
  var taskExecutionRole = new (Aws.iam.Role)(name + "TaskExecution", {
        assumeRolePolicy: "{\n  \"Version\": \"2008-10-17\",\n  \"Statement\": [\n    {\n      \"Effect\": \"Allow\",\n      \"Principal\": {\n        \"Service\": \"ecs-tasks.amazonaws.com\"\n      },\n      \"Action\": \"sts:AssumeRole\"\n    }\n  ]\n}\n              ",
        inlinePolicies: /* array */[{
            name: "clonerTask",
            policy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n      {\n          \"Effect\": \"Allow\",\n          \"Action\": [\n              \"logs:PutLogEvents\",\n              \"logs:CreateLogStream\"\n          ],\n          \"Resource\": \"*\"\n      }\n  ]\n}\n                   "
          }]
      }, undefined);
  var secretsManagerAccessPolicy = new (Aws.iam.Policy)("secretsManagerAccess", {
        policy: "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n      {\n          \"Effect\": \"Allow\",\n          \"Action\": [\n              \"secretsmanager:GetRandomPassword\",\n              \"secretsmanager:GetResourcePolicy\",\n              \"secretsmanager:GetSecretValue\",\n              \"secretsmanager:DescribeSecret\",\n              \"secretsmanager:ListSecretVersionIds\"\n          ],\n          \"Resource\": \"*\"\n      }\n  ]\n}\n                   "
      }, undefined);
  new (Aws.iam.RolePolicyAttachment)("ClonerTaskExecutionSecretsManagerAccess", {
        policyArn: secretsManagerAccessPolicy.arn,
        role: taskExecutionRole.name
      }, opts);
  var taskDefinition = new (Aws.ecs.TaskDefinition)(name, {
        family: name,
        containerDefinitions: containerDefinitions,
        cpu: "256",
        memory: "512",
        networkMode: "awsvpc",
        requiresCompatibilities: /* array */["FARGATE"],
        executionRoleArn: taskExecutionRole.arn
      }, opts);
  var resources = secretsManagerAccessPolicy.arn.apply((function (secretsManagerAccessPolicyArn) {
          var partial_arg = cluster.arn;
          var partial_arg$1 = taskDefinition.arn;
          var lambda = new (Aws.lambda.CallbackFunction)(name, Curry.app(Lambda$PulumiAws.CallbackFunction.Args.make, [
                    (function (param, param$1) {
                        return ClonerRunner_Fargate_Runtime$ReventlessAws.clone(partial_arg$1, partial_arg, fullQualifiedStackName, secretUrns, param, param$1);
                      }),
                    undefined,
                    /* array */[secretsManagerAccessPolicyArn],
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    undefined,
                    /* () */0
                  ]), opts !== undefined ? Caml_option.valFromOption(opts) : undefined);
          new (Aws.lambda.Permission)(name, {
                action: "lambda:InvokeFunction",
                function: lambda.arn,
                principal: "appsync.amazonaws.com"
              }, opts !== undefined ? Caml_option.valFromOption(opts) : undefined);
          var dataSourceRole = IAM$PulumiAws.Role.makeWithDefaultPolicy(name + "DS", Pulumi.output("appsync.amazonaws.com"), opts, /* () */0);
          IAM$PulumiAws.RolePolicy.make(name + "DS", "lambda:InvokeFunction", /* array */[lambda.arn], dataSourceRole.id, opts, /* () */0);
          var dataSource = new (Aws.appsync.DataSource)(name, {
                type: "AWS_LAMBDA",
                apiId: Output$Pulumi.flatMap(api, (function (api) {
                        return api.id;
                      })),
                lambdaConfig: {
                  functionArn: lambda.arn
                },
                serviceRoleArn: dataSourceRole.arn
              }, opts);
          var field = "clone";
          var resolver = AppSync_Resolver$PulumiAws.make(field, api, Caml_option.some(dataSource.name), "Mutation", field, "{\n  \"version\": \"2017-02-28\",\n  \"operation\": \"Invoke\",\n  \"payload\": {\n      \"pointInTime\": \$utils.toJson(\$context.arguments.pointInTime),\n      \"meta\": {\n        \"ip\": \$util.toJson(\$context.identity.sourceIp),\n        \"user\": \$util.toJson(\$context.identity.username)\n      }\n  }\n}\n          ", AppSync_Resolver_Templates$PulumiAws.result, /* Unit */0, opts, /* () */0);
          return /* array */[Util_AppSync$ReventlessAws.toResource(resolver)];
        }));
  return /* record */[/* resources */resources];
}

exports.make = make;
/* @pulumi/aws Not a pure module */
